package com.rhn.pharmacy.domain;

public enum DispenseTaskStatus {
    PENDING_REVIEW, INTERVENTION, READY_TO_PICK, REJECTED, PICKING, PARTIALLY_DISPENSED,
    READY_TO_DISPENSE, COMPLETED, PARTIALLY_RETURNED, RETURNED, CANCELLED
}
