package com.rhn.pharmacy.domain;
import com.rhn.shared.id.GlobalIds;
import jakarta.persistence.*;
import java.time.Instant;
@Entity @Table(name="RHN_SUP_STOCK_COUNT")
public class StockCount {
 @Id @Column(name = "ID_STOCK_COUNT") private Long id; @Version @Column(name = "REVISION") private long revision; @Column(name = "ID_TNT", nullable=false)private Long tenantId;
 @Column(name = "ID_ORG", nullable=false)private Long organizationId;@Column(name = "ID_DEPT", nullable=false)private Long departmentId;@Column(name = "ID_STOCK_SITE", nullable=false)private Long stockSiteId;@Column(name = "ID_STOCK_BIN")private Long stockBinId;
 @Column(name = "CD_COUNT_NO", nullable=false)private String countNo;@Column(name = "CD_REQ", nullable=false)private String requestCode;@Column(name = "SD_COUNT_TYPE", nullable=false)private String countType;@Column(name = "SD_STATUS", nullable=false)private String status;
 @Column(name = "DT_SNAP", nullable=false)private Instant snapshotAt;@Column(name = "DT_STARTED")private Instant startedAt;@Column(name = "ID_USER_STARTED")private Long startedBy;@Column(name = "DT_SUBMITTED")private Instant submittedAt;@Column(name = "ID_USER_SUBMITTED")private Long submittedBy;
 @Column(name = "DT_APPROVED")private Instant approvedAt;@Column(name = "ID_USER_APPROVED")private Long approvedBy;@Column(name = "DT_POSTED")private Instant postedAt;@Column(name = "ID_USER_POSTED")private Long postedBy;@Column(name = "DES_REASON") private String reason;@Column(name = "DES_STOCK_COUNT") private String description;
 @Column(name = "ID_INV_TXN")private Long inventoryTransactionId;@Column(name = "DT_CREATED", nullable=false)private Instant createdAt;@Column(name = "ID_USER_CREATED", nullable=false)private Long createdBy;@Column(name = "DT_UPDATED", nullable=false)private Instant updatedAt;@Column(name = "ID_USER_UPDATED", nullable=false)private Long updatedBy;
 protected StockCount(){}
 public StockCount(Long tenantId,Long organizationId,Long departmentId,Long siteId,Long binId,String no,String requestCode,String type,Instant snapshotAt,String reason,String description,Long actor){this.id=GlobalIds.next();this.tenantId=tenantId;this.organizationId=organizationId;this.departmentId=departmentId;this.stockSiteId=siteId;this.stockBinId=binId;this.countNo=no;this.requestCode=requestCode;this.countType=type;this.status="DRAFT";this.snapshotAt=snapshotAt;this.reason=reason;this.description=description;this.createdAt=Instant.now();this.createdBy=actor;this.updatedAt=createdAt;this.updatedBy=actor;}
 public void start(Long actor){require("DRAFT");status="COUNTING";startedAt=Instant.now();startedBy=actor;touch(actor);}public void submit(Long actor){require("COUNTING");status="SUBMITTED";submittedAt=Instant.now();submittedBy=actor;touch(actor);}public void approve(Long actor,String reason){require("SUBMITTED");status="APPROVED";approvedAt=Instant.now();approvedBy=actor;if(reason!=null&&!reason.isBlank())this.reason=reason;touch(actor);}public void reject(Long actor,String reason){require("SUBMITTED");status="REJECTED";approvedAt=Instant.now();approvedBy=actor;this.reason=reason;touch(actor);}public void post(Long actor,Long txn){require("APPROVED");status="POSTED";postedAt=Instant.now();postedBy=actor;inventoryTransactionId=txn;touch(actor);}private void require(String s){if(!s.equals(status))throw new IllegalStateException("盘点单状态不允许当前操作");}private void touch(Long a){updatedAt=Instant.now();updatedBy=a;}
 public Long id(){return id;}public long revision(){return revision;}public Long tenantId(){return tenantId;}public Long organizationId(){return organizationId;}public Long departmentId(){return departmentId;}public Long stockSiteId(){return stockSiteId;}public Long stockBinId(){return stockBinId;}public String countNo(){return countNo;}public String requestCode(){return requestCode;}public String countType(){return countType;}public String status(){return status;}public Instant snapshotAt(){return snapshotAt;}public Instant startedAt(){return startedAt;}public Long startedBy(){return startedBy;}public Instant submittedAt(){return submittedAt;}public Long submittedBy(){return submittedBy;}public Instant approvedAt(){return approvedAt;}public Long approvedBy(){return approvedBy;}public Instant postedAt(){return postedAt;}public Long postedBy(){return postedBy;}public String reason(){return reason;}public String description(){return description;}public Long inventoryTransactionId(){return inventoryTransactionId;}
}
