-- Preserve independent dosage forms when a standard specification becomes an operational medication.

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000001, d.ID_DICT_DEF, 'AEROSOL', '气雾剂', '标准参考目录剂型', 200, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'AEROSOL');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000002, d.ID_DICT_DEF, 'CAPSULE', '胶囊', '标准参考目录剂型', 201, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'CAPSULE');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000003, d.ID_DICT_DEF, 'CHEWABLE_TABLET', '咀嚼片', '标准参考目录剂型', 202, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'CHEWABLE_TABLET');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000004, d.ID_DICT_DEF, 'CONCENTRATE_FOR_INJECTION', '注射用浓溶液', '标准参考目录剂型', 203, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'CONCENTRATE_FOR_INJECTION');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000005, d.ID_DICT_DEF, 'CONTROLLED_RELEASE_TABLET', '控释片', '标准参考目录剂型', 204, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'CONTROLLED_RELEASE_TABLET');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000006, d.ID_DICT_DEF, 'CREAM', '乳膏剂', '标准参考目录剂型', 205, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'CREAM');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000007, d.ID_DICT_DEF, 'DISPERSIBLE_TABLET', '分散片', '标准参考目录剂型', 206, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'DISPERSIBLE_TABLET');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000008, d.ID_DICT_DEF, 'DROPPING_PILL', '滴丸剂', '标准参考目录剂型', 207, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'DROPPING_PILL');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000009, d.ID_DICT_DEF, 'DROPS_UNSPECIFIED', '滴剂', '标准参考目录剂型', 208, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'DROPS_UNSPECIFIED');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000010, d.ID_DICT_DEF, 'DRY_SUSPENSION', '干混悬剂', '标准参考目录剂型', 209, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'DRY_SUSPENSION');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000011, d.ID_DICT_DEF, 'EAR_DROPS', '滴耳剂', '标准参考目录剂型', 210, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'EAR_DROPS');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000012, d.ID_DICT_DEF, 'EFFERVESCENT_TABLET', '泡腾片', '标准参考目录剂型', 211, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'EFFERVESCENT_TABLET');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000013, d.ID_DICT_DEF, 'ELECTUARY', '煎膏剂', '标准参考目录剂型', 212, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'ELECTUARY');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000014, d.ID_DICT_DEF, 'ENEMA', '灌肠剂', '标准参考目录剂型', 213, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'ENEMA');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000015, d.ID_DICT_DEF, 'ENTERIC_CAPSULE', '肠溶胶囊', '标准参考目录剂型', 214, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'ENTERIC_CAPSULE');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000016, d.ID_DICT_DEF, 'ENTERIC_DRY_SUSPENSION', '肠溶干混悬剂', '标准参考目录剂型', 215, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'ENTERIC_DRY_SUSPENSION');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000017, d.ID_DICT_DEF, 'ENTERIC_EXTENDED_TABLET', '肠溶缓释片', '标准参考目录剂型', 216, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'ENTERIC_EXTENDED_TABLET');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000018, d.ID_DICT_DEF, 'ENTERIC_TABLET', '肠溶片', '标准参考目录剂型', 217, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'ENTERIC_TABLET');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000019, d.ID_DICT_DEF, 'EXTENDED_RELEASE_CAPSULE', '缓释胶囊', '标准参考目录剂型', 218, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'EXTENDED_RELEASE_CAPSULE');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000020, d.ID_DICT_DEF, 'EXTENDED_RELEASE_GRANULE', '缓释颗粒', '标准参考目录剂型', 219, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'EXTENDED_RELEASE_GRANULE');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000021, d.ID_DICT_DEF, 'EXTENDED_RELEASE_TABLET', '缓释片', '标准参考目录剂型', 220, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'EXTENDED_RELEASE_TABLET');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000022, d.ID_DICT_DEF, 'EYE_DROPS', '滴眼剂', '标准参考目录剂型', 221, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'EYE_DROPS');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000023, d.ID_DICT_DEF, 'EYE_GEL', '眼用凝胶', '标准参考目录剂型', 222, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'EYE_GEL');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000024, d.ID_DICT_DEF, 'EYE_INJECTION', '眼用注射液', '标准参考目录剂型', 223, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'EYE_INJECTION');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000025, d.ID_DICT_DEF, 'EYE_OINTMENT', '眼膏剂', '标准参考目录剂型', 224, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'EYE_OINTMENT');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000026, d.ID_DICT_DEF, 'GEL', '凝胶剂', '标准参考目录剂型', 225, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'GEL');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000027, d.ID_DICT_DEF, 'GLUCOSE_INJECTION', '葡萄糖注射液', '标准参考目录剂型', 226, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'GLUCOSE_INJECTION');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000028, d.ID_DICT_DEF, 'GRANULE', '颗粒剂', '标准参考目录剂型', 227, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'GRANULE');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000029, d.ID_DICT_DEF, 'INHALATION_AEROSOL', '吸入气雾剂', '标准参考目录剂型', 228, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'INHALATION_AEROSOL');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000030, d.ID_DICT_DEF, 'INHALATION_POWDER', '吸入粉雾剂', '标准参考目录剂型', 229, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'INHALATION_POWDER');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000031, d.ID_DICT_DEF, 'INHALATION_SOLUTION', '吸入溶液剂', '标准参考目录剂型', 230, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'INHALATION_SOLUTION');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000032, d.ID_DICT_DEF, 'INJECTION', '注射液', '标准参考目录剂型', 231, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'INJECTION');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000033, d.ID_DICT_DEF, 'INJECTION_EMULSION', '乳状注射液', '标准参考目录剂型', 232, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'INJECTION_EMULSION');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000034, d.ID_DICT_DEF, 'LINIMENT', '涂剂', '标准参考目录剂型', 233, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'LINIMENT');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000035, d.ID_DICT_DEF, 'LOTION', '洗剂', '标准参考目录剂型', 234, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'LOTION');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000036, d.ID_DICT_DEF, 'MEDICATED_PLASTER', '膏药', '标准参考目录剂型', 235, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'MEDICATED_PLASTER');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000037, d.ID_DICT_DEF, 'MEDICINAL_WINE', '酒剂', '标准参考目录剂型', 236, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'MEDICINAL_WINE');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000038, d.ID_DICT_DEF, 'MIXTURE', '合剂', '标准参考目录剂型', 237, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'MIXTURE');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000039, d.ID_DICT_DEF, 'MUCILAGE', '胶浆剂', '标准参考目录剂型', 238, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'MUCILAGE');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000040, d.ID_DICT_DEF, 'NASAL_DROPS', '滴鼻剂', '标准参考目录剂型', 239, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'NASAL_DROPS');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000041, d.ID_DICT_DEF, 'NASAL_SPRAY', '鼻喷雾剂', '标准参考目录剂型', 240, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'NASAL_SPRAY');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000042, d.ID_DICT_DEF, 'NEBULISER_SUSPENSION', '雾化吸入用混悬液', '标准参考目录剂型', 241, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'NEBULISER_SUSPENSION');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000043, d.ID_DICT_DEF, 'OINTMENT', '软膏剂', '标准参考目录剂型', 242, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'OINTMENT');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000044, d.ID_DICT_DEF, 'ORAL_FILM', '口溶膜', '标准参考目录剂型', 243, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'ORAL_FILM');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000045, d.ID_DICT_DEF, 'ORAL_SOLUTION', '口服溶液剂', '标准参考目录剂型', 244, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'ORAL_SOLUTION');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000046, d.ID_DICT_DEF, 'ORODISPERSIBLE_TABLET', '口崩片', '标准参考目录剂型', 245, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'ORODISPERSIBLE_TABLET');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000047, d.ID_DICT_DEF, 'PATCH', '贴剂', '标准参考目录剂型', 246, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'PATCH');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000048, d.ID_DICT_DEF, 'PILL', '丸剂', '标准参考目录剂型', 247, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'PILL');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000049, d.ID_DICT_DEF, 'PLASTER', '贴膏剂', '标准参考目录剂型', 248, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'PLASTER');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000050, d.ID_DICT_DEF, 'POWDER', '散剂', '标准参考目录剂型', 249, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'POWDER');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000051, d.ID_DICT_DEF, 'POWDER_FORM', '粉剂', '标准参考目录剂型', 250, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'POWDER_FORM');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000052, d.ID_DICT_DEF, 'POWDER_FOR_INJECTION', '注射用无菌粉末', '标准参考目录剂型', 251, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'POWDER_FOR_INJECTION');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000053, d.ID_DICT_DEF, 'SODIUM_CHLORIDE_INJECTION', '氯化钠注射液', '标准参考目录剂型', 252, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'SODIUM_CHLORIDE_INJECTION');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000054, d.ID_DICT_DEF, 'SOFT_CAPSULE', '软胶囊', '标准参考目录剂型', 253, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'SOFT_CAPSULE');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000055, d.ID_DICT_DEF, 'SOLUTION_FOR_INHALATION', '吸入用溶液', '标准参考目录剂型', 254, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'SOLUTION_FOR_INHALATION');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000056, d.ID_DICT_DEF, 'SPRAY', '喷雾剂', '标准参考目录剂型', 255, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'SPRAY');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000057, d.ID_DICT_DEF, 'SUBLINGUAL_TABLET', '舌下片', '标准参考目录剂型', 256, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'SUBLINGUAL_TABLET');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000058, d.ID_DICT_DEF, 'SUPPOSITORY', '栓剂', '标准参考目录剂型', 257, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'SUPPOSITORY');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000059, d.ID_DICT_DEF, 'SUSPENSION', '混悬液', '标准参考目录剂型', 258, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'SUSPENSION');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000060, d.ID_DICT_DEF, 'SYRUP', '糖浆剂', '标准参考目录剂型', 259, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'SYRUP');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000061, d.ID_DICT_DEF, 'TABLET', '片剂', '标准参考目录剂型', 260, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'TABLET');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000062, d.ID_DICT_DEF, 'TINCTURE', '酊剂', '标准参考目录剂型', 261, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'TINCTURE');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000063, d.ID_DICT_DEF, 'TOPICAL_SOLUTION', '外用溶液剂', '标准参考目录剂型', 262, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'TOPICAL_SOLUTION');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000064, d.ID_DICT_DEF, 'VAGINAL_EFFERVESCENT_TABLET', '阴道泡腾片', '标准参考目录剂型', 263, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'VAGINAL_EFFERVESCENT_TABLET');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000065, d.ID_DICT_DEF, 'VAGINAL_SOFT_CAPSULE', '阴道软胶囊', '标准参考目录剂型', 264, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'VAGINAL_SOFT_CAPSULE');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 910430000000066, d.ID_DICT_DEF, 'VAGINAL_TABLET', '阴道片', '标准参考目录剂型', 265, 'ACTIVE'
from RHN_BD_DICT_DEF d where d.CD_DICT_DEF = 'BD_DOSE_FORM' and d.SD_SCOPE_TYPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'VAGINAL_TABLET');
