insert into RHN_SYS_PARAM_DEF (
 ID_PARAM_DEF, ID_PARAM_CAT, CD_PARAM_KEY, NA_PARAM_DEF, DES_PARAM_DEF,
 SD_VAL_TYPE, SD_CONTROL_TYPE, JSON_SCHEMA, JSON_DEFAULT_VAL, JSON_EXAMPLE_VAL,
 UNIT, CD_DICT, JSON_SCOPE, SD_PARAM_CAT, FG_INHERITANCE, FG_CACHE, FG_NULLABLE_VAL,
 SENSITIVITY, SD_DISPLAY_POLICY, SD_STATUS, REVISION,
 DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED,
 CD_DEPENDS_ON_KEY, EXPR_DEPENDS_ON_VAL, SD_DEPENDENCY_BEHAVIOR
) values (
 362387869795122, 362387869794021, 'outpatient.direct-visit.enabled', '启用无挂号直接接诊',
 '医生确认患者身份后优先复用有效挂号；无有效挂号时自动创建不占号源的零元挂号并接诊。科室配置的门诊服务费进入就诊待结算费用，不要求预先支付。',
 'BOOLEAN', 'SWITCH', '{"type":"boolean"}', 'false', 'true', null, null,
 '["ORGANIZATION","DEPARTMENT"]', 'BUSINESS', 1, 1, 0,
 'NORMAL', 'PLAIN', 'ACTIVE', 0, current_timestamp, 362387869790222, current_timestamp, 362387869790222,
 null, null, 'DISABLE_AND_SUPPRESS'
);

insert into RHN_SYS_PARAM_DEF (
 ID_PARAM_DEF, ID_PARAM_CAT, CD_PARAM_KEY, NA_PARAM_DEF, DES_PARAM_DEF,
 SD_VAL_TYPE, SD_CONTROL_TYPE, JSON_SCHEMA, JSON_DEFAULT_VAL, JSON_EXAMPLE_VAL,
 UNIT, CD_DICT, JSON_SCOPE, SD_PARAM_CAT, FG_INHERITANCE, FG_CACHE, FG_NULLABLE_VAL,
 SENSITIVITY, SD_DISPLAY_POLICY, SD_STATUS, REVISION,
 DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED,
 CD_DEPENDS_ON_KEY, EXPR_DEPENDS_ON_VAL, SD_DEPENDENCY_BEHAVIOR
) values (
 362387869795123, 362387869794021, 'outpatient.direct-visit.catalog-item-id', '直接接诊门诊服务',
 '仅允许科室级配置；留空不收门诊服务费。配置后仅自动新建就诊时按机构当前有效价格记费一次，与本次其他费用一起结算；复用原挂号不重复收费。',
 'STRING', 'TEXT', '{"type":"string","pattern":"^([0-9]+)?$"}', 'null', null, null, null,
 '["DEPARTMENT"]', 'BUSINESS', 1, 1, 1,
 'NORMAL', 'PLAIN', 'ACTIVE', 0, current_timestamp, 362387869790222, current_timestamp, 362387869790222,
 null, null, 'DISABLE_AND_SUPPRESS'
);
