-- Independent, disabled-by-default catalog decision pilot. No existing AI overrides are changed.

insert into RHN_SYS_PARAM_DEF (ID_PARAM_DEF, ID_PARAM_CAT, CD_PARAM_KEY, NA_PARAM_DEF, DES_PARAM_DEF, SD_VAL_TYPE, SD_CONTROL_TYPE, JSON_SCHEMA, JSON_DEFAULT_VAL, JSON_SCOPE, SD_PARAM_CAT, FG_INHRT, FG_CACHE, FG_NULLBL_VAL, SENS, SD_DISPLAY_POLICY, SD_STATUS, REVISION, DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED)
select 362387869796200, ID_PARAM_CAT, 'ai.clinical.decision-mode', '目录决策模式', '仅在门诊治疗目录模糊匹配使用，关闭、旁路观察或辅助匹配', 'STRING', 'TEXT', to_clob('{"type":"string","enum":["DISABLED","SHADOW","ASSIST"]}'), to_clob('"DISABLED"'), to_clob('["PLATFORM","TENANT"]'), 'BUSINESS', 1, 0, 0, 'NORMAL', 'PLAIN', 'ACTIVE', 0, CURRENT_TIMESTAMP, ID_USER_CREATED, CURRENT_TIMESTAMP, ID_USER_UPDATED
from RHN_SYS_PARAM_DEF where CD_PARAM_KEY = 'ai.clinical.mode';

insert into RHN_SYS_PARAM_DEF (ID_PARAM_DEF, ID_PARAM_CAT, CD_PARAM_KEY, NA_PARAM_DEF, DES_PARAM_DEF, SD_VAL_TYPE, SD_CONTROL_TYPE, JSON_SCHEMA, JSON_DEFAULT_VAL, JSON_SCOPE, SD_PARAM_CAT, FG_INHRT, FG_CACHE, FG_NULLBL_VAL, SENS, SD_DISPLAY_POLICY, SD_STATUS, REVISION, DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED)
select 362387869796201, ID_PARAM_CAT, 'ai.clinical.decision-model', 'Jev模型标识', '固定模型版本以支持对比与回退', 'STRING', 'TEXT', to_clob('{"type":"string","minLength":1,"maxLength":200}'), to_clob('"jev-1.13.0"'), to_clob('["PLATFORM","TENANT"]'), 'BUSINESS', 1, 0, 0, 'NORMAL', 'PLAIN', 'ACTIVE', 0, CURRENT_TIMESTAMP, ID_USER_CREATED, CURRENT_TIMESTAMP, ID_USER_UPDATED
from RHN_SYS_PARAM_DEF where CD_PARAM_KEY = 'ai.clinical.mode';

insert into RHN_SYS_PARAM_DEF (ID_PARAM_DEF, ID_PARAM_CAT, CD_PARAM_KEY, NA_PARAM_DEF, DES_PARAM_DEF, SD_VAL_TYPE, SD_CONTROL_TYPE, JSON_SCHEMA, JSON_DEFAULT_VAL, JSON_SCOPE, SD_PARAM_CAT, FG_INHRT, FG_CACHE, FG_NULLBL_VAL, SENS, SD_DISPLAY_POLICY, SD_STATUS, REVISION, DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED)
select 362387869796202, ID_PARAM_CAT, 'ai.clinical.decision-endpoint', 'Jev服务地址', 'TypeSafe systemone 完整地址', 'STRING', 'TEXT', to_clob('{"type":"string","minLength":8,"maxLength":1000}'), to_clob('"https://api.typesafe.ai/v1/systemone"'), to_clob('["PLATFORM","TENANT"]'), 'BUSINESS', 1, 0, 0, 'NORMAL', 'PLAIN', 'ACTIVE', 0, CURRENT_TIMESTAMP, ID_USER_CREATED, CURRENT_TIMESTAMP, ID_USER_UPDATED
from RHN_SYS_PARAM_DEF where CD_PARAM_KEY = 'ai.clinical.mode';

insert into RHN_SYS_PARAM_DEF (ID_PARAM_DEF, ID_PARAM_CAT, CD_PARAM_KEY, NA_PARAM_DEF, DES_PARAM_DEF, SD_VAL_TYPE, SD_CONTROL_TYPE, JSON_SCHEMA, JSON_DEFAULT_VAL, JSON_SCOPE, SD_PARAM_CAT, FG_INHRT, FG_CACHE, FG_NULLBL_VAL, SENS, SD_DISPLAY_POLICY, SD_STATUS, REVISION, DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED)
select 362387869796203, ID_PARAM_CAT, 'ai.clinical.decision-api-key', 'Jev API Key', '独立加密凭据，不继承临床生成模型密钥', 'STRING', 'SECRET_REFERENCE', null, null, to_clob('["PLATFORM","TENANT"]'), 'BUSINESS', 1, 0, 1, 'SECRET', 'MASKED', 'ACTIVE', 0, CURRENT_TIMESTAMP, ID_USER_CREATED, CURRENT_TIMESTAMP, ID_USER_UPDATED
from RHN_SYS_PARAM_DEF where CD_PARAM_KEY = 'ai.clinical.mode';

insert into RHN_SYS_PARAM_DEF (ID_PARAM_DEF, ID_PARAM_CAT, CD_PARAM_KEY, NA_PARAM_DEF, DES_PARAM_DEF, SD_VAL_TYPE, SD_CONTROL_TYPE, JSON_SCHEMA, JSON_DEFAULT_VAL, JSON_SCOPE, SD_PARAM_CAT, FG_INHRT, FG_CACHE, FG_NULLBL_VAL, SENS, SD_DISPLAY_POLICY, SD_STATUS, REVISION, DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED)
select 362387869796204, ID_PARAM_CAT, 'ai.clinical.decision-timeout-seconds', '决策请求超时', '目录决策单次等待秒数，失败回退原有流程', 'NUMBER', 'NUMBER', to_clob('{"type":"integer","minimum":1,"maximum":30}'), to_clob('8'), to_clob('["PLATFORM","TENANT"]'), 'BUSINESS', 1, 0, 0, 'NORMAL', 'PLAIN', 'ACTIVE', 0, CURRENT_TIMESTAMP, ID_USER_CREATED, CURRENT_TIMESTAMP, ID_USER_UPDATED
from RHN_SYS_PARAM_DEF where CD_PARAM_KEY = 'ai.clinical.mode';

insert into RHN_SYS_PARAM_DEF (ID_PARAM_DEF, ID_PARAM_CAT, CD_PARAM_KEY, NA_PARAM_DEF, DES_PARAM_DEF, SD_VAL_TYPE, SD_CONTROL_TYPE, JSON_SCHEMA, JSON_DEFAULT_VAL, JSON_SCOPE, SD_PARAM_CAT, FG_INHRT, FG_CACHE, FG_NULLBL_VAL, SENS, SD_DISPLAY_POLICY, SD_STATUS, REVISION, DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED)
select 362387869796205, ID_PARAM_CAT, 'ai.clinical.decision-min-confidence-percent', '匹配置信度门槛', '仅表示分布集中程度，不代表医学正确率', 'NUMBER', 'NUMBER', to_clob('{"type":"integer","minimum":50,"maximum":100}'), to_clob('90'), to_clob('["PLATFORM","TENANT"]'), 'BUSINESS', 1, 0, 0, 'NORMAL', 'PLAIN', 'ACTIVE', 0, CURRENT_TIMESTAMP, ID_USER_CREATED, CURRENT_TIMESTAMP, ID_USER_UPDATED
from RHN_SYS_PARAM_DEF where CD_PARAM_KEY = 'ai.clinical.mode';
