create table inventory_trace_codes (
    id number(19) primary key,
    revision number(19) default 0 not null,
    tenant_id number(19) not null,
    organization_id number(19) not null,
    stock_site_id number(19) not null,
    stock_bin_id number(19),
    stock_item_id number(19) not null,
    stock_lot_id number(19),
    goods_receipt_line_id number(19),
    trace_code varchar2(256 char) not null,
    normalized_code varchar2(256 char) not null,
    product_code_snapshot varchar2(128 char) not null,
    product_name_snapshot varchar2(300 char) not null,
    lot_no_snapshot varchar2(128 char) not null,
    package_quantity number(28,8) not null,
    base_quantity number(28,8) not null,
    status varchar2(32 char) not null,
    current_document_type varchar2(64 char),
    current_document_id number(19),
    current_document_no varchar2(128 char),
    received_at timestamp with time zone,
    issued_at timestamp with time zone,
    created_at timestamp with time zone not null,
    created_by number(19) not null,
    updated_at timestamp with time zone not null,
    updated_by number(19) not null,
    constraint fk_trace_tenant foreign key (tenant_id) references tenants(id),
    constraint fk_trace_org foreign key (tenant_id, organization_id) references organizations(tenant_id, id),
    constraint fk_trace_site foreign key (tenant_id, stock_site_id) references stock_sites(tenant_id, id),
    constraint fk_trace_bin foreign key (tenant_id, stock_bin_id) references stock_bins(tenant_id, id),
    constraint fk_trace_item foreign key (tenant_id, stock_item_id) references stock_items(tenant_id, id),
    constraint fk_trace_lot foreign key (tenant_id, stock_lot_id) references stock_lots(tenant_id, id),
    constraint fk_trace_receipt_line foreign key (tenant_id, goods_receipt_line_id) references goods_receipt_lines(tenant_id, id),
    constraint uk_trace_tenant_id unique (tenant_id, id),
    constraint uk_trace_code unique (tenant_id, normalized_code),
    constraint ck_trace_quantity check (package_quantity > 0 and base_quantity > 0),
    constraint ck_trace_status check (status in ('PENDING_RECEIPT', 'AVAILABLE', 'RESERVED', 'IN_TRANSIT', 'ISSUED', 'RETURNED', 'QUARANTINED', 'DAMAGED', 'RECALLED', 'VOID'))
);
create index idx_trace_site_status on inventory_trace_codes (tenant_id, stock_site_id, status, updated_at);
create index idx_trace_item_lot on inventory_trace_codes (tenant_id, stock_site_id, stock_item_id, stock_lot_id, status);
create index idx_trace_receipt_line on inventory_trace_codes (tenant_id, goods_receipt_line_id, status);
create index idx_trace_document on inventory_trace_codes (tenant_id, current_document_type, current_document_id);

create table inventory_trace_events (
    id number(19) primary key,
    tenant_id number(19) not null,
    organization_id number(19) not null,
    trace_code_id number(19) not null,
    event_type varchar2(64 char) not null,
    from_status varchar2(32 char),
    to_status varchar2(32 char) not null,
    from_site_id number(19),
    to_site_id number(19),
    from_bin_id number(19),
    to_bin_id number(19),
    document_type varchar2(64 char) not null,
    document_id number(19) not null,
    document_no varchar2(128 char) not null,
    reason varchar2(1000 char),
    occurred_at timestamp with time zone not null,
    occurred_by number(19) not null,
    constraint fk_trace_evt_tenant foreign key (tenant_id) references tenants(id),
    constraint fk_trace_evt_org foreign key (tenant_id, organization_id) references organizations(tenant_id, id),
    constraint fk_trace_evt_code foreign key (tenant_id, trace_code_id) references inventory_trace_codes(tenant_id, id),
    constraint fk_trace_evt_from_site foreign key (tenant_id, from_site_id) references stock_sites(tenant_id, id),
    constraint fk_trace_evt_to_site foreign key (tenant_id, to_site_id) references stock_sites(tenant_id, id),
    constraint fk_trace_evt_from_bin foreign key (tenant_id, from_bin_id) references stock_bins(tenant_id, id),
    constraint fk_trace_evt_to_bin foreign key (tenant_id, to_bin_id) references stock_bins(tenant_id, id),
    constraint uk_trace_evt_tenant_id unique (tenant_id, id)
);
create index idx_trace_evt_code on inventory_trace_events (tenant_id, trace_code_id, occurred_at);
create index idx_trace_evt_document on inventory_trace_events (tenant_id, document_type, document_id, occurred_at);
