create table treatment_execution_tasks (
    id number(19,0) primary key,
    revision number(19,0) default 0 not null,
    tenant_id number(19,0) not null,
    organization_id number(19,0) not null,
    department_id number(19,0) not null,
    resident_id number(19,0) not null,
    encounter_id number(19,0) not null,
    source_group_id number(19,0) not null,
    task_no varchar2(64 char) not null,
    task_type varchar2(32 char) not null,
    status varchar2(32 char) not null,
    created_at timestamp with time zone not null,
    started_at timestamp with time zone,
    started_by number(19,0),
    verification_method varchar2(32 char),
    execution_site varchar2(128 char),
    start_note varchar2(1000 char),
    completed_at timestamp with time zone,
    completed_by number(19,0),
    result_code varchar2(32 char),
    completion_note varchar2(2000 char),
    adverse_reaction number(1,0) default 0 not null,
    adverse_reaction_detail varchar2(2000 char),
    exception_note varchar2(1000 char),
    constraint fk_treat_task_tenant foreign key (tenant_id) references tenants(id),
    constraint fk_treat_task_org foreign key (tenant_id,organization_id) references organizations(tenant_id,id),
    constraint fk_treat_task_dept foreign key (tenant_id,organization_id,department_id)
        references departments(tenant_id,organization_id,id),
    constraint fk_treat_task_resident foreign key (tenant_id,resident_id) references residents(tenant_id,id),
    constraint fk_treat_task_encounter foreign key (tenant_id,encounter_id) references encounters(tenant_id,id),
    constraint fk_treat_task_source foreign key (tenant_id,source_group_id) references care_requests(tenant_id,id),
    constraint fk_treat_task_starter foreign key (tenant_id,started_by) references user_accounts(tenant_id,id),
    constraint fk_treat_task_completer foreign key (tenant_id,completed_by) references user_accounts(tenant_id,id),
    constraint uk_treat_task_tenant_id unique (tenant_id,id),
    constraint uk_treat_task_group unique (tenant_id,task_type,source_group_id),
    constraint uk_treat_task_no unique (tenant_id,task_no),
    constraint ck_treat_task_type check (task_type in ('SERVICE','MEDICATION')),
    constraint ck_treat_task_status check (status in ('WAITING_SETTLEMENT','WAITING_DISPENSE','READY','IN_PROGRESS','COMPLETED','CANCELLED','EXCEPTION')),
    constraint ck_treat_task_result check (result_code is null or result_code in ('COMPLETED','INTERRUPTED','NOT_COMPLETED')),
    constraint ck_treat_task_reaction check (adverse_reaction = 0 or adverse_reaction_detail is not null)
);

create table treatment_execution_items (
    id number(19,0) primary key,
    tenant_id number(19,0) not null,
    task_id number(19,0) not null,
    source_type varchar2(32 char) not null,
    source_id number(19,0) not null,
    parent_source_id number(19,0),
    request_no varchar2(64 char) not null,
    item_code_snapshot varchar2(128 char) not null,
    item_name_snapshot varchar2(300 char) not null,
    dose_value number(28,8),
    dose_unit varchar2(64 char),
    route_code varchar2(64 char),
    frequency_code varchar2(64 char),
    duration_value number(12,3),
    duration_unit varchar2(32 char),
    skin_test_required number(1,0) default 0 not null,
    settlement_required number(1,0) default 0 not null,
    settlement_id number(19,0),
    fulfillment_required number(1,0) default 0 not null,
    fulfillment_id number(19,0),
    fulfillment_status varchar2(32 char),
    cancelled_at timestamp with time zone,
    created_at timestamp with time zone not null,
    constraint fk_treat_item_tenant foreign key (tenant_id) references tenants(id),
    constraint fk_treat_item_task foreign key (tenant_id,task_id) references treatment_execution_tasks(tenant_id,id),
    constraint fk_treat_item_source foreign key (tenant_id,source_id) references care_requests(tenant_id,id),
    constraint fk_treat_item_parent foreign key (tenant_id,parent_source_id) references care_requests(tenant_id,id),
    constraint fk_treat_item_settle foreign key (tenant_id,settlement_id) references settlements(tenant_id,id),
    constraint uk_treat_item_tenant_id unique (tenant_id,id),
    constraint uk_treat_item_source unique (tenant_id,source_type,source_id),
    constraint ck_treat_item_source check (source_type in ('SERVICE_REQUEST','MEDICATION_REQUEST')),
    constraint ck_treat_item_settle check (settlement_required = 1 or settlement_id is null),
    constraint ck_treat_item_fulfill check (fulfillment_required = 1 or fulfillment_id is null)
);

create index idx_treat_task_worklist on treatment_execution_tasks(tenant_id,organization_id,department_id,status,created_at);
create index idx_treat_task_encounter on treatment_execution_tasks(tenant_id,encounter_id,created_at);
create index idx_treat_item_task on treatment_execution_items(tenant_id,task_id,created_at);
