-- =============================================================================
-- RHN H2 Compatibility Migration
-- Converts text columns to CLOB for Hibernate schema validation compatibility
-- Preserves column comments for RhnPhysicalSchemaGovernanceTest
-- =============================================================================

alter table RHN_AI_SUGGEST alter column JSON_CONTENT clob;
comment on column RHN_AI_SUGGEST.JSON_CONTENT is '内容JSON';
alter table RHN_AI_SUGGEST alter column JSON_EVID clob;
comment on column RHN_AI_SUGGEST.JSON_EVID is '证据JSON';
alter table RHN_AI_SUGGEST_EVT alter column JSON_ACTION clob;
comment on column RHN_AI_SUGGEST_EVT.JSON_ACTION is '操作JSON';
alter table RHN_AUD_CRYPTO_EVID alter column DES_VERIFICATION_MATERIAL clob;
comment on column RHN_AUD_CRYPTO_EVID.DES_VERIFICATION_MATERIAL is '验证material';
alter table RHN_AUD_CRYPTO_EVID alter column JSON_STATEMENT clob;
comment on column RHN_AUD_CRYPTO_EVID.JSON_STATEMENT is '声明JSON';
alter table RHN_AUD_CRYPTO_EVID alter column SIGNATURE_VALUE clob;
comment on column RHN_AUD_CRYPTO_EVID.SIGNATURE_VALUE is '签名值';
alter table RHN_AUD_CRYPTO_EVID alter column TIMESTAMP_TOKEN clob;
comment on column RHN_AUD_CRYPTO_EVID.TIMESTAMP_TOKEN is '时间戳令牌';
alter table RHN_BD_CATALOG_CHG_ROW alter column JSON_SRC clob;
comment on column RHN_BD_CATALOG_CHG_ROW.JSON_SRC is '来源JSON';
alter table RHN_BD_DICT_ATTR_DEF alter column JSON_SCHEMA clob;
comment on column RHN_BD_DICT_ATTR_DEF.JSON_SCHEMA is '模式定义JSON';
alter table RHN_BD_DICT_CHG alter column JSON_AFTER clob;
comment on column RHN_BD_DICT_CHG.JSON_AFTER is '后JSON';
alter table RHN_BD_DICT_CHG alter column JSON_BEFORE clob;
comment on column RHN_BD_DICT_CHG.JSON_BEFORE is '前JSON';
alter table RHN_BD_IMPORT_ROW alter column JSON_ERRORS clob;
comment on column RHN_BD_IMPORT_ROW.JSON_ERRORS is '错误JSON';
alter table RHN_BD_IMPORT_ROW alter column JSON_NORMALIZED clob;
comment on column RHN_BD_IMPORT_ROW.JSON_NORMALIZED is '标准化JSON';
alter table RHN_BD_IMPORT_ROW alter column JSON_SRC clob;
comment on column RHN_BD_IMPORT_ROW.JSON_SRC is '来源JSON';
alter table RHN_BD_ITEM_ATTR_CHG alter column JSON_AFTER clob;
comment on column RHN_BD_ITEM_ATTR_CHG.JSON_AFTER is '后JSON';
alter table RHN_BD_ITEM_ATTR_CHG alter column JSON_BEFORE clob;
comment on column RHN_BD_ITEM_ATTR_CHG.JSON_BEFORE is '前JSON';
alter table RHN_BD_ITEM_ATTR_DEF alter column JSON_ALLOWED_SCOPE clob;
comment on column RHN_BD_ITEM_ATTR_DEF.JSON_ALLOWED_SCOPE is '允许范围JSON';
alter table RHN_BD_ITEM_ATTR_DEF alter column JSON_DEFAULT clob;
comment on column RHN_BD_ITEM_ATTR_DEF.JSON_DEFAULT is '默认JSON';
alter table RHN_BD_ITEM_ATTR_DEF alter column JSON_SCHEMA clob;
comment on column RHN_BD_ITEM_ATTR_DEF.JSON_SCHEMA is '模式定义JSON';
alter table RHN_BD_ITEM_ATTR_OVRD alter column JSON_VAL clob;
comment on column RHN_BD_ITEM_ATTR_OVRD.JSON_VAL is '值JSON';
alter table RHN_BD_ITEM_ATTR_VAL alter column JSON_VAL clob;
comment on column RHN_BD_ITEM_ATTR_VAL.JSON_VAL is '值JSON';
alter table RHN_BD_ITEM_TYPE_ATTR alter column JSON_DEFAULT clob;
comment on column RHN_BD_ITEM_TYPE_ATTR.JSON_DEFAULT is '默认JSON';
alter table RHN_BD_ITEM_TYPE_ATTR alter column JSON_REQUIRED_COND clob;
comment on column RHN_BD_ITEM_TYPE_ATTR.JSON_REQUIRED_COND is '应需健康问题JSON';
alter table RHN_BD_ITEM_TYPE_ATTR alter column JSON_VISIBLE_COND clob;
comment on column RHN_BD_ITEM_TYPE_ATTR.JSON_VISIBLE_COND is 'visible健康问题JSON';
alter table RHN_EX_CARE_REQ alter column JSON_ITEM_ATTR_SNAP clob;
comment on column RHN_EX_CARE_REQ.JSON_ITEM_ATTR_SNAP is '项目属性快照';
alter table RHN_EX_CARE_REQ alter column JSON_STD_MAP_SNAP clob;
comment on column RHN_EX_CARE_REQ.JSON_STD_MAP_SNAP is 'standard映射快照';
alter table RHN_EX_DIAG_REPORT alter column DES_CONCLUSION clob;
comment on column RHN_EX_DIAG_REPORT.DES_CONCLUSION is '结论';
alter table RHN_EX_MED_REQ alter column FREQUENCY_RULE_SNAPSHOT clob;
comment on column RHN_EX_MED_REQ.FREQUENCY_RULE_SNAPSHOT is '频次规则快照';
alter table RHN_EX_MED_REQ alter column MEDICATION_SNAPSHOT clob;
comment on column RHN_EX_MED_REQ.MEDICATION_SNAPSHOT is '药品快照';
alter table RHN_EX_TREAT_EXEC_ITEM alter column FREQUENCY_RULE_SNAPSHOT clob;
comment on column RHN_EX_TREAT_EXEC_ITEM.FREQUENCY_RULE_SNAPSHOT is '频次规则快照';
alter table RHN_HPL_CARE_TASK_EVT alter column JSON_EVID clob;
comment on column RHN_HPL_CARE_TASK_EVT.JSON_EVID is '证据JSON';
alter table RHN_INT_EXT_MSG alter column JSON_PAYLOAD clob;
comment on column RHN_INT_EXT_MSG.JSON_PAYLOAD is '载荷JSON';
alter table RHN_INT_IDEMP_RECORD alter column JSON_RESP clob;
comment on column RHN_INT_IDEMP_RECORD.JSON_RESP is '响应JSON';
alter table RHN_INT_OUTBOX_EVT alter column JSON_PAYLOAD clob;
comment on column RHN_INT_OUTBOX_EVT.JSON_PAYLOAD is '载荷JSON';
alter table RHN_META_OP_NOTE_FORM_VER alter column JSON_DEF clob;
comment on column RHN_META_OP_NOTE_FORM_VER.JSON_DEF is '定义JSON';
alter table RHN_META_OP_NOTE_TMPL alter column JSON_CONTENT clob;
comment on column RHN_META_OP_NOTE_TMPL.JSON_CONTENT is '内容JSON';
alter table RHN_META_PRINT_TMPL_VER alter column JSON_CONFIG clob;
comment on column RHN_META_PRINT_TMPL_VER.JSON_CONFIG is '配置JSON';
alter table RHN_PI_PAT_MATCH_CAND alter column JSON_REASONS clob;
comment on column RHN_PI_PAT_MATCH_CAND.JSON_REASONS is '原因JSON';
alter table RHN_PI_PAT_MERGE_HIST alter column MOVED_IDENTIFIER_IDS clob;
comment on column RHN_PI_PAT_MERGE_HIST.MOVED_IDENTIFIER_IDS is 'moved标识ids';
alter table RHN_PI_PAT_MERGE_HIST alter column MOVED_SOURCE_RECORD_IDS clob;
comment on column RHN_PI_PAT_MERGE_HIST.MOVED_SOURCE_RECORD_IDS is 'moved来源记录ids';
alter table RHN_PI_PAT_SPLIT_HIST alter column RESTORED_IDENTIFIER_IDS clob;
comment on column RHN_PI_PAT_SPLIT_HIST.RESTORED_IDENTIFIER_IDS is 'restored标识ids';
alter table RHN_PI_PAT_SRC_RECORD alter column JSON_RAW_PAYLOAD clob;
comment on column RHN_PI_PAT_SRC_RECORD.JSON_RAW_PAYLOAD is 'raw载荷JSON';
alter table RHN_SC_SCHED_GEN_RUN alter column JSON_REQ clob;
comment on column RHN_SC_SCHED_GEN_RUN.JSON_REQ is '请求JSON';
alter table RHN_SUP_DISP_TASK_LINE alter column JSON_ITEM_ATTR_SNAP clob;
comment on column RHN_SUP_DISP_TASK_LINE.JSON_ITEM_ATTR_SNAP is '项目属性快照';
alter table RHN_SYS_ANN alter column DES_CONTENT clob;
comment on column RHN_SYS_ANN.DES_CONTENT is '内容文本';
alter table RHN_SYS_PARAM_CHG alter column JSON_AFTER clob;
comment on column RHN_SYS_PARAM_CHG.JSON_AFTER is '后JSON';
alter table RHN_SYS_PARAM_CHG alter column JSON_BEFORE clob;
comment on column RHN_SYS_PARAM_CHG.JSON_BEFORE is '前JSON';
alter table RHN_SYS_PARAM_DEF alter column JSON_DEFAULT_VAL clob;
comment on column RHN_SYS_PARAM_DEF.JSON_DEFAULT_VAL is '默认值JSON';
alter table RHN_SYS_PARAM_DEF alter column JSON_EXAMPLE_VAL clob;
comment on column RHN_SYS_PARAM_DEF.JSON_EXAMPLE_VAL is 'example值JSON';
alter table RHN_SYS_PARAM_DEF alter column JSON_SCHEMA clob;
comment on column RHN_SYS_PARAM_DEF.JSON_SCHEMA is 'JSON模式定义';
alter table RHN_SYS_PARAM_DEF alter column JSON_SCOPE clob;
comment on column RHN_SYS_PARAM_DEF.JSON_SCOPE is '范围JSON';
alter table RHN_SYS_PARAM_VAL alter column JSON_VAL clob;
comment on column RHN_SYS_PARAM_VAL.JSON_VAL is '值JSON';
alter table RHN_SYS_PORTAL_USER_WKSPACE alter column JSON_FAVORITES clob;
comment on column RHN_SYS_PORTAL_USER_WKSPACE.JSON_FAVORITES is '收藏JSON';
alter table RHN_SYS_PORTAL_USER_WKSPACE alter column JSON_LAYOUT clob;
comment on column RHN_SYS_PORTAL_USER_WKSPACE.JSON_LAYOUT is '布局JSON';
alter table RHN_SYS_PORTAL_USER_WKSPACE alter column JSON_TABS clob;
comment on column RHN_SYS_PORTAL_USER_WKSPACE.JSON_TABS is '标签页JSON';
alter table RHN_SYS_PRINT_OUTPUT alter column CONTENT_BASE64 clob;
comment on column RHN_SYS_PRINT_OUTPUT.CONTENT_BASE64 is '内容base64';
alter table RHN_SYS_PRINT_OUTPUT alter column JSON_SNAP clob;
comment on column RHN_SYS_PRINT_OUTPUT.JSON_SNAP is '快照JSON';
alter table RHN_VIS_CLIN_DOC_VER alter column JSON_CONTENT clob;
comment on column RHN_VIS_CLIN_DOC_VER.JSON_CONTENT is '内容JSON';
alter table RHN_VIS_ENC_IDENT_CHECK alter column JSON_FACTOR_RESULT clob;
comment on column RHN_VIS_ENC_IDENT_CHECK.JSON_FACTOR_RESULT is '换算系数resultsJSON';
alter table RHN_VIS_HEALTH_EVT alter column JSON_PAYLOAD clob;
comment on column RHN_VIS_HEALTH_EVT.JSON_PAYLOAD is '载荷JSON';
alter table RHN_VIS_INP_NURS_RECORD alter column JSON_ASSESSMENT clob;
comment on column RHN_VIS_INP_NURS_RECORD.JSON_ASSESSMENT is '评估JSON';
alter table RHN_VIS_INP_NURS_RECORD alter column JSON_CONTENT clob;
comment on column RHN_VIS_INP_NURS_RECORD.JSON_CONTENT is '内容JSON';
alter table RHN_VIS_INP_NURS_RECORD alter column JSON_OBS_SUM clob;
comment on column RHN_VIS_INP_NURS_RECORD.JSON_OBS_SUM is '观察汇总JSON';
alter table RHN_VIS_INP_SHIFT_HANDOFF alter column JSON_GENERAL_ITEM clob;
comment on column RHN_VIS_INP_SHIFT_HANDOFF.JSON_GENERAL_ITEM is '通用itemsJSON';
alter table RHN_VIS_INP_SHIFT_HANDOFF_ITEM alter column JSON_PENDING_ACTIONS clob;
comment on column RHN_VIS_INP_SHIFT_HANDOFF_ITEM.JSON_PENDING_ACTIONS is '待办操作JSON';
alter table RHN_VIS_INP_SHIFT_HANDOFF_ITEM alter column JSON_RISK_FLAGS clob;
comment on column RHN_VIS_INP_SHIFT_HANDOFF_ITEM.JSON_RISK_FLAGS is 'risk标志JSON';
