ALTER TABLE RHN_EX_REQ_GRP ALTER COLUMN JSON_DOC_INFO CLOB;
COMMENT ON COLUMN RHN_EX_REQ_GRP.JSON_DOC_INFO IS '处方单据信息JSON';
ALTER TABLE RHN_EX_CARE_REQ ALTER COLUMN JSON_DOC_INFO CLOB;
COMMENT ON COLUMN RHN_EX_CARE_REQ.JSON_DOC_INFO IS '诊疗申请单据信息JSON';
