-- Separate resident identifiers from RC038 identity-document classification.
-- Preserve platform and tenant dictionary choices; do not infer types for existing patient rows.
-- No score is available for identifier evidence whose type/issuer is unverified.
alter table RHN_PI_PAT_MATCH_CAND alter column MATCH_SCORE drop not null;
insert into RHN_BD_DICT_DEF (ID_DICT_DEF, REVISION, SD_SCOPE_TYPE, CD_SCOPE, ID_TNT,
    CD_DICT_DEF, NA_DICT_DEF, DES_DICT_DEF, SD_STATUS, DT_CREATED, ID_USER_CREATED,
    DT_UPDATED, ID_USER_UPDATED, FG_SYS_MANAGED, ID_DICT_CAT)
select ID_DICT_DEF + 1000000000, 0, SD_SCOPE_TYPE, CD_SCOPE, ID_TNT,
    'PI_RESIDENT_IDENTIFIER_SYSTEM', '居民标识类型',
    '居民证件及卡号命名空间；卡证编码不替代RC038标准证件类别', SD_STATUS,
    CURRENT_TIMESTAMP, ID_USER_CREATED, CURRENT_TIMESTAMP, ID_USER_UPDATED, FG_SYS_MANAGED, ID_DICT_CAT
from RHN_BD_DICT_DEF where CD_DICT_DEF = 'PI_IDENTIFIER_TYPE';

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM,
    DES_DICT_ITEM, SN_SORT, SD_STATUS, ID_DICT_ITEM_PARENT)
select i.ID_DICT_ITEM + 1000000000, i.ID_DICT_DEF_DICT + 1000000000, i.CD_DICT_ITEM,
    i.NA_DICT_ITEM, i.DES_DICT_ITEM, i.SN_SORT, i.SD_STATUS, i.ID_DICT_ITEM_PARENT + 1000000000
from RHN_BD_DICT_ITEM i join RHN_BD_DICT_DEF d on d.ID_DICT_DEF = i.ID_DICT_DEF_DICT
where d.CD_DICT_DEF = 'PI_IDENTIFIER_TYPE';

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 362388869850100, ID_DICT_DEF, 'SOCIAL_SECURITY_CARD', '社会保障卡', '独立保存原始标识类型；无核实的发卡范围时仅作为人工核对依据', 80, 'ACTIVE'
from RHN_BD_DICT_DEF d where CD_DICT_DEF = 'PI_RESIDENT_IDENTIFIER_SYSTEM' and CD_SCOPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'SOCIAL_SECURITY_CARD');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 362388869850101, ID_DICT_DEF, 'HEALTH_CARD', '居民健康卡', '独立保存原始标识类型；无核实的发卡范围时仅作为人工核对依据', 90, 'ACTIVE'
from RHN_BD_DICT_DEF d where CD_DICT_DEF = 'PI_RESIDENT_IDENTIFIER_SYSTEM' and CD_SCOPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'HEALTH_CARD');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 362388869850102, ID_DICT_DEF, 'HOSPITAL_MRN', '机构病案号', '独立保存原始标识类型；无核实的发卡范围时仅作为人工核对依据', 100, 'ACTIVE'
from RHN_BD_DICT_DEF d where CD_DICT_DEF = 'PI_RESIDENT_IDENTIFIER_SYSTEM' and CD_SCOPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'HOSPITAL_MRN');

insert into RHN_BD_DICT_ITEM (ID_DICT_ITEM, ID_DICT_DEF_DICT, CD_DICT_ITEM, NA_DICT_ITEM, DES_DICT_ITEM, SN_SORT, SD_STATUS)
select 362388869850103, ID_DICT_DEF, 'BIRTH_CERTIFICATE', '出生医学证明', '独立保存原始标识类型；无核实的发卡范围时仅作为人工核对依据', 110, 'ACTIVE'
from RHN_BD_DICT_DEF d where CD_DICT_DEF = 'PI_RESIDENT_IDENTIFIER_SYSTEM' and CD_SCOPE = 'PLATFORM'
and not exists (select 1 from RHN_BD_DICT_ITEM i where i.ID_DICT_DEF_DICT = d.ID_DICT_DEF and i.CD_DICT_ITEM = 'BIRTH_CERTIFICATE');
