insert into RHN_SYS_PARAM_CAT (
    ID_PARAM_CAT, ID_PARAM_CAT_PARENT, CD_PARAM_CAT, NA_PARAM_CAT, DES_PARAM_CAT, SN_SORT,
    FG_ACTIVE, REVISION, DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED
) values (
    362387869794071, 362387869794020, 'OUTPATIENT_DOCTOR_WORKSTATION', '门诊医生站',
    '门诊医生接诊、病历签署和诊毕收口的交互策略', 20,
    true, 0, current_timestamp, 362387869790222, current_timestamp, 362387869790222
);

insert into RHN_SYS_PARAM_DEF (
    ID_PARAM_DEF, ID_PARAM_CAT, CD_PARAM_KEY, NA_PARAM_DEF, DES_PARAM_DEF,
    SD_VAL_TYPE, SD_CONTROL_TYPE, JSON_SCHEMA, JSON_DEFAULT_VAL, JSON_EXAMPLE_VAL,
    UNIT, CD_DICT, JSON_SCOPE, SD_PARAM_CAT, FG_INHERITANCE, FG_CACHE, FG_NULLABLE_VAL,
    SENSITIVITY, SD_DISPLAY_POLICY, SD_STATUS, REVISION,
    DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED
) values (
    362387869795120, 362387869794071,
    'outpatient.doctor-workstation.completion-mode', '门诊诊毕签署交互模式',
    'COMBINED_CONFIRMATION 在诊毕最终确认时合并完成病历签署；SEPARATE_CONFIRMATIONS 要求医生先单独签署再诊毕。两种模式均保留签署证据，均不允许绕过后端诊毕准入。',
    'STRING', 'SELECT',
    '{"type":"string","enum":["COMBINED_CONFIRMATION","SEPARATE_CONFIRMATIONS"]}',
    '"COMBINED_CONFIRMATION"', '"SEPARATE_CONFIRMATIONS"',
    null, null, '["PLATFORM","TENANT","ORGANIZATION","DEPARTMENT"]', 'BUSINESS',
    true, true, false, 'NORMAL', 'PLAIN', 'ACTIVE', 0,
    current_timestamp, 362387869790222, current_timestamp, 362387869790222
);
