-- =============================================================================
-- Outpatient Prescription Inventory Freeze System Parameter
-- =============================================================================

insert into RHN_SYS_PARAM_DEF (
    ID_PARAM_DEF,
    ID_PARAM_CAT,
    CD_PARAM_KEY,
    NA_PARAM_DEF,
    DES_PARAM_DEF,
    SD_VAL_TYPE,
    SD_CONTROL_TYPE,
    JSON_SCHEMA,
    JSON_DEFAULT_VAL,
    JSON_EXAMPLE_VAL,
    UNIT,
    CD_DICT,
    JSON_SCOPE,
    SD_PARAM_CAT,
    FG_INHERITANCE,
    FG_CACHE,
    FG_NULLABLE_VAL,
    SENSITIVITY,
    SD_DISPLAY_POLICY,
    SD_STATUS,
    REVISION,
    DT_CREATED,
    ID_USER_CREATED,
    DT_UPDATED,
    ID_USER_UPDATED
) values (
    362387869795080,
    362387869794021,
    'outpatient.prescription.inventory-freeze.enabled',
    '启用门诊处方开立库存冻结',
    '控制门诊医生提交处方时是否立即冻结目标发药药房的可用库存；启用时超量开立直接阻断，撤销处方时释放冻结；关闭时仅在收费结算后冻结或发药扣减',
    'BOOLEAN',
    'SWITCH',
    '{"type":"boolean"}',
    'true',
    'true',
    null,
    null,
    '["PLATFORM","TENANT","ORGANIZATION","DEPARTMENT"]',
    'BUSINESS',
    true,
    true,
    false,
    'NORMAL',
    'PLAIN',
    'ACTIVE',
    0,
    current_timestamp,
    362387869790222,
    current_timestamp,
    362387869790222
);
