-- 将常规非专管药品从单列医嘱（FG_SINGLE_ORDER=1）纠正为常规处方药品（FG_SINGLE_ORDER=0）
update RHN_BD_MED set FG_SINGLE_ORDER = 0 where CD_MED in (
  'DEMO-DRUG-PARA',
  'DEMO-DRUG-CRO',
  'DEMO-DRUG-SALB',
  'DEMO-DRUG-LHQW',
  'DEMO-DRUG-HUANGQI',
  'DEMO-DRUG-FLU-VAC',
  'DEMO-DRUG-PEN-G',
  'DRUG-AMOX',
  'DRUG-MET',
  'DRUG-AML',
  'DRUG-VB1-INJ'
);
