ALTER TABLE RHN_EX_REQ_GRP ADD JSON_DOC_INFO TEXT;
ALTER TABLE RHN_EX_CARE_REQ ADD JSON_DOC_INFO TEXT;
COMMENT ON COLUMN RHN_EX_REQ_GRP.JSON_DOC_INFO IS '处方单据信息JSON';
COMMENT ON COLUMN RHN_EX_CARE_REQ.JSON_DOC_INFO IS '诊疗申请单据信息JSON';
