-- Governed physical-column abbreviations. Preserve data, keys, indexes and comments.
-- Logical names and Java/API properties are unchanged. See docs/database/column-renames-1.77.0.json.


-- ai.ai_suggestion_event
ALTER TABLE RHN_AI_SUGGEST_EVT RENAME COLUMN DT_OCCURRED TO DT_OCCRD;

-- ai.ai_suggestion
ALTER TABLE RHN_AI_SUGGEST RENAME COLUMN CD_PROVIDER TO CD_PRVDR;
ALTER TABLE RHN_AI_SUGGEST RENAME COLUMN CD_KNOWLEDGE_VER TO CD_KNOW_VER;
ALTER TABLE RHN_AI_SUGGEST RENAME COLUMN DT_GENERATED TO DT_GEND;
ALTER TABLE RHN_AI_SUGGEST RENAME COLUMN DT_INVALIDATED TO DT_INVLDD;
ALTER TABLE RHN_AI_SUGGEST RENAME COLUMN DES_INVALIDATION_REASON TO DES_INVLDN_REASON;
ALTER TABLE RHN_AI_SUGGEST RENAME COLUMN ID_PRACT_REQUESTED TO ID_PRACT_REQD;
ALTER TABLE RHN_AI_SUGGEST RENAME COLUMN ID_USER_REQUESTED TO ID_USER_REQD;

-- vis.allergy_intolerance
ALTER TABLE RHN_VIS_ALLERGY_INTOL RENAME COLUMN SD_ASSERTION_TYPE TO SD_ASSERT_TYPE;
ALTER TABLE RHN_VIS_ALLERGY_INTOL RENAME COLUMN SD_VERIFICATION_STATUS TO SD_VRFCTN_STATUS;
ALTER TABLE RHN_VIS_ALLERGY_INTOL RENAME COLUMN CD_CRITICALITY TO CD_CRITCL;
ALTER TABLE RHN_VIS_ALLERGY_INTOL RENAME COLUMN SD_REACTION_SEVERITY TO SD_REACT_SEV;
ALTER TABLE RHN_VIS_ALLERGY_INTOL RENAME COLUMN SD_INFORMATION_SRC TO SD_INFO_SRC;
ALTER TABLE RHN_VIS_ALLERGY_INTOL RENAME COLUMN CD_SUBSTANCE_CODE_SYS_URI TO CD_SUBST_CODE_SYS_URI;
ALTER TABLE RHN_VIS_ALLERGY_INTOL RENAME COLUMN CD_SUBSTANCE TO CD_SUBST;
ALTER TABLE RHN_VIS_ALLERGY_INTOL RENAME COLUMN NA_SUBSTANCE TO NA_SUBST;
ALTER TABLE RHN_VIS_ALLERGY_INTOL RENAME COLUMN DES_REACTION TO DES_REACT;
ALTER TABLE RHN_VIS_ALLERGY_INTOL RENAME COLUMN DT_RECORDED TO DT_RECDD;
ALTER TABLE RHN_VIS_ALLERGY_INTOL RENAME COLUMN ID_PRACT_RECORDER TO ID_PRACT_RECDR;
ALTER TABLE RHN_VIS_ALLERGY_INTOL RENAME COLUMN ID_USER_RECORDER TO ID_USER_RECDR;
ALTER TABLE RHN_VIS_ALLERGY_INTOL RENAME COLUMN DT_VERIFIED TO DT_VRFD;
ALTER TABLE RHN_VIS_ALLERGY_INTOL RENAME COLUMN ID_PRACT_VERIFIER TO ID_PRACT_VRFR;
ALTER TABLE RHN_VIS_ALLERGY_INTOL RENAME COLUMN DT_INACTIVATED TO DT_INACTD;
ALTER TABLE RHN_VIS_ALLERGY_INTOL RENAME COLUMN ID_USER_INACTIVATED TO ID_USER_INACTD;
ALTER TABLE RHN_VIS_ALLERGY_INTOL RENAME COLUMN DES_INACTIVATION_REASON TO DES_INACTN_REASON;
ALTER TABLE RHN_VIS_ALLERGY_INTOL RENAME COLUMN ID_ALLERGEN TO ID_ALRGN;

-- sc.appointment_event
ALTER TABLE RHN_SC_APPT_EVT RENAME COLUMN ID_APPT_REPLACEMENT TO ID_APPT_RPLCMNT;
ALTER TABLE RHN_SC_APPT_EVT RENAME COLUMN DT_OCCURRED TO DT_OCCRD;
ALTER TABLE RHN_SC_APPT_EVT RENAME COLUMN ID_USER_OCCURRED TO ID_USER_OCCRD;

-- sc.appointment
ALTER TABLE RHN_SC_APPT RENAME COLUMN DT_CONFIRMED TO DT_CNFRMD;
ALTER TABLE RHN_SC_APPT RENAME COLUMN DT_CANCELLED TO DT_CNCLD;
ALTER TABLE RHN_SC_APPT RENAME COLUMN DES_CANCELLATION_REASON TO DES_CNCLN_REASON;
ALTER TABLE RHN_SC_APPT RENAME COLUMN ID_APPT_RESCHEDULED_FROM TO ID_APPT_RESCHD_FROM;

-- aud.audit_log
ALTER TABLE RHN_AUD_LOG RENAME COLUMN ID_CORRELATION TO ID_CORR;
ALTER TABLE RHN_AUD_LOG RENAME COLUMN DT_OCCURRED TO DT_OCCRD;

-- ex.care_request
ALTER TABLE RHN_EX_CARE_REQ RENAME COLUMN CD_PRIORITY TO CD_PRI;
ALTER TABLE RHN_EX_CARE_REQ RENAME COLUMN DA_BUSINESS TO DA_BIZ;
ALTER TABLE RHN_EX_CARE_REQ RENAME COLUMN DT_AUTHORED TO DT_AUTHRD;
ALTER TABLE RHN_EX_CARE_REQ RENAME COLUMN ID_USER_AUTHORED TO ID_USER_AUTHRD;
ALTER TABLE RHN_EX_CARE_REQ RENAME COLUMN DT_CANCELLED TO DT_CNCLD;
ALTER TABLE RHN_EX_CARE_REQ RENAME COLUMN ID_USER_CANCELLED TO ID_USER_CNCLD;
ALTER TABLE RHN_EX_CARE_REQ RENAME COLUMN ID_ORG_CATALOG_ITEM_ADOPTION TO ID_ORG_CATALOG_ITEM_ADOPT;
ALTER TABLE RHN_EX_CARE_REQ RENAME COLUMN SN_ADOPTION_VER TO SN_ADOPT_VER;
ALTER TABLE RHN_EX_CARE_REQ RENAME COLUMN CD_CURRENCY TO CD_CCY;
ALTER TABLE RHN_EX_CARE_REQ RENAME COLUMN DT_ITEM_ATTR_RESOLVED TO DT_ITEM_ATTR_RSLVD;

-- hpl.care_task_event
ALTER TABLE RHN_HPL_CARE_TASK_EVT RENAME COLUMN DES_RESULT_DESCRIPTION TO DES_RESULT_DESCR;
ALTER TABLE RHN_HPL_CARE_TASK_EVT RENAME COLUMN DT_OCCURRED TO DT_OCCRD;

-- hpl.care_task
ALTER TABLE RHN_HPL_CARE_TASK RENAME COLUMN SD_PRIORITY TO SD_PRI;
ALTER TABLE RHN_HPL_CARE_TASK RENAME COLUMN CD_ESCALATION_RULE TO CD_ESCLN_RULE;

-- bil.cashier_close_event
ALTER TABLE RHN_BIL_CASHIER_CLOSE_EVT RENAME COLUMN DT_OCCURRED TO DT_OCCRD;

-- bil.cashier_close_item
ALTER TABLE RHN_BIL_CASHIER_CLOSE_ITEM RENAME COLUMN CD_CURRENCY TO CD_CCY;

-- bil.cashier_close_line
ALTER TABLE RHN_BIL_CASHIER_CLOSE_LINE RENAME COLUMN AMT_EXPECTED TO AMT_EXPCTD;
ALTER TABLE RHN_BIL_CASHIER_CLOSE_LINE RENAME COLUMN AMT_DIFFERENCE TO AMT_DIFF;
ALTER TABLE RHN_BIL_CASHIER_CLOSE_LINE RENAME COLUMN CD_CURRENCY TO CD_CCY;

-- bil.cashier_close
ALTER TABLE RHN_BIL_CASHIER_CLOSE RENAME COLUMN ID_CASHIER_CLOSE_REVERSES TO ID_CASHIER_CLOSE_RVRS;
ALTER TABLE RHN_BIL_CASHIER_CLOSE RENAME COLUMN CD_TERMINAL TO CD_TRMNL;
ALTER TABLE RHN_BIL_CASHIER_CLOSE RENAME COLUMN AMT_EXPECTED TO AMT_EXPCTD;
ALTER TABLE RHN_BIL_CASHIER_CLOSE RENAME COLUMN AMT_DIFFERENCE TO AMT_DIFF;
ALTER TABLE RHN_BIL_CASHIER_CLOSE RENAME COLUMN CD_CURRENCY TO CD_CCY;
ALTER TABLE RHN_BIL_CASHIER_CLOSE RENAME COLUMN DES_DIFFERENCE_REASON TO DES_DIFF_REASON;
ALTER TABLE RHN_BIL_CASHIER_CLOSE RENAME COLUMN ID_USER_CONFIRMED TO ID_USER_CNFRMD;
ALTER TABLE RHN_BIL_CASHIER_CLOSE RENAME COLUMN DT_CONFIRMED TO DT_CNFRMD;

-- bd.catalog_change_batch
ALTER TABLE RHN_BD_CATALOG_CHG_BATCH RENAME COLUMN SD_OPERATION_TYPE TO SD_OPER_TYPE;
ALTER TABLE RHN_BD_CATALOG_CHG_BATCH RENAME COLUMN DA_BUSINESS TO DA_BIZ;
ALTER TABLE RHN_BD_CATALOG_CHG_BATCH RENAME COLUMN QTY_SUCCEEDED_ROW TO QTY_SUCCDD_ROW;

-- bd.catalog_item
ALTER TABLE RHN_BD_CATALOG_ITEM RENAME COLUMN FG_ORDERABLE TO FG_ORDRBL;
ALTER TABLE RHN_BD_CATALOG_ITEM RENAME COLUMN FG_CHARGEABLE TO FG_CHGBL;

-- bd.catalog_price
ALTER TABLE RHN_BD_CATALOG_PRICE RENAME COLUMN CD_CURRENCY TO CD_CCY;
ALTER TABLE RHN_BD_CATALOG_PRICE RENAME COLUMN ID_CATALOG_PRICE_REPLACES TO ID_CATALOG_PRICE_RPLCS;

-- bil.charge_item_component
ALTER TABLE RHN_BIL_CHARGE_ITEM_COMP RENAME COLUMN QTY_COMPONENT TO QTY_COMP;
ALTER TABLE RHN_BIL_CHARGE_ITEM_COMP RENAME COLUMN AMT_COMPONENT TO AMT_COMP;

-- bil.charge_item
ALTER TABLE RHN_BIL_CHARGE_ITEM RENAME COLUMN CD_CURRENCY TO CD_CCY;
ALTER TABLE RHN_BIL_CHARGE_ITEM RENAME COLUMN DT_OCCURRED TO DT_OCCRD;
ALTER TABLE RHN_BIL_CHARGE_ITEM RENAME COLUMN ID_CHARGE_ITEM_REVERSES TO ID_CHARGE_ITEM_RVRS;

-- vis.clinical_document_version
ALTER TABLE RHN_VIS_CLIN_DOC_VER RENAME COLUMN CONTENT_DIGEST_ALGORITHM TO CONTENT_DIGEST_ALGO;
ALTER TABLE RHN_VIS_CLIN_DOC_VER RENAME COLUMN ID_CRYPTO_EVID_INTEGRITY TO ID_CRYPTO_EVID_INTGR;

-- vis.clinical_document
ALTER TABLE RHN_VIS_CLIN_DOC RENAME COLUMN CD_INSTANCE_KEY TO CD_INST_KEY;

-- bd.code_system
ALTER TABLE RHN_BD_CODE_SYSTEM RENAME COLUMN CD_CANONICAL_URI TO CD_CANON_URI;
ALTER TABLE RHN_BD_CODE_SYSTEM RENAME COLUMN DA_EFFECTIVE_FROM TO DA_EFF_FROM;
ALTER TABLE RHN_BD_CODE_SYSTEM RENAME COLUMN DA_EFFECTIVE_TO TO DA_EFF_TO;
ALTER TABLE RHN_BD_CODE_SYSTEM RENAME COLUMN PUBLISHER TO PUBLSHR;
ALTER TABLE RHN_BD_CODE_SYSTEM RENAME COLUMN SD_AUTHORITY_TYPE TO SD_AUTHRTY_TYPE;

-- bd.concept_mapping
ALTER TABLE RHN_BD_CONCEPT_MAP RENAME COLUMN SD_EQUIVALENCE TO SD_EQUIV;

-- bd.concept
ALTER TABLE RHN_BD_CONCEPT RENAME COLUMN DA_EFFECTIVE_FROM TO DA_EFF_FROM;
ALTER TABLE RHN_BD_CONCEPT RENAME COLUMN DA_EFFECTIVE_TO TO DA_EFF_TO;
ALTER TABLE RHN_BD_CONCEPT RENAME COLUMN ID_CONCEPT_REPLACEMENT TO ID_CONCEPT_RPLCMNT;

-- hpl.condition
ALTER TABLE RHN_HPL_COND RENAME COLUMN SD_VERIFICATION_STATUS TO SD_VRFCTN_STATUS;
ALTER TABLE RHN_HPL_COND RENAME COLUMN DT_ABATEMENT TO DT_ABATE;
ALTER TABLE RHN_HPL_COND RENAME COLUMN DT_RECORDED TO DT_RECDD;
ALTER TABLE RHN_HPL_COND RENAME COLUMN ID_PRACT_RECORDER TO ID_PRACT_RECDR;
ALTER TABLE RHN_HPL_COND RENAME COLUMN ID_USER_RECORDER TO ID_USER_RECDR;

-- sys.configuration_definition
ALTER TABLE RHN_SYS_CFG_DEF RENAME COLUMN FG_INHERITANCE TO FG_INHRT;

-- sys.configuration_revision
ALTER TABLE RHN_SYS_CFG_REV RENAME COLUMN DT_EFFECTIVE_FROM TO DT_EFF_FROM;
ALTER TABLE RHN_SYS_CFG_REV RENAME COLUMN DT_EFFECTIVE_TO TO DT_EFF_TO;

-- vis.critical_value_alert_event
ALTER TABLE RHN_VIS_CRIT_VAL_ALERT_EVT RENAME COLUMN ID_CORRELATION TO ID_CORR;
ALTER TABLE RHN_VIS_CRIT_VAL_ALERT_EVT RENAME COLUMN DT_OCCURRED TO DT_OCCRD;

-- vis.critical_value_alert
ALTER TABLE RHN_VIS_CRIT_VAL_ALERT RENAME COLUMN ID_USER_RECIPIENT TO ID_USER_RCPNT;
ALTER TABLE RHN_VIS_CRIT_VAL_ALERT RENAME COLUMN SD_SEVERITY TO SD_SEV;
ALTER TABLE RHN_VIS_CRIT_VAL_ALERT RENAME COLUMN DT_DETECTED TO DT_DTCTD;
ALTER TABLE RHN_VIS_CRIT_VAL_ALERT RENAME COLUMN DT_ACKNOWLEDGE_DEADLINE TO DT_ACK_DDLN;
ALTER TABLE RHN_VIS_CRIT_VAL_ALERT RENAME COLUMN ID_USER_ACKNOWLEDGED TO ID_USER_ACKD;
ALTER TABLE RHN_VIS_CRIT_VAL_ALERT RENAME COLUMN DT_ACKNOWLEDGED TO DT_ACKD;
ALTER TABLE RHN_VIS_CRIT_VAL_ALERT RENAME COLUMN DES_ACKNOWLEDGE_NOTE TO DES_ACK_NOTE;
ALTER TABLE RHN_VIS_CRIT_VAL_ALERT RENAME COLUMN CD_DISPOSITION TO CD_DISPOS;
ALTER TABLE RHN_VIS_CRIT_VAL_ALERT RENAME COLUMN ID_DIAG_REPORT_SUPERSEDED TO ID_DIAG_REPORT_SPRSDD;
ALTER TABLE RHN_VIS_CRIT_VAL_ALERT RENAME COLUMN SD_ESCALATION_LEVEL TO SD_ESCLN_LEVEL;

-- aud.cryptographic_evidence
ALTER TABLE RHN_AUD_CRYPTO_EVID RENAME COLUMN CD_OPERATION TO CD_OPER;
ALTER TABLE RHN_AUD_CRYPTO_EVID RENAME COLUMN SD_PROTECTION_PROF TO SD_PROT_PROF;
ALTER TABLE RHN_AUD_CRYPTO_EVID RENAME COLUMN SD_PROTECTION_PURPOSE TO SD_PROT_PURPOSE;
ALTER TABLE RHN_AUD_CRYPTO_EVID RENAME COLUMN CONTENT_DIGEST_ALGORITHM TO CONTENT_DIGEST_ALGO;
ALTER TABLE RHN_AUD_CRYPTO_EVID RENAME COLUMN SN_STATEMENT_VER TO SN_STMT_VER;
ALTER TABLE RHN_AUD_CRYPTO_EVID RENAME COLUMN JSON_STATEMENT TO JSON_STMT;
ALTER TABLE RHN_AUD_CRYPTO_EVID RENAME COLUMN STATEMENT_DIGEST_ALGORITHM TO STMT_DIGEST_ALGO;
ALTER TABLE RHN_AUD_CRYPTO_EVID RENAME COLUMN HASH_STATEMENT TO HASH_STMT;
ALTER TABLE RHN_AUD_CRYPTO_EVID RENAME COLUMN ID_CRYPTO_EVID_PREVIOUS TO ID_CRYPTO_EVID_PREV;
ALTER TABLE RHN_AUD_CRYPTO_EVID RENAME COLUMN CD_PROVIDER TO CD_PRVDR;
ALTER TABLE RHN_AUD_CRYPTO_EVID RENAME COLUMN PROVIDER_ASSURANCE TO PRVDR_ASSUR;
ALTER TABLE RHN_AUD_CRYPTO_EVID RENAME COLUMN SD_SIGN_ALGORITHM TO SD_SIGN_ALGO;
ALTER TABLE RHN_AUD_CRYPTO_EVID RENAME COLUMN SIGNATURE_VALUE TO SIGNTR_VALUE;
ALTER TABLE RHN_AUD_CRYPTO_EVID RENAME COLUMN DES_VERIFICATION_MATERIAL TO DES_VRFCTN_MATL;
ALTER TABLE RHN_AUD_CRYPTO_EVID RENAME COLUMN CD_CERTIFICATE_SERIAL TO CD_CERT_SERIAL;
ALTER TABLE RHN_AUD_CRYPTO_EVID RENAME COLUMN CERTIFICATE_ISSUER TO CERT_ISSUER;
ALTER TABLE RHN_AUD_CRYPTO_EVID RENAME COLUMN TIMESTAMP_AUTHORITY TO TS_AUTHRTY;
ALTER TABLE RHN_AUD_CRYPTO_EVID RENAME COLUMN TIMESTAMP_TOKEN TO TS_TOKEN;
ALTER TABLE RHN_AUD_CRYPTO_EVID RENAME COLUMN ID_CORRELATION TO ID_CORR;
ALTER TABLE RHN_AUD_CRYPTO_EVID RENAME COLUMN DT_RECORDED TO DT_RECDD;

-- sys.department_capability
ALTER TABLE RHN_SYS_DEPT_CAP RENAME COLUMN CD_QUALIFICATION_BASIS TO CD_QUALIF_BASIS;

-- sys.department_responsibility
ALTER TABLE RHN_SYS_DEPT_RESP RENAME COLUMN NA_EXT_RESPONSIBLE TO NA_EXT_RSPNSBL;

-- sys.department
ALTER TABLE RHN_SYS_DEPT RENAME COLUMN SD_DEPT_PROPERTY TO SD_DEPT_PROP;

-- ex.diagnostic_execution_task
ALTER TABLE RHN_EX_DIAG_EXEC_TASK RENAME COLUMN DT_COLLECTED TO DT_COLLD;
ALTER TABLE RHN_EX_DIAG_EXEC_TASK RENAME COLUMN ID_USER_COLLECTED TO ID_USER_COLLD;
ALTER TABLE RHN_EX_DIAG_EXEC_TASK RENAME COLUMN DES_COLLECTION_NOTE TO DES_COLL_NOTE;
ALTER TABLE RHN_EX_DIAG_EXEC_TASK RENAME COLUMN DT_COMPLETED TO DT_CMPLD;
ALTER TABLE RHN_EX_DIAG_EXEC_TASK RENAME COLUMN ID_USER_COMPLETED TO ID_USER_CMPLD;
ALTER TABLE RHN_EX_DIAG_EXEC_TASK RENAME COLUMN DT_CANCELLED TO DT_CNCLD;

-- ex.diagnostic_report
ALTER TABLE RHN_EX_DIAG_REPORT RENAME COLUMN CD_ENDPOINT TO CD_ENDPT;
ALTER TABLE RHN_EX_DIAG_REPORT RENAME COLUMN ID_DIAG_REPORT_REPLACES TO ID_DIAG_REPORT_RPLCS;
ALTER TABLE RHN_EX_DIAG_REPORT RENAME COLUMN DT_RECEIVED TO DT_RECVD;
ALTER TABLE RHN_EX_DIAG_REPORT RENAME COLUMN DES_CONCLUSION TO DES_CONCL;
ALTER TABLE RHN_EX_DIAG_REPORT RENAME COLUMN CONTENT_DIGEST_ALGORITHM TO CONTENT_DIGEST_ALGO;

-- bd.dictionary_attribute_definition
ALTER TABLE RHN_BD_DICT_ATTR_DEF RENAME COLUMN SD_CARDINALITY TO SD_CARDNL;
ALTER TABLE RHN_BD_DICT_ATTR_DEF RENAME COLUMN ID_DICT_DEF_REFERENCE_DICT TO ID_DICT_DEF_REF_DICT;
ALTER TABLE RHN_BD_DICT_ATTR_DEF RENAME COLUMN FG_REQUIRED_VAL TO FG_RQD_VAL;
ALTER TABLE RHN_BD_DICT_ATTR_DEF RENAME COLUMN FG_SEARCHABLE TO FG_SRCHBL;

-- bd.dictionary_item_attribute_value
ALTER TABLE RHN_BD_DICT_ITEM_ATTR_VAL RENAME COLUMN DT_DATETIME_VAL TO DT_DTTM_VAL;
ALTER TABLE RHN_BD_DICT_ITEM_ATTR_VAL RENAME COLUMN ID_DICT_ITEM_REFERENCE TO ID_DICT_ITEM_REF;

-- hpl.disease_management_member
ALTER TABLE RHN_HPL_DISEASE_MGMT_MEMBER RENAME COLUMN DA_EFFECTIVE_FROM TO DA_EFF_FROM;
ALTER TABLE RHN_HPL_DISEASE_MGMT_MEMBER RENAME COLUMN DA_EFFECTIVE_TO TO DA_EFF_TO;
ALTER TABLE RHN_HPL_DISEASE_MGMT_MEMBER RENAME COLUMN SD_INCLUSION_MODE TO SD_INCL_MODE;

-- hpl.disease_management_program
ALTER TABLE RHN_HPL_DISEASE_MGMT_PROG RENAME COLUMN QTY_REPORT_DEADLINE_HOURS TO QTY_REPORT_DDLN_HOURS;
ALTER TABLE RHN_HPL_DISEASE_MGMT_PROG RENAME COLUMN DA_EFFECTIVE_FROM TO DA_EFF_FROM;
ALTER TABLE RHN_HPL_DISEASE_MGMT_PROG RENAME COLUMN DA_EFFECTIVE_TO TO DA_EFF_TO;

-- hpl.disease_management_rule
ALTER TABLE RHN_HPL_DISEASE_MGMT_RULE RENAME COLUMN SD_INCLUSION_MODE TO SD_INCL_MODE;

-- sup.dispense_task_line
ALTER TABLE RHN_SUP_DISP_TASK_LINE RENAME COLUMN QTY_REQUESTED TO QTY_REQD;
ALTER TABLE RHN_SUP_DISP_TASK_LINE RENAME COLUMN QTY_DISPENSED TO QTY_DSPNSD;
ALTER TABLE RHN_SUP_DISP_TASK_LINE RENAME COLUMN QTY_RETURNED TO QTY_RETD;
ALTER TABLE RHN_SUP_DISP_TASK_LINE RENAME COLUMN BASE_QUANTITY_FACTOR TO BASE_QTY_FACTOR;
ALTER TABLE RHN_SUP_DISP_TASK_LINE RENAME COLUMN FG_TRACE_REQUIRED TO FG_TRACE_RQD;
ALTER TABLE RHN_SUP_DISP_TASK_LINE RENAME COLUMN PACKAGE_SPEC_SNAPSHOT TO PACKAGE_SPEC_SNAP;

-- sup.dispense_task
ALTER TABLE RHN_SUP_DISP_TASK RENAME COLUMN SD_PRIORITY TO SD_PRI;
ALTER TABLE RHN_SUP_DISP_TASK RENAME COLUMN ID_ASSIGNED_PRACT TO ID_ASGND_PRACT;
ALTER TABLE RHN_SUP_DISP_TASK RENAME COLUMN DES_PICK_DESCRIPTION TO DES_PICK_DESCR;

-- vis.encounter_completion_check
ALTER TABLE RHN_VIS_ENC_COMP_CHECK RENAME COLUMN SN_EXPECTED_VER TO SN_EXPCTD_VER;

-- vis.encounter_completion_issue
ALTER TABLE RHN_VIS_ENC_COMP_ISSUE RENAME COLUMN SD_SEVERITY TO SD_SEV;

-- vis.encounter_diagnosis
ALTER TABLE RHN_VIS_ENC_DIAG RENAME COLUMN DT_RECORDED TO DT_RECDD;
ALTER TABLE RHN_VIS_ENC_DIAG RENAME COLUMN CD_BUSINESS_VER_NO TO CD_BIZ_VER_NO;
ALTER TABLE RHN_VIS_ENC_DIAG RENAME COLUMN SD_VERIFICATION_STATUS TO SD_VRFCTN_STATUS;
ALTER TABLE RHN_VIS_ENC_DIAG RENAME COLUMN CODE_SYSTEM_VERSION_SNAPSHOT TO CODE_SYSTEM_VERSION_SNAP;

-- vis.encounter_diagnosis_revision
ALTER TABLE RHN_VIS_ENC_DIAG_REV RENAME COLUMN CD_BUSINESS_VER_NO TO CD_BIZ_VER_NO;
ALTER TABLE RHN_VIS_ENC_DIAG_REV RENAME COLUMN SD_VERIFICATION_STATUS TO SD_VRFCTN_STATUS;
ALTER TABLE RHN_VIS_ENC_DIAG_REV RENAME COLUMN DT_OCCURRED TO DT_OCCRD;
ALTER TABLE RHN_VIS_ENC_DIAG_REV RENAME COLUMN CODE_SYSTEM_VERSION_SNAPSHOT TO CODE_SYSTEM_VERSION_SNAP;

-- vis.encounter_identity_check
ALTER TABLE RHN_VIS_ENC_IDENT_CHECK RENAME COLUMN SD_CHECK_SCENARIO TO SD_CHECK_SCEN;
ALTER TABLE RHN_VIS_ENC_IDENT_CHECK RENAME COLUMN CD_TERMINAL TO CD_TRMNL;
ALTER TABLE RHN_VIS_ENC_IDENT_CHECK RENAME COLUMN DT_OCCURRED TO DT_OCCRD;

-- vis.encounter_status_event
ALTER TABLE RHN_VIS_ENC_STATUS_EVT RENAME COLUMN SN_EXPECTED_VER TO SN_EXPCTD_VER;
ALTER TABLE RHN_VIS_ENC_STATUS_EVT RENAME COLUMN DT_OCCURRED TO DT_OCCRD;

-- vis.encounter_work_session
ALTER TABLE RHN_VIS_ENC_WORK_SESSION RENAME COLUMN CD_TERMINAL TO CD_TRMNL;
ALTER TABLE RHN_VIS_ENC_WORK_SESSION RENAME COLUMN DT_HEARTBEAT TO DT_HRTBT;

-- vis.encounter
ALTER TABLE RHN_VIS_ENC RENAME COLUMN ID_CLINICIAN TO ID_CLNCN;
ALTER TABLE RHN_VIS_ENC RENAME COLUMN DES_CHIEF_COMPLAINT TO DES_CHIEF_CMPLNT;
ALTER TABLE RHN_VIS_ENC RENAME COLUMN SYSTOLIC TO SBP;
ALTER TABLE RHN_VIS_ENC RENAME COLUMN DIASTOLIC TO DBP;
ALTER TABLE RHN_VIS_ENC RENAME COLUMN DT_REGISTERED TO DT_REGD;
ALTER TABLE RHN_VIS_ENC RENAME COLUMN DT_COMPLETED TO DT_CMPLD;
ALTER TABLE RHN_VIS_ENC RENAME COLUMN CD_TERMINATION TO CD_TRMN;
ALTER TABLE RHN_VIS_ENC RENAME COLUMN DES_TERMINATION_REASON TO DES_TRMN_REASON;
ALTER TABLE RHN_VIS_ENC RENAME COLUMN DT_TERMINATED TO DT_TRMND;
ALTER TABLE RHN_VIS_ENC RENAME COLUMN ID_USER_TERMINATED TO ID_USER_TRMND;

-- int.event_consumption
ALTER TABLE RHN_INT_EVT_CONSUME RENAME COLUMN NA_CONSUMER TO NA_CNSMR;
ALTER TABLE RHN_INT_EVT_CONSUME RENAME COLUMN DT_PROCESSED TO DT_PROCSD;

-- ex.examination_attachment_item
ALTER TABLE RHN_EX_EXAM_ATTACH_ITEM RENAME COLUMN FG_REQUIRED_ATTACH TO FG_RQD_ATTACH;
ALTER TABLE RHN_EX_EXAM_ATTACH_ITEM RENAME COLUMN FG_SEPARATELY_CHARGEABLE TO FG_SEPRLY_CHGBL;

-- bd.examination_service
ALTER TABLE RHN_BD_EXAM_SVC RENAME COLUMN FG_BODY_SITE_REQUIRED TO FG_BODY_SITE_RQD;
ALTER TABLE RHN_BD_EXAM_SVC RENAME COLUMN DES_PREPARATION_DESCRIPTION TO DES_PREP_DESCR;
ALTER TABLE RHN_BD_EXAM_SVC RENAME COLUMN QTY_INCLUDED_SITE TO QTY_INCLD_SITE;
ALTER TABLE RHN_BD_EXAM_SVC RENAME COLUMN QTY_MAX_CHARGEABLE_SITE TO QTY_MAX_CHGBL_SITE;

-- int.external_message
ALTER TABLE RHN_INT_EXT_MSG RENAME COLUMN CD_ENDPOINT TO CD_ENDPT;
ALTER TABLE RHN_INT_EXT_MSG RENAME COLUMN SD_DIRECTION TO SD_DIR;
ALTER TABLE RHN_INT_EXT_MSG RENAME COLUMN ID_BUSINESS_MSG TO ID_BIZ_MSG;
ALTER TABLE RHN_INT_EXT_MSG RENAME COLUMN ID_CORRELATION TO ID_CORR;
ALTER TABLE RHN_INT_EXT_MSG RENAME COLUMN PAYLOAD_DIGEST_ALGORITHM TO PAYLOAD_DIGEST_ALGO;
ALTER TABLE RHN_INT_EXT_MSG RENAME COLUMN DT_RECEIVED TO DT_RECVD;
ALTER TABLE RHN_INT_EXT_MSG RENAME COLUMN DT_PROCESSED TO DT_PROCSD;

-- sup.goods_receipt_line
ALTER TABLE RHN_SUP_GOOD_RCPT_LINE RENAME COLUMN ID_STOCK_BIN_DESTINATION TO ID_STOCK_BIN_DEST;
ALTER TABLE RHN_SUP_GOOD_RCPT_LINE RENAME COLUMN DA_PRODUCTION TO DA_PROD;
ALTER TABLE RHN_SUP_GOOD_RCPT_LINE RENAME COLUMN QTY_DELIVERED TO QTY_DELIVD;
ALTER TABLE RHN_SUP_GOOD_RCPT_LINE RENAME COLUMN QTY_ACCEPTED TO QTY_ACPTD;
ALTER TABLE RHN_SUP_GOOD_RCPT_LINE RENAME COLUMN QTY_REJECTED TO QTY_REJCTD;
ALTER TABLE RHN_SUP_GOOD_RCPT_LINE RENAME COLUMN DES_REJECTION_REASON TO DES_REJCTN_REASON;

-- sup.goods_receipt
ALTER TABLE RHN_SUP_GOOD_RCPT RENAME COLUMN DT_RECEIVED TO DT_RECVD;
ALTER TABLE RHN_SUP_GOOD_RCPT RENAME COLUMN ID_USER_RECEIVED TO ID_USER_RECVD;
ALTER TABLE RHN_SUP_GOOD_RCPT RENAME COLUMN DT_INSPECTED TO DT_INSPTD;
ALTER TABLE RHN_SUP_GOOD_RCPT RENAME COLUMN ID_USER_INSPECTED TO ID_USER_INSPTD;

-- vis.health_event
ALTER TABLE RHN_VIS_HEALTH_EVT RENAME COLUMN DT_OCCURRED TO DT_OCCRD;
ALTER TABLE RHN_VIS_HEALTH_EVT RENAME COLUMN DT_RECORDED TO DT_RECDD;
ALTER TABLE RHN_VIS_HEALTH_EVT RENAME COLUMN ID_USER_RECORDED TO ID_USER_RECDD;
ALTER TABLE RHN_VIS_HEALTH_EVT RENAME COLUMN ID_CORRELATION TO ID_CORR;

-- aud.iam_authorization_event
ALTER TABLE RHN_AUD_IAM_AUTH_EVT RENAME COLUMN DT_OCCURRED TO DT_OCCRD;

-- int.idempotency_record
ALTER TABLE RHN_INT_IDEMP_RECORD RENAME COLUMN CD_OPERATION TO CD_OPER;
ALTER TABLE RHN_INT_IDEMP_RECORD RENAME COLUMN DT_COMPLETED TO DT_CMPLD;

-- vis.inpatient_bed_day_fact
ALTER TABLE RHN_VIS_INP_BED_DAY_FACT RENAME COLUMN DA_BUSINESS TO DA_BIZ;

-- vis.inpatient_bed_profile
ALTER TABLE RHN_VIS_INP_BED_PROF RENAME COLUMN SD_GENDER_RESTRICTION TO SD_GENDER_RSTRCT;
ALTER TABLE RHN_VIS_INP_BED_PROF RENAME COLUMN SD_OPERATIONAL_STATUS TO SD_OPERAT_STATUS;
ALTER TABLE RHN_VIS_INP_BED_PROF RENAME COLUMN ID_RESPONSIBLE_NURSE TO ID_RSPNSBL_NURSE;

-- vis.inpatient_chart_event
ALTER TABLE RHN_VIS_INP_CHART_EVT RENAME COLUMN DT_OCCURRED TO DT_OCCRD;
ALTER TABLE RHN_VIS_INP_CHART_EVT RENAME COLUMN ID_USER_RECORDED TO ID_USER_RECDD;
ALTER TABLE RHN_VIS_INP_CHART_EVT RENAME COLUMN DT_RECORDED TO DT_RECDD;

-- vis.inpatient_episode_detail
ALTER TABLE RHN_VIS_INP_EPISODE_DETAIL RENAME COLUMN CD_ADMISSION_TYPE TO CD_ADM_TYPE;
ALTER TABLE RHN_VIS_INP_EPISODE_DETAIL RENAME COLUMN CD_ADMISSION_SRC TO CD_ADM_SRC;
ALTER TABLE RHN_VIS_INP_EPISODE_DETAIL RENAME COLUMN ID_SVC_LOC_ADMISSION TO ID_SVC_LOC_ADM;
ALTER TABLE RHN_VIS_INP_EPISODE_DETAIL RENAME COLUMN DES_ADMISSION_REASON TO DES_ADM_REASON;
ALTER TABLE RHN_VIS_INP_EPISODE_DETAIL RENAME COLUMN CD_DISCHARGE_DISPOSITION TO CD_DISCH_DISPOS;
ALTER TABLE RHN_VIS_INP_EPISODE_DETAIL RENAME COLUMN ID_SVC_LOC_DISCHARGE TO ID_SVC_LOC_DISCH;
ALTER TABLE RHN_VIS_INP_EPISODE_DETAIL RENAME COLUMN DES_DISCHARGE_NOTE TO DES_DISCH_NOTE;
ALTER TABLE RHN_VIS_INP_EPISODE_DETAIL RENAME COLUMN ID_RESPONSIBLE_NURSE TO ID_RSPNSBL_NURSE;
ALTER TABLE RHN_VIS_INP_EPISODE_DETAIL RENAME COLUMN CD_ADMISSION_METHOD TO CD_ADM_METHOD;
ALTER TABLE RHN_VIS_INP_EPISODE_DETAIL RENAME COLUMN NA_EMERGENCY_CONTACT TO NA_EMERG_CONTACT;
ALTER TABLE RHN_VIS_INP_EPISODE_DETAIL RENAME COLUMN EMERGENCY_CONTACT_RELATIONSHIP TO EMERG_CONTACT_RELSHIP;
ALTER TABLE RHN_VIS_INP_EPISODE_DETAIL RENAME COLUMN EMERGENCY_CONTACT_PHONE TO EMERG_CONTACT_PHONE;
ALTER TABLE RHN_VIS_INP_EPISODE_DETAIL RENAME COLUMN DES_ADMISSION_NOTE TO DES_ADM_NOTE;

-- vis.inpatient_event
ALTER TABLE RHN_VIS_INP_EVT RENAME COLUMN DT_OCCURRED TO DT_OCCRD;

-- sup.inpatient_med_consumption
ALTER TABLE RHN_SUP_INP_MED_CONSUME RENAME COLUMN SD_CONSUMER_TYPE TO SD_CNSMR_TYPE;
ALTER TABLE RHN_SUP_INP_MED_CONSUME RENAME COLUMN QTY_CONSUMED TO QTY_CNSMD;
ALTER TABLE RHN_SUP_INP_MED_CONSUME RENAME COLUMN QTY_CONSUMED_BASE TO QTY_CNSMD_BASE;
ALTER TABLE RHN_SUP_INP_MED_CONSUME RENAME COLUMN DT_CONSUMED TO DT_CNSMD;
ALTER TABLE RHN_SUP_INP_MED_CONSUME RENAME COLUMN ID_USER_CONSUMED TO ID_USER_CNSMD;

-- sup.inpatient_med_supply_batch
ALTER TABLE RHN_SUP_INP_MED_SUPPLY_BATCH RENAME COLUMN DT_SUBMITTED TO DT_SUBMTD;
ALTER TABLE RHN_SUP_INP_MED_SUPPLY_BATCH RENAME COLUMN ID_USER_SUBMITTED TO ID_USER_SUBMTD;
ALTER TABLE RHN_SUP_INP_MED_SUPPLY_BATCH RENAME COLUMN DT_CANCELLED TO DT_CNCLD;
ALTER TABLE RHN_SUP_INP_MED_SUPPLY_BATCH RENAME COLUMN ID_USER_CANCELLED TO ID_USER_CNCLD;

-- sup.inpatient_med_supply_gen_run
ALTER TABLE RHN_SUP_INP_MED_SUPPLY_GEN_RUN RENAME COLUMN DA_BUSINESS TO DA_BIZ;
ALTER TABLE RHN_SUP_INP_MED_SUPPLY_GEN_RUN RENAME COLUMN DT_COMPLETED TO DT_CMPLD;

-- sup.inpatient_med_supply_line
ALTER TABLE RHN_SUP_INP_MED_SUPPLY_LINE RENAME COLUMN QTY_REQUESTED TO QTY_REQD;
ALTER TABLE RHN_SUP_INP_MED_SUPPLY_LINE RENAME COLUMN CD_QUANTITY_UNIT TO CD_QTY_UNIT;
ALTER TABLE RHN_SUP_INP_MED_SUPPLY_LINE RENAME COLUMN QTY_REQUESTED_BASE TO QTY_REQD_BASE;
ALTER TABLE RHN_SUP_INP_MED_SUPPLY_LINE RENAME COLUMN QTY_OCCURRENCE TO QTY_OCC;
ALTER TABLE RHN_SUP_INP_MED_SUPPLY_LINE RENAME COLUMN DT_SUBMITTED TO DT_SUBMTD;
ALTER TABLE RHN_SUP_INP_MED_SUPPLY_LINE RENAME COLUMN ID_USER_SUBMITTED TO ID_USER_SUBMTD;
ALTER TABLE RHN_SUP_INP_MED_SUPPLY_LINE RENAME COLUMN DT_CANCELLED TO DT_CNCLD;
ALTER TABLE RHN_SUP_INP_MED_SUPPLY_LINE RENAME COLUMN ID_USER_CANCELLED TO ID_USER_CNCLD;

-- sup.inpatient_med_supply_task
ALTER TABLE RHN_SUP_INP_MED_SUPPLY_TASK RENAME COLUMN DT_SCHEDULED TO DT_SCHEDD;
ALTER TABLE RHN_SUP_INP_MED_SUPPLY_TASK RENAME COLUMN QTY_REQUIRED TO QTY_RQD;
ALTER TABLE RHN_SUP_INP_MED_SUPPLY_TASK RENAME COLUMN CD_QUANTITY_UNIT TO CD_QTY_UNIT;
ALTER TABLE RHN_SUP_INP_MED_SUPPLY_TASK RENAME COLUMN QTY_REQUIRED_BASE TO QTY_RQD_BASE;
ALTER TABLE RHN_SUP_INP_MED_SUPPLY_TASK RENAME COLUMN DT_CANCELLED TO DT_CNCLD;
ALTER TABLE RHN_SUP_INP_MED_SUPPLY_TASK RENAME COLUMN ID_USER_CANCELLED TO ID_USER_CNCLD;

-- vis.inpatient_nursing_record
ALTER TABLE RHN_VIS_INP_NURS_RECORD RENAME COLUMN DT_OCCURRED TO DT_OCCRD;
ALTER TABLE RHN_VIS_INP_NURS_RECORD RENAME COLUMN ID_RECORDED_BY_SUBJECT TO ID_RECDD_BY_SUBJECT;
ALTER TABLE RHN_VIS_INP_NURS_RECORD RENAME COLUMN ID_RECORDED_BY_PRACT TO ID_RECDD_BY_PRACT;
ALTER TABLE RHN_VIS_INP_NURS_RECORD RENAME COLUMN NA_RECORDER TO NA_RECDR;
ALTER TABLE RHN_VIS_INP_NURS_RECORD RENAME COLUMN DT_RECORDED TO DT_RECDD;
ALTER TABLE RHN_VIS_INP_NURS_RECORD RENAME COLUMN CONTENT_DIGEST_ALGORITHM TO CONTENT_DIGEST_ALGO;
ALTER TABLE RHN_VIS_INP_NURS_RECORD RENAME COLUMN ID_CRYPTO_EVID_INTEGRITY TO ID_CRYPTO_EVID_INTGR;
ALTER TABLE RHN_VIS_INP_NURS_RECORD RENAME COLUMN JSON_ASSESSMENT TO JSON_ASSMT;

-- vis.inpatient_observation_group
ALTER TABLE RHN_VIS_INP_OBS_GRP RENAME COLUMN DT_MEASURED TO DT_MEASD;
ALTER TABLE RHN_VIS_INP_OBS_GRP RENAME COLUMN ID_USER_RECORDED TO ID_USER_RECDD;
ALTER TABLE RHN_VIS_INP_OBS_GRP RENAME COLUMN DT_RECORDED TO DT_RECDD;

-- vis.inpatient_observation
ALTER TABLE RHN_VIS_INP_OBS RENAME COLUMN DT_OBSERVED TO DT_OBSD;

-- ex.inpatient_order_event
ALTER TABLE RHN_EX_INP_ORDER_EVT RENAME COLUMN DT_OCCURRED TO DT_OCCRD;

-- ex.inpatient_order_task
ALTER TABLE RHN_EX_INP_ORDER_TASK RENAME COLUMN CD_OCCURRENCE_NO TO CD_OCC_NO;
ALTER TABLE RHN_EX_INP_ORDER_TASK RENAME COLUMN DT_SCHEDULED TO DT_SCHEDD;
ALTER TABLE RHN_EX_INP_ORDER_TASK RENAME COLUMN DT_COMPLETED TO DT_CMPLD;
ALTER TABLE RHN_EX_INP_ORDER_TASK RENAME COLUMN ID_USER_COMPLETED TO ID_USER_CMPLD;
ALTER TABLE RHN_EX_INP_ORDER_TASK RENAME COLUMN DT_CANCELLED TO DT_CNCLD;

-- ex.inpatient_order_workflow
ALTER TABLE RHN_EX_INP_ORDER_WF RENAME COLUMN SD_DURATION_TYPE TO SD_DUR_TYPE;
ALTER TABLE RHN_EX_INP_ORDER_WF RENAME COLUMN ID_AUTHORED_PRACT TO ID_AUTHRD_PRACT;
ALTER TABLE RHN_EX_INP_ORDER_WF RENAME COLUMN ID_USER_VERIFIED TO ID_USER_VRFD;
ALTER TABLE RHN_EX_INP_ORDER_WF RENAME COLUMN DT_VERIFIED TO DT_VRFD;
ALTER TABLE RHN_EX_INP_ORDER_WF RENAME COLUMN MEDICATION_QUANTITY_UNIT TO MED_QTY_UNIT;
ALTER TABLE RHN_EX_INP_ORDER_WF RENAME COLUMN MEDICATION_BASE_UNIT TO MED_BASE_UNIT;

-- vis.inpatient_shift_handoff_item
ALTER TABLE RHN_VIS_INP_SHIFT_HANDOFF_ITEM RENAME COLUMN DES_SITUATION TO DES_SITUAT;

-- vis.inpatient_shift_handoff
ALTER TABLE RHN_VIS_INP_SHIFT_HANDOFF RENAME COLUMN CONTENT_DIGEST_ALGORITHM TO CONTENT_DIGEST_ALGO;
ALTER TABLE RHN_VIS_INP_SHIFT_HANDOFF RENAME COLUMN ID_CRYPTO_EVID_INTEGRITY TO ID_CRYPTO_EVID_INTGR;

-- ins.insurance_claim_line
ALTER TABLE RHN_INS_CLAIM_LINE RENAME COLUMN AMT_APPROVED TO AMT_APRVD;
ALTER TABLE RHN_INS_CLAIM_LINE RENAME COLUMN CD_REJECTION TO CD_REJCTN;

-- ins.insurance_claim_response
ALTER TABLE RHN_INS_CLAIM_RESP RENAME COLUMN SD_OPERATION TO SD_OPER;
ALTER TABLE RHN_INS_CLAIM_RESP RENAME COLUMN AMT_PERSONAL_ACCT TO AMT_PERS_ACCT;
ALTER TABLE RHN_INS_CLAIM_RESP RENAME COLUMN DT_RESPONDED TO DT_RSPND;

-- ins.insurance_claim
ALTER TABLE RHN_INS_CLAIM RENAME COLUMN SD_CURRENT_OPERATION TO SD_CURRENT_OPER;
ALTER TABLE RHN_INS_CLAIM RENAME COLUMN AMT_PERSONAL_ACCT TO AMT_PERS_ACCT;
ALTER TABLE RHN_INS_CLAIM RENAME COLUMN CD_CURRENCY TO CD_CCY;
ALTER TABLE RHN_INS_CLAIM RENAME COLUMN ID_CORRELATION TO ID_CORR;
ALTER TABLE RHN_INS_CLAIM RENAME COLUMN DES_REVERSAL_REASON TO DES_RVRSL_REASON;
ALTER TABLE RHN_INS_CLAIM RENAME COLUMN DT_REVERSED TO DT_RVRSD;

-- sup.inventory_balance
ALTER TABLE RHN_SUP_INV_BAL RENAME COLUMN QTY_RESERVED TO QTY_RESVD;
ALTER TABLE RHN_SUP_INV_BAL RENAME COLUMN QTY_AVAILABLE TO QTY_AVAIL;
ALTER TABLE RHN_SUP_INV_BAL RENAME COLUMN DT_PROJECTED TO DT_PROJD;

-- sup.inventory_document_event
ALTER TABLE RHN_SUP_INV_DOC_EVT RENAME COLUMN ID_CORRELATION TO ID_CORR;
ALTER TABLE RHN_SUP_INV_DOC_EVT RENAME COLUMN DT_OCCURRED TO DT_OCCRD;
ALTER TABLE RHN_SUP_INV_DOC_EVT RENAME COLUMN ID_USER_OCCURRED TO ID_USER_OCCRD;

-- sup.inventory_open_package
ALTER TABLE RHN_SUP_INV_OPEN_PKG RENAME COLUMN QTY_REMAINING_BASE TO QTY_REM_BASE;

-- sup.inventory_period_balance_snapshot
ALTER TABLE RHN_SUP_INV_PERIOD_BAL_SNAP RENAME COLUMN QTY_MOVEMENT TO QTY_MVMT;
ALTER TABLE RHN_SUP_INV_PERIOD_BAL_SNAP RENAME COLUMN QTY_DIFFERENCE TO QTY_DIFF;

-- sup.inventory_period_balance_value
ALTER TABLE RHN_SUP_INV_PERIOD_BAL_VAL RENAME COLUMN CD_CURRENCY TO CD_CCY;
ALTER TABLE RHN_SUP_INV_PERIOD_BAL_VAL RENAME COLUMN AMT_MOVEMENT TO AMT_MVMT;
ALTER TABLE RHN_SUP_INV_PERIOD_BAL_VAL RENAME COLUMN AMT_ROUNDING_ADJ TO AMT_RND_ADJ;
ALTER TABLE RHN_SUP_INV_PERIOD_BAL_VAL RENAME COLUMN AMT_VAL_DIFFERENCE TO AMT_VAL_DIFF;

-- sup.inventory_period_close_run
ALTER TABLE RHN_SUP_INV_PERIOD_CLOSE_RUN RENAME COLUMN ID_INV_PERIOD_PREVIOUS TO ID_INV_PERIOD_PREV;
ALTER TABLE RHN_SUP_INV_PERIOD_CLOSE_RUN RENAME COLUMN QTY_DIMENSION TO QTY_DIM;
ALTER TABLE RHN_SUP_INV_PERIOD_CLOSE_RUN RENAME COLUMN QTY_DIFFERENCE TO QTY_DIFF;
ALTER TABLE RHN_SUP_INV_PERIOD_CLOSE_RUN RENAME COLUMN DT_VALIDATED TO DT_VLDTD;
ALTER TABLE RHN_SUP_INV_PERIOD_CLOSE_RUN RENAME COLUMN ID_USER_VALIDATED TO ID_USER_VLDTD;
ALTER TABLE RHN_SUP_INV_PERIOD_CLOSE_RUN RENAME COLUMN DT_COMPLETED TO DT_CMPLD;

-- sup.inventory_period_close_total
ALTER TABLE RHN_SUP_INV_PERIOD_CLOSE_TOTAL RENAME COLUMN CD_CURRENCY TO CD_CCY;
ALTER TABLE RHN_SUP_INV_PERIOD_CLOSE_TOTAL RENAME COLUMN AMT_MOVEMENT TO AMT_MVMT;
ALTER TABLE RHN_SUP_INV_PERIOD_CLOSE_TOTAL RENAME COLUMN AMT_ROUNDING_ADJ TO AMT_RND_ADJ;
ALTER TABLE RHN_SUP_INV_PERIOD_CLOSE_TOTAL RENAME COLUMN AMT_VAL_DIFFERENCE TO AMT_VAL_DIFF;

-- sup.inventory_period
ALTER TABLE RHN_SUP_INV_PERIOD RENAME COLUMN ID_INV_PERIOD_PREVIOUS TO ID_INV_PERIOD_PREV;

-- sup.inventory_price_adjustment_detail
ALTER TABLE RHN_SUP_INV_PRICE_ADJ_DETAIL RENAME COLUMN AMT_ROUNDING TO AMT_RND;

-- sup.inventory_price_adjustment_line
ALTER TABLE RHN_SUP_INV_PRICE_ADJ_LINE RENAME COLUMN AMT_ROUNDING TO AMT_RND;

-- sup.inventory_price_adjustment
ALTER TABLE RHN_SUP_INV_PRICE_ADJ RENAME COLUMN ID_INV_PRICE_ADJ_REVERSAL_OF TO ID_INV_PRICE_ADJ_RVRSL_OF;
ALTER TABLE RHN_SUP_INV_PRICE_ADJ RENAME COLUMN DA_BUSINESS TO DA_BIZ;
ALTER TABLE RHN_SUP_INV_PRICE_ADJ RENAME COLUMN CD_CURRENCY TO CD_CCY;
ALTER TABLE RHN_SUP_INV_PRICE_ADJ RENAME COLUMN DT_SUBMITTED TO DT_SUBMTD;
ALTER TABLE RHN_SUP_INV_PRICE_ADJ RENAME COLUMN ID_USER_SUBMITTED TO ID_USER_SUBMTD;
ALTER TABLE RHN_SUP_INV_PRICE_ADJ RENAME COLUMN DT_APPROVED TO DT_APRVD;
ALTER TABLE RHN_SUP_INV_PRICE_ADJ RENAME COLUMN ID_USER_APPROVED TO ID_USER_APRVD;
ALTER TABLE RHN_SUP_INV_PRICE_ADJ RENAME COLUMN DT_REVERSED TO DT_RVRSD;
ALTER TABLE RHN_SUP_INV_PRICE_ADJ RENAME COLUMN ID_USER_REVERSED TO ID_USER_RVRSD;
ALTER TABLE RHN_SUP_INV_PRICE_ADJ RENAME COLUMN DT_CANCELLED TO DT_CNCLD;
ALTER TABLE RHN_SUP_INV_PRICE_ADJ RENAME COLUMN ID_USER_CANCELLED TO ID_USER_CNCLD;

-- sup.inventory_reconciliation_line
ALTER TABLE RHN_SUP_INV_RECON_LINE RENAME COLUMN QTY_EXPECTED TO QTY_EXPCTD;
ALTER TABLE RHN_SUP_INV_RECON_LINE RENAME COLUMN QTY_DIFFERENCE TO QTY_DIFF;
ALTER TABLE RHN_SUP_INV_RECON_LINE RENAME COLUMN SD_SEVERITY TO SD_SEV;
ALTER TABLE RHN_SUP_INV_RECON_LINE RENAME COLUMN CD_CURRENCY TO CD_CCY;
ALTER TABLE RHN_SUP_INV_RECON_LINE RENAME COLUMN AMT_EXPECTED TO AMT_EXPCTD;
ALTER TABLE RHN_SUP_INV_RECON_LINE RENAME COLUMN AMT_DIFFERENCE TO AMT_DIFF;

-- sup.inventory_reconciliation_run
ALTER TABLE RHN_SUP_INV_RECON_RUN RENAME COLUMN DA_BUSINESS TO DA_BIZ;
ALTER TABLE RHN_SUP_INV_RECON_RUN RENAME COLUMN DT_COMPLETED TO DT_CMPLD;
ALTER TABLE RHN_SUP_INV_RECON_RUN RENAME COLUMN QTY_DIMENSION TO QTY_DIM;

-- sup.inventory_reservation
ALTER TABLE RHN_SUP_INV_RESV RENAME COLUMN QTY_RESERVED TO QTY_RESVD;
ALTER TABLE RHN_SUP_INV_RESV RENAME COLUMN QTY_CONSUMED TO QTY_CNSMD;
ALTER TABLE RHN_SUP_INV_RESV RENAME COLUMN DT_CONSUMED TO DT_CNSMD;
ALTER TABLE RHN_SUP_INV_RESV RENAME COLUMN ID_USER_CONSUMED TO ID_USER_CNSMD;
ALTER TABLE RHN_SUP_INV_RESV RENAME COLUMN DT_RELEASED TO DT_RLSD;
ALTER TABLE RHN_SUP_INV_RESV RENAME COLUMN ID_USER_RELEASED TO ID_USER_RLSD;

-- sup.inventory_split_event
ALTER TABLE RHN_SUP_INV_SPLIT_EVT RENAME COLUMN DT_OCCURRED TO DT_OCCRD;
ALTER TABLE RHN_SUP_INV_SPLIT_EVT RENAME COLUMN ID_USER_OCCURRED TO ID_USER_OCCRD;

-- sup.inventory_trace_code
ALTER TABLE RHN_SUP_INV_TRACE_CODE RENAME COLUMN CD_NORMALIZED TO CD_NORM;
ALTER TABLE RHN_SUP_INV_TRACE_CODE RENAME COLUMN DT_RECEIVED TO DT_RECVD;
ALTER TABLE RHN_SUP_INV_TRACE_CODE RENAME COLUMN QTY_REMAINING_BASE TO QTY_REM_BASE;

-- sup.inventory_trace_event
ALTER TABLE RHN_SUP_INV_TRACE_EVT RENAME COLUMN DT_OCCURRED TO DT_OCCRD;
ALTER TABLE RHN_SUP_INV_TRACE_EVT RENAME COLUMN ID_USER_OCCURRED TO ID_USER_OCCRD;

-- sup.inventory_transaction_line
ALTER TABLE RHN_SUP_INV_TXN_LINE RENAME COLUMN QTY_OPERATION TO QTY_OPER;
ALTER TABLE RHN_SUP_INV_TXN_LINE RENAME COLUMN CD_OPERATION_UNIT TO CD_OPER_UNIT;
ALTER TABLE RHN_SUP_INV_TXN_LINE RENAME COLUMN BASE_QUANTITY_FACTOR TO BASE_QTY_FACTOR;

-- sup.inventory_transaction
ALTER TABLE RHN_SUP_INV_TXN RENAME COLUMN ID_INV_TXN_REVERSES TO ID_INV_TXN_RVRS;
ALTER TABLE RHN_SUP_INV_TXN RENAME COLUMN DT_OCCURRED TO DT_OCCRD;

-- sup.inventory_valuation_entry
ALTER TABLE RHN_SUP_INV_VALUAT_ENTRY RENAME COLUMN ID_INV_VALUAT_ENTRY_REVERSES TO ID_INV_VALUAT_ENTRY_RVRS;
ALTER TABLE RHN_SUP_INV_VALUAT_ENTRY RENAME COLUMN CD_CURRENCY TO CD_CCY;
ALTER TABLE RHN_SUP_INV_VALUAT_ENTRY RENAME COLUMN DT_OCCURRED TO DT_OCCRD;

-- bil.invoice_category_summary
ALTER TABLE RHN_BIL_INVOICE_CAT_SUM RENAME COLUMN AMT_CATEGORY TO AMT_CAT;

-- bil.invoice
ALTER TABLE RHN_BIL_INVOICE RENAME COLUMN CD_CURRENCY TO CD_CCY;
ALTER TABLE RHN_BIL_INVOICE RENAME COLUMN AMT_DISCOUNT TO AMT_DISC;
ALTER TABLE RHN_BIL_INVOICE RENAME COLUMN DT_CANCELLED TO DT_CNCLD;
ALTER TABLE RHN_BIL_INVOICE RENAME COLUMN DES_CANCELLATION_REASON TO DES_CNCLN_REASON;

-- bd.item_alias
ALTER TABLE RHN_BD_ITEM_ALIAS RENAME COLUMN CD_MNEMONIC TO CD_MNEM;

-- bd.item_attribute_definition
ALTER TABLE RHN_BD_ITEM_ATTR_DEF RENAME COLUMN SD_CARDINALITY TO SD_CARDNL;
ALTER TABLE RHN_BD_ITEM_ATTR_DEF RENAME COLUMN SD_VARIABILITY TO SD_VARBLTY;
ALTER TABLE RHN_BD_ITEM_ATTR_DEF RENAME COLUMN PROJECTION_FIELD TO PROJ_FIELD;
ALTER TABLE RHN_BD_ITEM_ATTR_DEF RENAME COLUMN ID_VALIDATION_RULE TO ID_VLDN_RULE;
ALTER TABLE RHN_BD_ITEM_ATTR_DEF RENAME COLUMN SENSITIVITY TO SENS;

-- bd.item_group_member
ALTER TABLE RHN_BD_ITEM_GRP_MEMBER RENAME COLUMN FG_REQUIRED_MEMBER TO FG_RQD_MEMBER;
ALTER TABLE RHN_BD_ITEM_GRP_MEMBER RENAME COLUMN DES_MEMBER_DESCRIPTION TO DES_MEMBER_DESCR;

-- bd.item_term_mapping
ALTER TABLE RHN_BD_ITEM_TERM_MAP RENAME COLUMN SD_EQUIVALENCE TO SD_EQUIV;
ALTER TABLE RHN_BD_ITEM_TERM_MAP RENAME COLUMN DES_LIMITATION TO DES_LIMIT;
ALTER TABLE RHN_BD_ITEM_TERM_MAP RENAME COLUMN ID_ITEM_TERM_MAP_REPLACES TO ID_ITEM_TERM_MAP_RPLCS;

-- bd.item_type_attribute
ALTER TABLE RHN_BD_ITEM_TYPE_ATTR RENAME COLUMN FG_REQUIRED_VAL TO FG_RQD_VAL;
ALTER TABLE RHN_BD_ITEM_TYPE_ATTR RENAME COLUMN JSON_REQUIRED_COND TO JSON_RQD_COND;
ALTER TABLE RHN_BD_ITEM_TYPE_ATTR RENAME COLUMN FG_SEARCHABLE TO FG_SRCHBL;

-- ex.laboratory_service_specimen
ALTER TABLE RHN_EX_LAB_SVC_SPEC RENAME COLUMN ID_DICT_ITEM_CONTAINER TO ID_DICT_ITEM_CONTNR;
ALTER TABLE RHN_EX_LAB_SVC_SPEC RENAME COLUMN MINIMUM_QUANTITY_UNIT TO MINIMUM_QTY_UNIT;
ALTER TABLE RHN_EX_LAB_SVC_SPEC RENAME COLUMN FG_REQUIRED_SPEC TO FG_RQD_SPEC;
ALTER TABLE RHN_EX_LAB_SVC_SPEC RENAME COLUMN DES_COLLECTION_DESCRIPTION TO DES_COLL_DESCR;
ALTER TABLE RHN_EX_LAB_SVC_SPEC RENAME COLUMN QTY_INCLUDED_TUBE TO QTY_INCLD_TUBE;

-- bd.laboratory_service
ALTER TABLE RHN_BD_LAB_SVC RENAME COLUMN QTY_REPORT_DURATION TO QTY_REPORT_DUR;
ALTER TABLE RHN_BD_LAB_SVC RENAME COLUMN REPORT_DURATION_UNIT TO REPORT_DUR_UNIT;
ALTER TABLE RHN_BD_LAB_SVC RENAME COLUMN FG_FASTING_REQUIRED TO FG_FASTING_RQD;
ALTER TABLE RHN_BD_LAB_SVC RENAME COLUMN DES_COLLECTION_DESCRIPTION TO DES_COLL_DESCR;

-- bil.ledger_entry
ALTER TABLE RHN_BIL_LEDGER_ENTRY RENAME COLUMN SD_DIRECTION TO SD_DIR;
ALTER TABLE RHN_BIL_LEDGER_ENTRY RENAME COLUMN CD_CURRENCY TO CD_CCY;
ALTER TABLE RHN_BIL_LEDGER_ENTRY RENAME COLUMN ID_LEDGER_ENTRY_REVERSES TO ID_LEDGER_ENTRY_RVRS;
ALTER TABLE RHN_BIL_LEDGER_ENTRY RENAME COLUMN DT_OCCURRED TO DT_OCCRD;
ALTER TABLE RHN_BIL_LEDGER_ENTRY RENAME COLUMN DT_RECORDED TO DT_RECDD;
ALTER TABLE RHN_BIL_LEDGER_ENTRY RENAME COLUMN ID_USER_RECORDED TO ID_USER_RECDD;

-- bd.manufacturer
ALTER TABLE RHN_BD_MFR RENAME COLUMN PRODUCTION_PLACE TO PROD_PLACE;

-- bd.master_data_import_batch
ALTER TABLE RHN_BD_IMPORT_BATCH RENAME COLUMN QTY_IMPORTED_ROW TO QTY_IMPRTD_ROW;

-- bd.master_data_import_row
ALTER TABLE RHN_BD_IMPORT_ROW RENAME COLUMN JSON_NORMALIZED TO JSON_NORM;

-- sup.medication_dispense_line
ALTER TABLE RHN_SUP_MED_DISP_LINE RENAME COLUMN ID_MED_DISP_LINE_ORIGINAL TO ID_MED_DISP_LINE_ORIG;
ALTER TABLE RHN_SUP_MED_DISP_LINE RENAME COLUMN QTY_DISPENSED TO QTY_DSPNSD;
ALTER TABLE RHN_SUP_MED_DISP_LINE RENAME COLUMN BASE_QUANTITY_FACTOR TO BASE_QTY_FACTOR;

-- sup.medication_dispense
ALTER TABLE RHN_SUP_MED_DISP RENAME COLUMN ID_MED_DISP_ORIGINAL TO ID_MED_DISP_ORIG;
ALTER TABLE RHN_SUP_MED_DISP RENAME COLUMN DT_OCCURRED TO DT_OCCRD;
ALTER TABLE RHN_SUP_MED_DISP RENAME COLUMN ID_DISPENSER_PRACT TO ID_DSPNSR_PRACT;
ALTER TABLE RHN_SUP_MED_DISP RENAME COLUMN ID_DISPENSER_USER TO ID_DSPNSR_USER;
ALTER TABLE RHN_SUP_MED_DISP RENAME COLUMN ID_DISPENSER_ASSIGN TO ID_DSPNSR_ASSIGN;
ALTER TABLE RHN_SUP_MED_DISP RENAME COLUMN QTY_OPERATION TO QTY_OPER;
ALTER TABLE RHN_SUP_MED_DISP RENAME COLUMN CD_OPERATION_UNIT TO CD_OPER_UNIT;

-- bd.medication_herbal
ALTER TABLE RHN_BD_MED_HERBAL RENAME COLUMN ID_DICT_ITEM_MEDICINAL_PART TO ID_DICT_ITEM_MEDCNL_PART;
ALTER TABLE RHN_BD_MED_HERBAL RENAME COLUMN SD_PROCESSING_METHOD TO SD_PROCSG_METHOD;
ALTER TABLE RHN_BD_MED_HERBAL RENAME COLUMN DES_FLAVOR_DESCRIPTION TO DES_FLAVOR_DESCR;
ALTER TABLE RHN_BD_MED_HERBAL RENAME COLUMN DES_MERIDIAN_DESCRIPTION TO DES_MERID_DESCR;
ALTER TABLE RHN_BD_MED_HERBAL RENAME COLUMN DES_DECOCTION_DESCRIPTION TO DES_DECOCT_DESCR;
ALTER TABLE RHN_BD_MED_HERBAL RENAME COLUMN FG_SEPARATE_DECOCTION TO FG_SEPR_DECOCT;

-- bd.medication_product
ALTER TABLE RHN_BD_MED_PRODUCT RENAME COLUMN CD_APPROVAL TO CD_APRVL;
ALTER TABLE RHN_BD_MED_PRODUCT RENAME COLUMN DA_APPROVAL_FROM TO DA_APRVL_FROM;
ALTER TABLE RHN_BD_MED_PRODUCT RENAME COLUMN DA_APPROVAL_TO TO DA_APRVL_TO;
ALTER TABLE RHN_BD_MED_PRODUCT RENAME COLUMN PRODUCTION_PLACE TO PROD_PLACE;
ALTER TABLE RHN_BD_MED_PRODUCT RENAME COLUMN FG_TRACE_SPLIT_REQUIRED TO FG_TRACE_SPLIT_RQD;
ALTER TABLE RHN_BD_MED_PRODUCT RENAME COLUMN DES_INDICATION TO DES_INDIC;
ALTER TABLE RHN_BD_MED_PRODUCT RENAME COLUMN DES_INSTRUCTION TO DES_INSTR;

-- ex.medication_request
ALTER TABLE RHN_EX_MED_REQ RENAME COLUMN QTY_DURATION_VAL TO QTY_DUR_VAL;
ALTER TABLE RHN_EX_MED_REQ RENAME COLUMN DURATION_UNIT TO DUR_UNIT;
ALTER TABLE RHN_EX_MED_REQ RENAME COLUMN PACKAGE_FACTOR_SNAPSHOT TO PACKAGE_FACTOR_SNAP;
ALTER TABLE RHN_EX_MED_REQ RENAME COLUMN PACKAGE_SPEC_SNAPSHOT TO PACKAGE_SPEC_SNAP;
ALTER TABLE RHN_EX_MED_REQ RENAME COLUMN PRICE_QUANTITY_SNAP TO PRICE_QTY_SNAP;
ALTER TABLE RHN_EX_MED_REQ RENAME COLUMN FG_SUBSTITUTION TO FG_SUBSTN;
ALTER TABLE RHN_EX_MED_REQ RENAME COLUMN FG_SELF_PROVIDED TO FG_SELF_PRVDD;
ALTER TABLE RHN_EX_MED_REQ RENAME COLUMN DES_MED_INSTRUCTION TO DES_MED_INSTR;
ALTER TABLE RHN_EX_MED_REQ RENAME COLUMN DOSE_FORM_SNAPSHOT TO DOSE_FORM_SNAP;
ALTER TABLE RHN_EX_MED_REQ RENAME COLUMN PREPARATION_SPEC_SNAPSHOT TO PREP_SPEC_SNAP;
ALTER TABLE RHN_EX_MED_REQ RENAME COLUMN PREPARATION_UNIT_SNAPSHOT TO PREP_UNIT_SNAP;
ALTER TABLE RHN_EX_MED_REQ RENAME COLUMN FG_SKIN_TEST_REQUIRED_SNAP TO FG_SKIN_TEST_RQD_SNAP;
ALTER TABLE RHN_EX_MED_REQ RENAME COLUMN FG_ANTIMICROBIAL_SNAP TO FG_ANTIMIC_SNAP;
ALTER TABLE RHN_EX_MED_REQ RENAME COLUMN SD_ANTIMICROBIAL_LEVEL_SNAP TO SD_ANTIMIC_LEVEL_SNAP;
ALTER TABLE RHN_EX_MED_REQ RENAME COLUMN MEDICATION_SNAPSHOT TO MED_SNAP;
ALTER TABLE RHN_EX_MED_REQ RENAME COLUMN FREQUENCY_RULE_SNAPSHOT TO FREQ_RULE_SNAP;
ALTER TABLE RHN_EX_MED_REQ RENAME COLUMN SD_ROUTE_RESOLUTION_STATUS TO SD_ROUTE_RSLN_STATUS;
ALTER TABLE RHN_EX_MED_REQ RENAME COLUMN ID_EXEMPT_EVIDENCE_EVENT TO ID_EXEMPT_EVID_EVENT;

-- bd.medication_vaccine
ALTER TABLE RHN_BD_MED_VACCINE RENAME COLUMN SD_RECOMMENDED_ROUTE TO SD_RECMD_ROUTE;
ALTER TABLE RHN_BD_MED_VACCINE RENAME COLUMN FG_COLD_CHAIN_REQUIRED TO FG_COLD_CHAIN_RQD;
ALTER TABLE RHN_BD_MED_VACCINE RENAME COLUMN QTY_MIN_TEMPERATURE TO QTY_MIN_TEMP;
ALTER TABLE RHN_BD_MED_VACCINE RENAME COLUMN QTY_MAX_TEMPERATURE TO QTY_MAX_TEMP;
ALTER TABLE RHN_BD_MED_VACCINE RENAME COLUMN IMMUNIZATION_SCHEDULE TO IMMUN_SCHED;

-- bd.medication_western
ALTER TABLE RHN_BD_MED_WESTERN RENAME COLUMN ACTIVE_INGREDIENT TO ACTIVE_INGR;
ALTER TABLE RHN_BD_MED_WESTERN RENAME COLUMN SD_THERAPEUTIC_CLASS TO SD_THERAP_CLASS;
ALTER TABLE RHN_BD_MED_WESTERN RENAME COLUMN FG_BIOLOGIC TO FG_BIOL;
ALTER TABLE RHN_BD_MED_WESTERN RENAME COLUMN FG_BIOSIMILAR TO FG_BIOSIM;

-- bd.medication
ALTER TABLE RHN_BD_MED RENAME COLUMN PREPARATION_SPEC TO PREP_SPEC;
ALTER TABLE RHN_BD_MED RENAME COLUMN PREPARATION_UNIT TO PREP_UNIT;
ALTER TABLE RHN_BD_MED RENAME COLUMN QTY_STRENGTH_VAL TO QTY_STRNTH_VAL;
ALTER TABLE RHN_BD_MED RENAME COLUMN STRENGTH_UNIT TO STRNTH_UNIT;
ALTER TABLE RHN_BD_MED RENAME COLUMN FG_PRESCRIPTION_DRUG TO FG_RX_DRUG;
ALTER TABLE RHN_BD_MED RENAME COLUMN FG_ESSENTIAL_DRUG TO FG_ESSNTL_DRUG;
ALTER TABLE RHN_BD_MED RENAME COLUMN FG_ANTIMICROBIAL TO FG_ANTIMIC;
ALTER TABLE RHN_BD_MED RENAME COLUMN SD_ANTIMICROBIAL_LEVEL TO SD_ANTIMIC_LEVEL;
ALTER TABLE RHN_BD_MED RENAME COLUMN FG_SKIN_TEST_REQUIRED TO FG_SKIN_TEST_RQD;
ALTER TABLE RHN_BD_MED RENAME COLUMN DEFAULT_FREQUENCY TO DEFAULT_FREQ;
ALTER TABLE RHN_BD_MED RENAME COLUMN FG_ANTIMICROBIAL_OUTPATIENT TO FG_ANTIMIC_OP;
ALTER TABLE RHN_BD_MED RENAME COLUMN FG_ANTIMICROBIAL_CONSULT TO FG_ANTIMIC_CONSULT;
ALTER TABLE RHN_BD_MED RENAME COLUMN FG_ANTIMICROBIAL_EMERGENCY TO FG_ANTIMIC_EMERG;
ALTER TABLE RHN_BD_MED RENAME COLUMN QTY_ANTIMICROBIAL_MAX_DAYS TO QTY_ANTIMIC_MAX_DAYS;
ALTER TABLE RHN_BD_MED RENAME COLUMN SD_SKIN_TEST_SOLUTION_MODE TO SD_SKIN_TEST_SOLN_MODE;
ALTER TABLE RHN_BD_MED RENAME COLUMN DES_SKIN_TEST_INSTRUCTION TO DES_SKIN_TEST_INSTR;

-- vis.observation
ALTER TABLE RHN_VIS_OBS RENAME COLUMN DT_EFFECTIVE TO DT_EFF;
ALTER TABLE RHN_VIS_OBS RENAME COLUMN DT_VAL_DATETIME TO DT_VAL_DTTM;
ALTER TABLE RHN_VIS_OBS RENAME COLUMN REFERENCE_RANGE_LOW TO REF_RANGE_LOW;
ALTER TABLE RHN_VIS_OBS RENAME COLUMN REFERENCE_RANGE_HIGH TO REF_RANGE_HIGH;
ALTER TABLE RHN_VIS_OBS RENAME COLUMN CD_INTERPRETATION TO CD_INTERP;
ALTER TABLE RHN_VIS_OBS RENAME COLUMN CD_PERFORMER TO CD_PRFRMR;
ALTER TABLE RHN_VIS_OBS RENAME COLUMN NA_PERFORMER TO NA_PRFRMR;

-- bd.order_frequency
ALTER TABLE RHN_BD_ORDER_FREQ RENAME COLUMN DEFAULT_EXECUTION_TIMES TO DEFAULT_EXEC_TIMES;
ALTER TABLE RHN_BD_ORDER_FREQ RENAME COLUMN FG_OP_APPLICABLE TO FG_OP_APPL;
ALTER TABLE RHN_BD_ORDER_FREQ RENAME COLUMN FG_INP_APPLICABLE TO FG_INP_APPL;
ALTER TABLE RHN_BD_ORDER_FREQ RENAME COLUMN FG_EMERGENCY_APPLICABLE TO FG_EMERG_APPL;
ALTER TABLE RHN_BD_ORDER_FREQ RENAME COLUMN FG_MED_APPLICABLE TO FG_MED_APPL;
ALTER TABLE RHN_BD_ORDER_FREQ RENAME COLUMN FG_TREAT_APPLICABLE TO FG_TREAT_APPL;
ALTER TABLE RHN_BD_ORDER_FREQ RENAME COLUMN FG_NURS_APPLICABLE TO FG_NURS_APPL;
ALTER TABLE RHN_BD_ORDER_FREQ RENAME COLUMN FG_AUTOMATIC_TASK_GEN TO FG_AUTO_TASK_GEN;

-- bd.order_frequency_config
ALTER TABLE RHN_BD_ORDER_FREQ_CFG RENAME COLUMN EXECUTION_TIMES TO EXEC_TIMES;

-- sys.organization_address
ALTER TABLE RHN_SYS_ORG_ADDR RENAME COLUMN CD_PROVINCE TO CD_PROV;
ALTER TABLE RHN_SYS_ORG_ADDR RENAME COLUMN CD_DISTRICT TO CD_DIST;

-- sys.organization_capability
ALTER TABLE RHN_SYS_ORG_CAP RENAME COLUMN CD_QUALIFICATION_BASIS TO CD_QUALIF_BASIS;

-- bd.organization_catalog_item
ALTER TABLE RHN_BD_ORG_CATALOG_ITEM RENAME COLUMN FG_ORDERABLE TO FG_ORDRBL;
ALTER TABLE RHN_BD_ORG_CATALOG_ITEM RENAME COLUMN FG_EXECUTABLE TO FG_EXECBL;
ALTER TABLE RHN_BD_ORG_CATALOG_ITEM RENAME COLUMN FG_CHARGEABLE TO FG_CHGBL;
ALTER TABLE RHN_BD_ORG_CATALOG_ITEM RENAME COLUMN FG_PURCHASABLE TO FG_PURCHBL;
ALTER TABLE RHN_BD_ORG_CATALOG_ITEM RENAME COLUMN FG_DISPENSABLE TO FG_DISPBL;
ALTER TABLE RHN_BD_ORG_CATALOG_ITEM RENAME COLUMN FG_RETURNABLE TO FG_RETBL;
ALTER TABLE RHN_BD_ORG_CATALOG_ITEM RENAME COLUMN ID_ORG_CATALOG_ITEM_REPLACED TO ID_ORG_CATALOG_ITEM_RPLCD;

-- bd.organization_concept
ALTER TABLE RHN_BD_ORG_CONCEPT RENAME COLUMN FG_SELECTABLE TO FG_SELBL;
ALTER TABLE RHN_BD_ORG_CONCEPT RENAME COLUMN FG_FREQUENT TO FG_FREQNT;

-- sys.organization_identifier
ALTER TABLE RHN_SYS_ORG_IDENT RENAME COLUMN DT_VERIFIED TO DT_VRFD;
ALTER TABLE RHN_SYS_ORG_IDENT RENAME COLUMN ID_USER_VERIFIED TO ID_USER_VRFD;

-- sys.organization_responsibility
ALTER TABLE RHN_SYS_ORG_RESP RENAME COLUMN NA_EXT_RESPONSIBLE TO NA_EXT_RSPNSBL;

-- sys.organization
ALTER TABLE RHN_SYS_ORG RENAME COLUMN SD_ORG_PROPERTY TO SD_ORG_PROP;
ALTER TABLE RHN_SYS_ORG RENAME COLUMN CD_TIMEZONE TO CD_TZ;

-- int.outbox_event
ALTER TABLE RHN_INT_OUTBOX_EVT RENAME COLUMN SD_AGGREGATE_TYPE TO SD_AGG_TYPE;
ALTER TABLE RHN_INT_OUTBOX_EVT RENAME COLUMN ID_AGGREGATE TO ID_AGG;
ALTER TABLE RHN_INT_OUTBOX_EVT RENAME COLUMN SN_AGGREGATE_VER TO SN_AGG_VER;
ALTER TABLE RHN_INT_OUTBOX_EVT RENAME COLUMN DT_OCCURRED TO DT_OCCRD;
ALTER TABLE RHN_INT_OUTBOX_EVT RENAME COLUMN DT_RECORDED TO DT_RECDD;
ALTER TABLE RHN_INT_OUTBOX_EVT RENAME COLUMN ID_CORRELATION TO ID_CORR;
ALTER TABLE RHN_INT_OUTBOX_EVT RENAME COLUMN ID_CAUSATION TO ID_CAUS;
ALTER TABLE RHN_INT_OUTBOX_EVT RENAME COLUMN SD_PUBLICATION_STATUS TO SD_PUBLCN_STATUS;

-- meta.outpatient_note_form_version
ALTER TABLE RHN_META_OP_NOTE_FORM_VER RENAME COLUMN CD_SPECIALTY TO CD_SPECLTY;

-- meta.outpatient_note_template
ALTER TABLE RHN_META_OP_NOTE_TMPL RENAME COLUMN CD_SPECIALTY TO CD_SPECLTY;

-- meta.outpatient_plan_medication
ALTER TABLE RHN_META_OP_PLAN_MED RENAME COLUMN PREPARATION_SPEC TO PREP_SPEC;
ALTER TABLE RHN_META_OP_PLAN_MED RENAME COLUMN QTY_DURATION_VAL TO QTY_DUR_VAL;
ALTER TABLE RHN_META_OP_PLAN_MED RENAME COLUMN DURATION_UNIT TO DUR_UNIT;
ALTER TABLE RHN_META_OP_PLAN_MED RENAME COLUMN FG_SUBSTITUTION TO FG_SUBSTN;
ALTER TABLE RHN_META_OP_PLAN_MED RENAME COLUMN FG_SELF_PROVIDED TO FG_SELF_PRVDD;
ALTER TABLE RHN_META_OP_PLAN_MED RENAME COLUMN DES_MED_INSTRUCTION TO DES_MED_INSTR;
ALTER TABLE RHN_META_OP_PLAN_MED RENAME COLUMN FG_PRICING_REQUIRED TO FG_PRICING_RQD;

-- meta.outpatient_plan_service
ALTER TABLE RHN_META_OP_PLAN_SVC RENAME COLUMN FG_PRICING_REQUIRED TO FG_PRICING_RQD;
ALTER TABLE RHN_META_OP_PLAN_SVC RENAME COLUMN DES_CLIN_DESCRIPTION TO DES_CLIN_DESCR;

-- ex.outpatient_referral_event
ALTER TABLE RHN_EX_OP_REFER_EVT RENAME COLUMN DT_OCCURRED TO DT_OCCRD;

-- ex.outpatient_referral_request
ALTER TABLE RHN_EX_OP_REFER_REQ RENAME COLUMN DT_EXPECTED TO DT_EXPCTD;
ALTER TABLE RHN_EX_OP_REFER_REQ RENAME COLUMN ID_USER_REQUESTED TO ID_USER_REQD;
ALTER TABLE RHN_EX_OP_REFER_REQ RENAME COLUMN DT_REQUESTED TO DT_REQD;
ALTER TABLE RHN_EX_OP_REFER_REQ RENAME COLUMN ID_USER_ACCEPTED TO ID_USER_ACPTD;
ALTER TABLE RHN_EX_OP_REFER_REQ RENAME COLUMN DT_ACCEPTED TO DT_ACPTD;
ALTER TABLE RHN_EX_OP_REFER_REQ RENAME COLUMN ID_USER_COMPLETED TO ID_USER_CMPLD;
ALTER TABLE RHN_EX_OP_REFER_REQ RENAME COLUMN DT_COMPLETED TO DT_CMPLD;
ALTER TABLE RHN_EX_OP_REFER_REQ RENAME COLUMN DES_REJECTION_REASON TO DES_REJCTN_REASON;

-- sys.parameter_definition
ALTER TABLE RHN_SYS_PARAM_DEF RENAME COLUMN FG_INHERITANCE TO FG_INHRT;
ALTER TABLE RHN_SYS_PARAM_DEF RENAME COLUMN FG_NULLABLE_VAL TO FG_NULLBL_VAL;
ALTER TABLE RHN_SYS_PARAM_DEF RENAME COLUMN SENSITIVITY TO SENS;
ALTER TABLE RHN_SYS_PARAM_DEF RENAME COLUMN SD_DEPENDENCY_BEHAVIOR TO SD_DEPNCY_BEHAV;

-- sys.parameter_value
ALTER TABLE RHN_SYS_PARAM_VAL RENAME COLUMN SCOPE_REFERENCE TO SCOPE_REF;

-- bil.patient_account
ALTER TABLE RHN_BIL_PAT_ACCT RENAME COLUMN CD_CURRENCY TO CD_CCY;

-- sc.patient_registration
ALTER TABLE RHN_SC_PAT_REG RENAME COLUMN DT_REGISTERED TO DT_REGD;
ALTER TABLE RHN_SC_PAT_REG RENAME COLUMN ID_USER_REGISTERED TO ID_USER_REGD;
ALTER TABLE RHN_SC_PAT_REG RENAME COLUMN DT_COMPLETED TO DT_CMPLD;

-- bil.payment_event
ALTER TABLE RHN_BIL_PAY_EVT RENAME COLUMN DT_OCCURRED TO DT_OCCRD;

-- bil.payment_order
ALTER TABLE RHN_BIL_PAY_ORDER RENAME COLUMN ID_PAY_ORIGINAL TO ID_PAY_ORIG;
ALTER TABLE RHN_BIL_PAY_ORDER RENAME COLUMN SD_BUSINESS_SCENE TO SD_BIZ_SCENE;
ALTER TABLE RHN_BIL_PAY_ORDER RENAME COLUMN AMT_REQUESTED TO AMT_REQD;
ALTER TABLE RHN_BIL_PAY_ORDER RENAME COLUMN AMT_CAPTURED TO AMT_CAPTD;
ALTER TABLE RHN_BIL_PAY_ORDER RENAME COLUMN AMT_REFUNDED TO AMT_RFNDD;
ALTER TABLE RHN_BIL_PAY_ORDER RENAME COLUMN CD_CURRENCY TO CD_CCY;
ALTER TABLE RHN_BIL_PAY_ORDER RENAME COLUMN ID_CORRELATION TO ID_CORR;
ALTER TABLE RHN_BIL_PAY_ORDER RENAME COLUMN CD_TERMINAL TO CD_TRMNL;

-- bil.payment
ALTER TABLE RHN_BIL_PAY RENAME COLUMN CD_CURRENCY TO CD_CCY;
ALTER TABLE RHN_BIL_PAY RENAME COLUMN ID_PAY_REVERSES TO ID_PAY_RVRS;

-- sup.pharmacy_review
ALTER TABLE RHN_SUP_PHARM_REVIEW RENAME COLUMN ID_PHARMACIST_PRACT TO ID_PHMCST_PRACT;
ALTER TABLE RHN_SUP_PHARM_REVIEW RENAME COLUMN ID_REVIEWER_USER TO ID_RVWR_USER;
ALTER TABLE RHN_SUP_PHARM_REVIEW RENAME COLUMN ID_REVIEWER_ASSIGN TO ID_RVWR_ASSIGN;
ALTER TABLE RHN_SUP_PHARM_REVIEW RENAME COLUMN DT_REVIEWED TO DT_RVWD;

-- sys.portal_notification
ALTER TABLE RHN_SYS_PORTAL_NOTIFY RENAME COLUMN ID_USER_RECIPIENT TO ID_USER_RCPNT;
ALTER TABLE RHN_SYS_PORTAL_NOTIFY RENAME COLUMN SD_SEVERITY TO SD_SEV;
ALTER TABLE RHN_SYS_PORTAL_NOTIFY RENAME COLUMN DT_ARCHIVED TO DT_ARCHD;

-- sys.portal_user_workspace
ALTER TABLE RHN_SYS_PORTAL_USER_WKSPACE RENAME COLUMN JSON_FAVORITES TO JSON_FAVS;

-- sys.position
ALTER TABLE RHN_SYS_POS RENAME COLUMN DES_DUTY_DESCRIPTION TO DES_DUTY_DESCR;

-- anl.presence_metric_sample
ALTER TABLE RHN_ANL_PRES_METRIC_SAMPLE RENAME COLUMN QTY_ONLINE_CONTEXTS TO QTY_ONLINE_CTXS;
ALTER TABLE RHN_ANL_PRES_METRIC_SAMPLE RENAME COLUMN QTY_CONNECTIONS TO QTY_CONNS;
ALTER TABLE RHN_ANL_PRES_METRIC_SAMPLE RENAME COLUMN QTY_INSTANCES TO QTY_INSTS;

-- sys.print_job
ALTER TABLE RHN_SYS_PRINT_JOB RENAME COLUMN ID_PRINT_JOB_ORIGINAL TO ID_PRINT_JOB_ORIG;
ALTER TABLE RHN_SYS_PRINT_JOB RENAME COLUMN DT_REQUESTED TO DT_REQD;
ALTER TABLE RHN_SYS_PRINT_JOB RENAME COLUMN ID_USER_REQUESTED TO ID_USER_REQD;
ALTER TABLE RHN_SYS_PRINT_JOB RENAME COLUMN ID_CORRELATION TO ID_CORR;

-- sys.print_output
ALTER TABLE RHN_SYS_PRINT_OUTPUT RENAME COLUMN CONTENT_DIGEST_ALGORITHM TO CONTENT_DIGEST_ALGO;
ALTER TABLE RHN_SYS_PRINT_OUTPUT RENAME COLUMN DT_GENERATED TO DT_GEND;
ALTER TABLE RHN_SYS_PRINT_OUTPUT RENAME COLUMN ID_USER_GENERATED TO ID_USER_GEND;

-- meta.print_task_definition
ALTER TABLE RHN_META_PRINT_TASK_DEF RENAME COLUMN SD_CATEGORY TO SD_CAT;
ALTER TABLE RHN_META_PRINT_TASK_DEF RENAME COLUMN CD_DATA_PROVIDER TO CD_DATA_PRVDR;
ALTER TABLE RHN_META_PRINT_TASK_DEF RENAME COLUMN JSON_PURPOSES TO JSON_PURPS;

-- meta.print_implementation
ALTER TABLE RHN_META_PRINT_IMPL RENAME COLUMN SD_RENDERER TO SD_RNDR;

-- meta.print_implementation_binding
ALTER TABLE RHN_META_PRINT_IMPL_BIND RENAME COLUMN SD_FALLBACK TO SD_FALBK;

-- meta.print_template_version
ALTER TABLE RHN_META_PRINT_TMPL_VER RENAME COLUMN CONTENT_DIGEST_ALGORITHM TO CONTENT_DIGEST_ALGO;

-- meta.print_media_profile
ALTER TABLE RHN_META_PRINT_MEDIA RENAME COLUMN SD_ORIENTATION TO SD_ORIENT;
ALTER TABLE RHN_META_PRINT_MEDIA RENAME COLUMN GAP_HORIZONTAL_MM TO GAP_HORIZ_MM;
ALTER TABLE RHN_META_PRINT_MEDIA RENAME COLUMN GAP_VERTICAL_MM TO GAP_VERT_MM;

-- sup.purchase_order_line
ALTER TABLE RHN_SUP_PURCH_ORDER_LINE RENAME COLUMN QTY_RECEIVED TO QTY_RECVD;

-- sup.purchase_order
ALTER TABLE RHN_SUP_PURCH_ORDER RENAME COLUMN DA_EXPECTED TO DA_EXPCTD;
ALTER TABLE RHN_SUP_PURCH_ORDER RENAME COLUMN DT_SUBMITTED TO DT_SUBMTD;
ALTER TABLE RHN_SUP_PURCH_ORDER RENAME COLUMN ID_USER_SUBMITTED TO ID_USER_SUBMTD;
ALTER TABLE RHN_SUP_PURCH_ORDER RENAME COLUMN DT_APPROVED TO DT_APRVD;
ALTER TABLE RHN_SUP_PURCH_ORDER RENAME COLUMN ID_USER_APPROVED TO ID_USER_APRVD;
ALTER TABLE RHN_SUP_PURCH_ORDER RENAME COLUMN DES_APPROVAL_REASON TO DES_APRVL_REASON;

-- sc.queue_counter
ALTER TABLE RHN_SC_QUEUE_COUNT RENAME COLUMN DA_BUSINESS TO DA_BIZ;

-- sc.queue_ticket_event
ALTER TABLE RHN_SC_QUEUE_TICKET_EVT RENAME COLUMN DT_OCCURRED TO DT_OCCRD;
ALTER TABLE RHN_SC_QUEUE_TICKET_EVT RENAME COLUMN ID_USER_OCCURRED TO ID_USER_OCCRD;

-- sc.queue_ticket
ALTER TABLE RHN_SC_QUEUE_TICKET RENAME COLUMN DA_BUSINESS TO DA_BIZ;
ALTER TABLE RHN_SC_QUEUE_TICKET RENAME COLUMN SN_SEQUENCE TO SN_SEQ;
ALTER TABLE RHN_SC_QUEUE_TICKET RENAME COLUMN SN_PRIORITY TO SN_PRI;
ALTER TABLE RHN_SC_QUEUE_TICKET RENAME COLUMN DT_COMPLETED TO DT_CMPLD;

-- bil.receipt_event
ALTER TABLE RHN_BIL_RCPT_EVT RENAME COLUMN DT_OCCURRED TO DT_OCCRD;

-- bil.receipt
ALTER TABLE RHN_BIL_RCPT RENAME COLUMN ID_RCPT_REVERSES TO ID_RCPT_RVRS;
ALTER TABLE RHN_BIL_RCPT RENAME COLUMN CD_FISCAL_AUTHORITY TO CD_FISCAL_AUTHRTY;
ALTER TABLE RHN_BIL_RCPT RENAME COLUMN CD_VERIFICATION TO CD_VRFCTN;
ALTER TABLE RHN_BIL_RCPT RENAME COLUMN CONTROLLED_OBJECT_REFERENCE TO CTRLD_OBJECT_REF;
ALTER TABLE RHN_BIL_RCPT RENAME COLUMN CD_CURRENCY TO CD_CCY;
ALTER TABLE RHN_BIL_RCPT RENAME COLUMN HASH_PAYER_IDENTITY TO HASH_PAYER_IDTY;
ALTER TABLE RHN_BIL_RCPT RENAME COLUMN ID_CORRELATION TO ID_CORR;

-- bil.reconciliation_batch
ALTER TABLE RHN_BIL_RECON_BATCH RENAME COLUMN DA_BUSINESS TO DA_BIZ;
ALTER TABLE RHN_BIL_RECON_BATCH RENAME COLUMN QTY_DIFFERENCE TO QTY_DIFF;
ALTER TABLE RHN_BIL_RECON_BATCH RENAME COLUMN AMT_DIFFERENCE TO AMT_DIFF;
ALTER TABLE RHN_BIL_RECON_BATCH RENAME COLUMN CD_CURRENCY TO CD_CCY;
ALTER TABLE RHN_BIL_RECON_BATCH RENAME COLUMN ID_USER_COMPLETED TO ID_USER_CMPLD;
ALTER TABLE RHN_BIL_RECON_BATCH RENAME COLUMN DT_COMPLETED TO DT_CMPLD;

-- bil.reconciliation_item_event
ALTER TABLE RHN_BIL_RECON_ITEM_EVT RENAME COLUMN DT_OCCURRED TO DT_OCCRD;

-- bil.reconciliation_item
ALTER TABLE RHN_BIL_RECON_ITEM RENAME COLUMN AMT_DIFFERENCE TO AMT_DIFF;
ALTER TABLE RHN_BIL_RECON_ITEM RENAME COLUMN CD_CURRENCY TO CD_CCY;
ALTER TABLE RHN_BIL_RECON_ITEM RENAME COLUMN ID_USER_RESOLVED TO ID_USER_RSLVD;
ALTER TABLE RHN_BIL_RECON_ITEM RENAME COLUMN DT_RESOLVED TO DT_RSLVD;
ALTER TABLE RHN_BIL_RECON_ITEM RENAME COLUMN DES_RESOLUTION TO DES_RSLN;

-- bil.registration_billing_intent
ALTER TABLE RHN_BIL_REG_BIL_INTENT RENAME COLUMN CD_CURRENCY TO CD_CCY;
ALTER TABLE RHN_BIL_REG_BIL_INTENT RENAME COLUMN QTY_COMP_ATTEMPTS TO QTY_COMP_ATMPTS;
ALTER TABLE RHN_BIL_REG_BIL_INTENT RENAME COLUMN DT_COMPLETED TO DT_CMPLD;

-- ex.request_group
ALTER TABLE RHN_EX_REQ_GRP RENAME COLUMN DT_AUTHORED TO DT_AUTHRD;
ALTER TABLE RHN_EX_REQ_GRP RENAME COLUMN ID_USER_AUTHORED TO ID_USER_AUTHRD;
ALTER TABLE RHN_EX_REQ_GRP RENAME COLUMN DT_SUBMITTED TO DT_SUBMTD;
ALTER TABLE RHN_EX_REQ_GRP RENAME COLUMN ID_USER_SUBMITTED TO ID_USER_SUBMTD;
ALTER TABLE RHN_EX_REQ_GRP RENAME COLUMN DT_CANCELLED TO DT_CNCLD;
ALTER TABLE RHN_EX_REQ_GRP RENAME COLUMN ID_USER_CANCELLED TO ID_USER_CNCLD;

-- pi.resident_address
ALTER TABLE RHN_PI_PAT_ADDR RENAME COLUMN CD_PROVINCE TO CD_PROV;
ALTER TABLE RHN_PI_PAT_ADDR RENAME COLUMN CD_DISTRICT TO CD_DIST;
ALTER TABLE RHN_PI_PAT_ADDR RENAME COLUMN CD_COMMUNITY TO CD_COMM;

-- pi.resident_demographic_profile
ALTER TABLE RHN_PI_PAT_DEMO_PROF RENAME COLUMN CD_NATIONALITY TO CD_NATLTY;
ALTER TABLE RHN_PI_PAT_DEMO_PROF RENAME COLUMN CD_ETHNICITY TO CD_ETHNIC;
ALTER TABLE RHN_PI_PAT_DEMO_PROF RENAME COLUMN CD_EDUCATION TO CD_EDUC;
ALTER TABLE RHN_PI_PAT_DEMO_PROF RENAME COLUMN CD_OCCUPATION TO CD_OCCUPN;
ALTER TABLE RHN_PI_PAT_DEMO_PROF RENAME COLUMN CD_RESIDENCY_TYPE TO CD_RESDNCY_TYPE;

-- pi.resident_employment
ALTER TABLE RHN_PI_PAT_EMPL RENAME COLUMN NA_EMPLOYER TO NA_EMPLYR;
ALTER TABLE RHN_PI_PAT_EMPL RENAME COLUMN CD_OCCUPATION TO CD_OCCUPN;

-- pi.resident_identifier
ALTER TABLE RHN_PI_PAT_IDENT RENAME COLUMN NORMALIZED_VALUE TO NORM_VALUE;

-- pi.resident_match_candidate
ALTER TABLE RHN_PI_PAT_MATCH_CAND RENAME COLUMN SD_DECISION TO SD_DCSN;
ALTER TABLE RHN_PI_PAT_MATCH_CAND RENAME COLUMN ID_USER_REVIEWED TO ID_USER_RVWD;
ALTER TABLE RHN_PI_PAT_MATCH_CAND RENAME COLUMN DT_REVIEWED TO DT_RVWD;

-- pi.resident_merge_history
ALTER TABLE RHN_PI_PAT_MERGE_HIST RENAME COLUMN ID_PAT_SURVIVING TO ID_PAT_SURV;
ALTER TABLE RHN_PI_PAT_MERGE_HIST RENAME COLUMN MOVED_IDENTIFIER_IDS TO MOVED_IDENT_IDS;

-- pi.resident_related_person
ALTER TABLE RHN_PI_PAT_RELATED_PERSON RENAME COLUMN CD_RELATIONSHIP TO CD_RELSHIP;
ALTER TABLE RHN_PI_PAT_RELATED_PERSON RENAME COLUMN FG_GUARDIAN_FLAG TO FG_GUARD_FLAG;
ALTER TABLE RHN_PI_PAT_RELATED_PERSON RENAME COLUMN FG_EMERGENCY_CONTACT_FLAG TO FG_EMERG_CONTACT_FLAG;

-- pi.resident_split_history
ALTER TABLE RHN_PI_PAT_SPLIT_HIST RENAME COLUMN ID_PAT_RESTORED TO ID_PAT_RSTRD;
ALTER TABLE RHN_PI_PAT_SPLIT_HIST RENAME COLUMN RESTORED_IDENTIFIER_IDS TO RSTRD_IDENT_IDS;

-- pi.resident
ALTER TABLE RHN_PI_PAT RENAME COLUMN ID_NATIONAL TO ID_NATL;
ALTER TABLE RHN_PI_PAT RENAME COLUMN FG_DECEASED TO FG_DCD;
ALTER TABLE RHN_PI_PAT RENAME COLUMN DT_DECEASED TO DT_DCD;

-- sc.schedule_exception
ALTER TABLE RHN_SC_SCHED_EXCEPT RENAME COLUMN QTY_CAPACITY TO QTY_CAPCTY;

-- sc.schedule_generation_run
ALTER TABLE RHN_SC_SCHED_GEN_RUN RENAME COLUMN QTY_GENERATED TO QTY_GEND;
ALTER TABLE RHN_SC_SCHED_GEN_RUN RENAME COLUMN DT_COMPLETED TO DT_CMPLD;
ALTER TABLE RHN_SC_SCHED_GEN_RUN RENAME COLUMN ID_USER_TRIGGERED TO ID_USER_TRIGD;

-- sc.schedule_slot_hold
ALTER TABLE RHN_SC_SCHED_SLOT_HOLD RENAME COLUMN ID_PAT_REG_CONSUMED TO ID_PAT_REG_CNSMD;

-- sc.schedule_slot_pool
ALTER TABLE RHN_SC_SCHED_SLOT_POOL RENAME COLUMN QTY_OCCUPIED TO QTY_OCCPD;

-- sc.schedule_template_period
ALTER TABLE RHN_SC_SCHED_TMPL_PERIOD RENAME COLUMN QTY_DEFAULT_CAPACITY TO QTY_DEFAULT_CAPCTY;

-- sc.schedule_template
ALTER TABLE RHN_SC_SCHED_TMPL RENAME COLUMN CD_TIMEZONE TO CD_TZ;

-- bd.service_item
ALTER TABLE RHN_BD_SVC_ITEM RENAME COLUMN FG_MEDICAL_TECHNOLOGY TO FG_MEDICAL_TECH;
ALTER TABLE RHN_BD_SVC_ITEM RENAME COLUMN FG_COMBINATION_ITEM TO FG_COMB_ITEM;
ALTER TABLE RHN_BD_SVC_ITEM RENAME COLUMN SD_ACCOUNTING_CAT TO SD_ACCTG_CAT;
ALTER TABLE RHN_BD_SVC_ITEM RENAME COLUMN SD_DUPLICATE_RULE TO SD_DUP_RULE;
ALTER TABLE RHN_BD_SVC_ITEM RENAME COLUMN CD_MUTUAL_RECOGNITION TO CD_MUTUAL_RECOG;
ALTER TABLE RHN_BD_SVC_ITEM RENAME COLUMN FG_PREGNANCY_ALERT TO FG_PREG_ALERT;
ALTER TABLE RHN_BD_SVC_ITEM RENAME COLUMN DES_ATTENTION TO DES_ATTN;

-- ex.service_request
ALTER TABLE RHN_EX_SVC_REQ RENAME COLUMN DES_CLIN_DESCRIPTION TO DES_CLIN_DESCR;

-- sc.service_schedule_event
ALTER TABLE RHN_SC_SVC_SCHED_EVT RENAME COLUMN DT_OCCURRED TO DT_OCCRD;

-- sc.service_schedule
ALTER TABLE RHN_SC_SVC_SCHED RENAME COLUMN CD_TIMEZONE TO CD_TZ;
ALTER TABLE RHN_SC_SVC_SCHED RENAME COLUMN QTY_TOTAL_CAPACITY TO QTY_TOTAL_CAPCTY;

-- bd.service_variant
ALTER TABLE RHN_BD_SVC_VAR RENAME COLUMN FG_BODY_SITE_REQUIRED TO FG_BODY_SITE_RQD;
ALTER TABLE RHN_BD_SVC_VAR RENAME COLUMN CD_MUTUAL_RECOGNITION TO CD_MUTUAL_RECOG;

-- bil.settlement_event
ALTER TABLE RHN_BIL_STL_EVT RENAME COLUMN DT_OCCURRED TO DT_OCCRD;

-- bil.settlement_line
ALTER TABLE RHN_BIL_STL_LINE RENAME COLUMN AMT_DISCOUNT TO AMT_DISC;

-- bil.settlement_tender
ALTER TABLE RHN_BIL_STL_TENDER RENAME COLUMN CD_CURRENCY TO CD_CCY;

-- bil.settlement
ALTER TABLE RHN_BIL_STL RENAME COLUMN ID_STL_REVERSES TO ID_STL_RVRS;
ALTER TABLE RHN_BIL_STL RENAME COLUMN SD_TERMINAL_SCENE TO SD_TRMNL_SCENE;
ALTER TABLE RHN_BIL_STL RENAME COLUMN AMT_DISCOUNT TO AMT_DISC;
ALTER TABLE RHN_BIL_STL RENAME COLUMN AMT_ROUNDING TO AMT_RND;
ALTER TABLE RHN_BIL_STL RENAME COLUMN CD_CURRENCY TO CD_CCY;
ALTER TABLE RHN_BIL_STL RENAME COLUMN CD_TERMINAL TO CD_TRMNL;
ALTER TABLE RHN_BIL_STL RENAME COLUMN ID_USER_FINALIZED TO ID_USER_FNLZD;
ALTER TABLE RHN_BIL_STL RENAME COLUMN DT_FINALIZED TO DT_FNLZD;

-- ex.skin_test_event
ALTER TABLE RHN_EX_SKIN_TEST_EVT RENAME COLUMN FG_ORIGINAL_SOLUTION TO FG_ORIG_SOLN;
ALTER TABLE RHN_EX_SKIN_TEST_EVT RENAME COLUMN ID_CATALOG_ITEM_SOLUTION TO ID_CATALOG_ITEM_SOLN;
ALTER TABLE RHN_EX_SKIN_TEST_EVT RENAME COLUMN NA_SOLUTION_SNAP TO NA_SOLN_SNAP;
ALTER TABLE RHN_EX_SKIN_TEST_EVT RENAME COLUMN CONCENTRATION TO CONC;
ALTER TABLE RHN_EX_SKIN_TEST_EVT RENAME COLUMN CONCENTRATION_UNIT TO CONC_UNIT;
ALTER TABLE RHN_EX_SKIN_TEST_EVT RENAME COLUMN SD_VERIFICATION_METHOD TO SD_VRFCTN_METHOD;
ALTER TABLE RHN_EX_SKIN_TEST_EVT RENAME COLUMN DT_COMPLETED TO DT_CMPLD;
ALTER TABLE RHN_EX_SKIN_TEST_EVT RENAME COLUMN QTY_WHEAL_DIAMETER_MM TO QTY_WHEAL_DIAM_MM;
ALTER TABLE RHN_EX_SKIN_TEST_EVT RENAME COLUMN QTY_FLARE_DIAMETER_MM TO QTY_FLARE_DIAM_MM;
ALTER TABLE RHN_EX_SKIN_TEST_EVT RENAME COLUMN DES_REACTION_DESCRIPTION TO DES_REACT_DESCR;
ALTER TABLE RHN_EX_SKIN_TEST_EVT RENAME COLUMN ID_USER_PERFORMED TO ID_USER_PRFRMD;
ALTER TABLE RHN_EX_SKIN_TEST_EVT RENAME COLUMN ID_PRACT_PERFORMED TO ID_PRACT_PRFRMD;
ALTER TABLE RHN_EX_SKIN_TEST_EVT RENAME COLUMN DT_CANCELLED TO DT_CNCLD;
ALTER TABLE RHN_EX_SKIN_TEST_EVT RENAME COLUMN ID_USER_CANCELLED TO ID_USER_CNCLD;
ALTER TABLE RHN_EX_SKIN_TEST_EVT RENAME COLUMN ID_USER_VERIFIED TO ID_USER_VRFD;
ALTER TABLE RHN_EX_SKIN_TEST_EVT RENAME COLUMN ID_PRACT_VERIFIED TO ID_PRACT_VRFD;
ALTER TABLE RHN_EX_SKIN_TEST_EVT RENAME COLUMN NA_PRACT_VERIFIED TO NA_PRACT_VRFD;
ALTER TABLE RHN_EX_SKIN_TEST_EVT RENAME COLUMN DT_VERIFIED TO DT_VRFD;

-- sc.slot_event
ALTER TABLE RHN_SC_SLOT_EVT RENAME COLUMN SN_SEQUENCE TO SN_SEQ;
ALTER TABLE RHN_SC_SLOT_EVT RENAME COLUMN QTY_OCCUPIED_DELTA TO QTY_OCCPD_DELTA;
ALTER TABLE RHN_SC_SLOT_EVT RENAME COLUMN DT_OCCURRED TO DT_OCCRD;

-- sys.staff_assignment
ALTER TABLE RHN_SYS_STAFF_ASSIGN RENAME COLUMN CD_SPECIALTY TO CD_SPECLTY;
ALTER TABLE RHN_SYS_STAFF_ASSIGN RENAME COLUMN WORKLOAD_PERCENT TO WKLOAD_PERCENT;

-- sup.stock_count_line
ALTER TABLE RHN_SUP_STOCK_COUNT_LINE RENAME COLUMN QTY_VARIANCE TO QTY_VARNC;
ALTER TABLE RHN_SUP_STOCK_COUNT_LINE RENAME COLUMN DES_VARIANCE_REASON TO DES_VARNC_REASON;

-- sup.stock_count
ALTER TABLE RHN_SUP_STOCK_COUNT RENAME COLUMN DT_SUBMITTED TO DT_SUBMTD;
ALTER TABLE RHN_SUP_STOCK_COUNT RENAME COLUMN ID_USER_SUBMITTED TO ID_USER_SUBMTD;
ALTER TABLE RHN_SUP_STOCK_COUNT RENAME COLUMN DT_APPROVED TO DT_APRVD;
ALTER TABLE RHN_SUP_STOCK_COUNT RENAME COLUMN ID_USER_APPROVED TO ID_USER_APRVD;

-- sup.stock_item
ALTER TABLE RHN_SUP_STOCK_ITEM RENAME COLUMN FG_NEGATIVE TO FG_NEG;
ALTER TABLE RHN_SUP_STOCK_ITEM RENAME COLUMN FG_LOT_REQUIRED TO FG_LOT_RQD;
ALTER TABLE RHN_SUP_STOCK_ITEM RENAME COLUMN FG_TRACE_REQUIRED TO FG_TRACE_RQD;
ALTER TABLE RHN_SUP_STOCK_ITEM RENAME COLUMN FG_CONTROLLED TO FG_CTRLD;

-- sup.stock_lot
ALTER TABLE RHN_SUP_STOCK_LOT RENAME COLUMN DA_PRODUCTION TO DA_PROD;
ALTER TABLE RHN_SUP_STOCK_LOT RENAME COLUMN CD_APPROVAL_SNAP TO CD_APRVL_SNAP;

-- sup.stock_requisition_allocation
ALTER TABLE RHN_SUP_STOCK_REQ_ALLOC RENAME COLUMN QTY_ALLOCATED TO QTY_ALLOCD;

-- sup.stock_requisition_line
ALTER TABLE RHN_SUP_STOCK_REQ_LINE RENAME COLUMN QTY_REQUESTED TO QTY_REQD;
ALTER TABLE RHN_SUP_STOCK_REQ_LINE RENAME COLUMN QTY_APPROVED TO QTY_APRVD;

-- sup.stock_requisition
ALTER TABLE RHN_SUP_STOCK_REQ RENAME COLUMN ID_DEPT_REQUESTING TO ID_DEPT_REQNG;
ALTER TABLE RHN_SUP_STOCK_REQ RENAME COLUMN ID_STOCK_SITE_DESTINATION TO ID_STOCK_SITE_DEST;
ALTER TABLE RHN_SUP_STOCK_REQ RENAME COLUMN DT_REQUESTED TO DT_REQD;
ALTER TABLE RHN_SUP_STOCK_REQ RENAME COLUMN ID_USER_REQUESTED TO ID_USER_REQD;
ALTER TABLE RHN_SUP_STOCK_REQ RENAME COLUMN DT_APPROVED TO DT_APRVD;
ALTER TABLE RHN_SUP_STOCK_REQ RENAME COLUMN ID_USER_APPROVED TO ID_USER_APRVD;

-- sup.stock_return_line
ALTER TABLE RHN_SUP_STOCK_RETURN_LINE RENAME COLUMN ID_MED_DISP_LINE_ORIGINAL TO ID_MED_DISP_LINE_ORIG;
ALTER TABLE RHN_SUP_STOCK_RETURN_LINE RENAME COLUMN QTY_REQUESTED TO QTY_REQD;
ALTER TABLE RHN_SUP_STOCK_RETURN_LINE RENAME COLUMN QTY_ACCEPTED TO QTY_ACPTD;
ALTER TABLE RHN_SUP_STOCK_RETURN_LINE RENAME COLUMN BASE_QUANTITY_FACTOR TO BASE_QTY_FACTOR;
ALTER TABLE RHN_SUP_STOCK_RETURN_LINE RENAME COLUMN SD_DISPOSITION TO SD_DISPOS;
ALTER TABLE RHN_SUP_STOCK_RETURN_LINE RENAME COLUMN DES_EXCEPT_DESCRIPTION TO DES_EXCEPT_DESCR;

-- sup.stock_return
ALTER TABLE RHN_SUP_STOCK_RETURN RENAME COLUMN ID_MED_DISP_ORIGINAL TO ID_MED_DISP_ORIG;
ALTER TABLE RHN_SUP_STOCK_RETURN RENAME COLUMN DT_REQUESTED TO DT_REQD;
ALTER TABLE RHN_SUP_STOCK_RETURN RENAME COLUMN ID_USER_REQUESTED TO ID_USER_REQD;
ALTER TABLE RHN_SUP_STOCK_RETURN RENAME COLUMN DT_CONFIRMED TO DT_CNFRMD;
ALTER TABLE RHN_SUP_STOCK_RETURN RENAME COLUMN ID_USER_CONFIRMED TO ID_USER_CNFRMD;

-- sup.stock_transfer_allocation
ALTER TABLE RHN_SUP_STOCK_XFER_ALLOC RENAME COLUMN ID_STOCK_BIN_DESTINATION TO ID_STOCK_BIN_DEST;
ALTER TABLE RHN_SUP_STOCK_XFER_ALLOC RENAME COLUMN QTY_DISPATCHED TO QTY_DSPTD;
ALTER TABLE RHN_SUP_STOCK_XFER_ALLOC RENAME COLUMN QTY_RECEIVED TO QTY_RECVD;

-- sup.stock_transfer_line
ALTER TABLE RHN_SUP_STOCK_XFER_LINE RENAME COLUMN ID_STOCK_ITEM_DESTINATION TO ID_STOCK_ITEM_DEST;
ALTER TABLE RHN_SUP_STOCK_XFER_LINE RENAME COLUMN QTY_REQUESTED TO QTY_REQD;
ALTER TABLE RHN_SUP_STOCK_XFER_LINE RENAME COLUMN QTY_APPROVED TO QTY_APRVD;
ALTER TABLE RHN_SUP_STOCK_XFER_LINE RENAME COLUMN QTY_DISPATCHED TO QTY_DSPTD;
ALTER TABLE RHN_SUP_STOCK_XFER_LINE RENAME COLUMN QTY_RECEIVED TO QTY_RECVD;
ALTER TABLE RHN_SUP_STOCK_XFER_LINE RENAME COLUMN DES_DISCREPANCY_REASON TO DES_DSCRPN_REASON;
ALTER TABLE RHN_SUP_STOCK_XFER_LINE RENAME COLUMN QTY_REQUESTED_OPERATION TO QTY_REQD_OPER;
ALTER TABLE RHN_SUP_STOCK_XFER_LINE RENAME COLUMN CD_OPERATION_UNIT TO CD_OPER_UNIT;
ALTER TABLE RHN_SUP_STOCK_XFER_LINE RENAME COLUMN BASE_QUANTITY_FACTOR TO BASE_QTY_FACTOR;

-- sup.stock_transfer
ALTER TABLE RHN_SUP_STOCK_XFER RENAME COLUMN ID_STOCK_SITE_DESTINATION TO ID_STOCK_SITE_DEST;
ALTER TABLE RHN_SUP_STOCK_XFER RENAME COLUMN DT_REQUESTED TO DT_REQD;
ALTER TABLE RHN_SUP_STOCK_XFER RENAME COLUMN ID_USER_REQUESTED TO ID_USER_REQD;
ALTER TABLE RHN_SUP_STOCK_XFER RENAME COLUMN DT_APPROVED TO DT_APRVD;
ALTER TABLE RHN_SUP_STOCK_XFER RENAME COLUMN ID_USER_APPROVED TO ID_USER_APRVD;
ALTER TABLE RHN_SUP_STOCK_XFER RENAME COLUMN DT_DISPATCHED TO DT_DSPTD;
ALTER TABLE RHN_SUP_STOCK_XFER RENAME COLUMN ID_USER_DISPATCHED TO ID_USER_DSPTD;
ALTER TABLE RHN_SUP_STOCK_XFER RENAME COLUMN DT_RECEIVED TO DT_RECVD;
ALTER TABLE RHN_SUP_STOCK_XFER RENAME COLUMN ID_USER_RECEIVED TO ID_USER_RECVD;
ALTER TABLE RHN_SUP_STOCK_XFER RENAME COLUMN ID_INV_TXN_OUTBOUND TO ID_INV_TXN_OUTBND;

-- sup.supplier_supply_item
ALTER TABLE RHN_SUP_SUPPL_SUPPLY_ITEM RENAME COLUMN PRICE_AGREEMENT TO PRICE_AGRMT;

-- bd.supply_item
ALTER TABLE RHN_BD_SUPPLY_ITEM RENAME COLUMN SD_MATERIAL_TYPE TO SD_MATL_TYPE;
ALTER TABLE RHN_BD_SUPPLY_ITEM RENAME COLUMN FG_INTERVENTION TO FG_INTRVN;
ALTER TABLE RHN_BD_SUPPLY_ITEM RENAME COLUMN NA_REGISTRANT TO NA_REGSTR;
ALTER TABLE RHN_BD_SUPPLY_ITEM RENAME COLUMN DES_STRUCTURE_DESCRIPTION TO DES_STRUCT_DESCR;
ALTER TABLE RHN_BD_SUPPLY_ITEM RENAME COLUMN DES_SCOPE_DESCRIPTION TO DES_SCOPE_DESCR;
ALTER TABLE RHN_BD_SUPPLY_ITEM RENAME COLUMN DES_INSTRUCTION TO DES_INSTR;

-- sys.system_announcement
ALTER TABLE RHN_SYS_ANN RENAME COLUMN SD_PRIORITY TO SD_PRI;
ALTER TABLE RHN_SYS_ANN RENAME COLUMN ID_USER_WITHDRAWN TO ID_USER_WDRWN;
ALTER TABLE RHN_SYS_ANN RENAME COLUMN DT_WITHDRAWN TO DT_WDRWN;

-- sys.tenant
ALTER TABLE RHN_SYS_TNT RENAME COLUMN CD_TIMEZONE TO CD_TZ;

-- ex.treatment_execution_item
ALTER TABLE RHN_EX_TREAT_EXEC_ITEM RENAME COLUMN QTY_DURATION_VAL TO QTY_DUR_VAL;
ALTER TABLE RHN_EX_TREAT_EXEC_ITEM RENAME COLUMN DURATION_UNIT TO DUR_UNIT;
ALTER TABLE RHN_EX_TREAT_EXEC_ITEM RENAME COLUMN FG_SKIN_TEST_REQUIRED TO FG_SKIN_TEST_RQD;
ALTER TABLE RHN_EX_TREAT_EXEC_ITEM RENAME COLUMN FG_STL_REQUIRED TO FG_STL_RQD;
ALTER TABLE RHN_EX_TREAT_EXEC_ITEM RENAME COLUMN FG_FULFILL_REQUIRED TO FG_FULFILL_RQD;
ALTER TABLE RHN_EX_TREAT_EXEC_ITEM RENAME COLUMN DT_CANCELLED TO DT_CNCLD;
ALTER TABLE RHN_EX_TREAT_EXEC_ITEM RENAME COLUMN FREQUENCY_RULE_SNAPSHOT TO FREQ_RULE_SNAP;

-- ex.treatment_execution_task
ALTER TABLE RHN_EX_TREAT_EXEC_TASK RENAME COLUMN SD_VERIFICATION_METHOD TO SD_VRFCTN_METHOD;
ALTER TABLE RHN_EX_TREAT_EXEC_TASK RENAME COLUMN DT_COMPLETED TO DT_CMPLD;
ALTER TABLE RHN_EX_TREAT_EXEC_TASK RENAME COLUMN ID_USER_COMPLETED TO ID_USER_CMPLD;
ALTER TABLE RHN_EX_TREAT_EXEC_TASK RENAME COLUMN FG_ADVERSE_REACTION TO FG_ADVERSE_REACT;
ALTER TABLE RHN_EX_TREAT_EXEC_TASK RENAME COLUMN DES_ADVERSE_REACTION_DETAIL TO DES_ADVERSE_REACT_DETAIL;

-- bd.unit_definition
ALTER TABLE RHN_BD_UNIT_DEF RENAME COLUMN DIMENSION TO DIM;

-- sys.user_account
ALTER TABLE RHN_SYS_USER_ACCT RENAME COLUMN CD_USERNAME TO CD_USRNM;
ALTER TABLE RHN_SYS_USER_ACCT RENAME COLUMN HASH_PASSWORD TO HASH_PWD;
ALTER TABLE RHN_SYS_USER_ACCT RENAME COLUMN DT_PASSWORD_CHANGED TO DT_PWD_CHANGED;

-- bd.value_set
ALTER TABLE RHN_BD_VAL_SET RENAME COLUMN DA_EFFECTIVE_FROM TO DA_EFF_FROM;
ALTER TABLE RHN_BD_VAL_SET RENAME COLUMN DA_EFFECTIVE_TO TO DA_EFF_TO;

-- sup.ward_delivery
ALTER TABLE RHN_SUP_WARD_DELIV RENAME COLUMN DT_DISPATCHED TO DT_DSPTD;
ALTER TABLE RHN_SUP_WARD_DELIV RENAME COLUMN ID_USER_DISPATCHED TO ID_USER_DSPTD;
ALTER TABLE RHN_SUP_WARD_DELIV RENAME COLUMN DES_DISPATCH_NOTE TO DES_DSPT_NOTE;
ALTER TABLE RHN_SUP_WARD_DELIV RENAME COLUMN DT_RECEIVED TO DT_RECVD;
ALTER TABLE RHN_SUP_WARD_DELIV RENAME COLUMN ID_USER_RECEIVED TO ID_USER_RECVD;
ALTER TABLE RHN_SUP_WARD_DELIV RENAME COLUMN DES_DISCREPANCY_NOTE TO DES_DSCRPN_NOTE;
ALTER TABLE RHN_SUP_WARD_DELIV RENAME COLUMN DT_RESOLVED TO DT_RSLVD;
ALTER TABLE RHN_SUP_WARD_DELIV RENAME COLUMN ID_USER_RESOLVED TO ID_USER_RSLVD;
ALTER TABLE RHN_SUP_WARD_DELIV RENAME COLUMN CD_RESOLUTION TO CD_RSLN;
ALTER TABLE RHN_SUP_WARD_DELIV RENAME COLUMN DES_RESOLUTION_NOTE TO DES_RSLN_NOTE;

-- sup.ward_delivery_event
ALTER TABLE RHN_SUP_WARD_DELIV_EVT RENAME COLUMN DT_OCCURRED TO DT_OCCRD;
ALTER TABLE RHN_SUP_WARD_DELIV_EVT RENAME COLUMN ID_USER_OCCURRED TO ID_USER_OCCRD;

-- sup.ward_delivery_line
ALTER TABLE RHN_SUP_WARD_DELIV_LINE RENAME COLUMN QTY_EXPECTED TO QTY_EXPCTD;
ALTER TABLE RHN_SUP_WARD_DELIV_LINE RENAME COLUMN QTY_RECEIVED TO QTY_RECVD;
ALTER TABLE RHN_SUP_WARD_DELIV_LINE RENAME COLUMN CD_DISCREPANCY TO CD_DSCRPN;
ALTER TABLE RHN_SUP_WARD_DELIV_LINE RENAME COLUMN DES_DISCREPANCY_NOTE TO DES_DSCRPN_NOTE;

-- sup.ward_med_return_event
ALTER TABLE RHN_SUP_WARD_MED_RETURN_EVT RENAME COLUMN DT_OCCURRED TO DT_OCCRD;
ALTER TABLE RHN_SUP_WARD_MED_RETURN_EVT RENAME COLUMN ID_USER_OCCURRED TO ID_USER_OCCRD;

-- sup.ward_med_return_line
ALTER TABLE RHN_SUP_WARD_MED_RETURN_LINE RENAME COLUMN ID_MED_DISP_ORIGINAL TO ID_MED_DISP_ORIG;
ALTER TABLE RHN_SUP_WARD_MED_RETURN_LINE RENAME COLUMN ID_MED_DISP_LINE_ORIGINAL TO ID_MED_DISP_LINE_ORIG;
ALTER TABLE RHN_SUP_WARD_MED_RETURN_LINE RENAME COLUMN QTY_REQUESTED TO QTY_REQD;
ALTER TABLE RHN_SUP_WARD_MED_RETURN_LINE RENAME COLUMN QTY_REQUESTED_BASE TO QTY_REQD_BASE;
ALTER TABLE RHN_SUP_WARD_MED_RETURN_LINE RENAME COLUMN SD_DISPOSITION TO SD_DISPOS;

-- sup.ward_med_return_request
ALTER TABLE RHN_SUP_WARD_MED_RETURN_REQ RENAME COLUMN DT_REQUESTED TO DT_REQD;
ALTER TABLE RHN_SUP_WARD_MED_RETURN_REQ RENAME COLUMN ID_USER_REQUESTED TO ID_USER_REQD;
ALTER TABLE RHN_SUP_WARD_MED_RETURN_REQ RENAME COLUMN DES_HANDOVER_NOTE TO DES_HNDOVR_NOTE;
ALTER TABLE RHN_SUP_WARD_MED_RETURN_REQ RENAME COLUMN DT_RECEIVED TO DT_RECVD;
ALTER TABLE RHN_SUP_WARD_MED_RETURN_REQ RENAME COLUMN ID_USER_RECEIVED TO ID_USER_RECVD;
ALTER TABLE RHN_SUP_WARD_MED_RETURN_REQ RENAME COLUMN ID_PROCESSOR_PRACT TO ID_PROCSR_PRACT;
ALTER TABLE RHN_SUP_WARD_MED_RETURN_REQ RENAME COLUMN ID_PROCESSOR_ASSIGN TO ID_PROCSR_ASSIGN;

-- sys.work_task_history
ALTER TABLE RHN_SYS_WORK_TASK_HIST RENAME COLUMN ID_CORRELATION TO ID_CORR;
ALTER TABLE RHN_SYS_WORK_TASK_HIST RENAME COLUMN DT_OCCURRED TO DT_OCCRD;

-- sys.work_task
ALTER TABLE RHN_SYS_WORK_TASK RENAME COLUMN SD_PRIORITY TO SD_PRI;
ALTER TABLE RHN_SYS_WORK_TASK RENAME COLUMN SD_ASSIGNEE_TYPE TO SD_ASGNEE_TYPE;
ALTER TABLE RHN_SYS_WORK_TASK RENAME COLUMN ID_USER_ASSIGNEE TO ID_USER_ASGNEE;
ALTER TABLE RHN_SYS_WORK_TASK RENAME COLUMN ID_USER_COMPLETED TO ID_USER_CMPLD;
ALTER TABLE RHN_SYS_WORK_TASK RENAME COLUMN DT_COMPLETED TO DT_CMPLD;

-- meta.print_device
ALTER TABLE RHN_META_PRINT_DEVICE RENAME COLUMN JSON_CAPABILITIES TO JSON_CAPS;

-- sys.print_batch
ALTER TABLE RHN_SYS_PRINT_BATCH RENAME COLUMN DA_BUSINESS TO DA_BIZ;
ALTER TABLE RHN_SYS_PRINT_BATCH RENAME COLUMN JSON_SELECTION TO JSON_SELCTN;
ALTER TABLE RHN_SYS_PRINT_BATCH RENAME COLUMN SD_LAYOUT_STRATEGY TO SD_LAYOUT_STRAT;
ALTER TABLE RHN_SYS_PRINT_BATCH RENAME COLUMN ID_IDEMPOTENCY TO ID_IDEMP;
ALTER TABLE RHN_SYS_PRINT_BATCH RENAME COLUMN QTY_SELECTED TO QTY_SELCTD;
ALTER TABLE RHN_SYS_PRINT_BATCH RENAME COLUMN QTY_INCLUDED TO QTY_INCLD;
ALTER TABLE RHN_SYS_PRINT_BATCH RENAME COLUMN QTY_EXCLUDED TO QTY_EXCLD;

-- sys.print_batch_item
ALTER TABLE RHN_SYS_PRINT_BATCH_ITEM RENAME COLUMN JSON_SNAPSHOT TO JSON_SNAP;

-- sys.print_delivery
ALTER TABLE RHN_SYS_PRINT_DELIVERY RENAME COLUMN ID_PRINT_DELIVERY TO ID_PRINT_DELIV;
ALTER TABLE RHN_SYS_PRINT_DELIVERY RENAME COLUMN DT_CONFIRMED TO DT_CNFRMD;

-- an.catalog_ver
ALTER TABLE RHN_AN_CATALOG_VER RENAME COLUMN JSON_DEFINITION TO JSON_DEF;

-- an.run
ALTER TABLE RHN_AN_RUN RENAME COLUMN SD_DELIVERY TO SD_DELIV;

-- bd.allergen
ALTER TABLE RHN_BD_ALLERGEN RENAME COLUMN ID_ALLERGEN TO ID_ALRGN;
ALTER TABLE RHN_BD_ALLERGEN RENAME COLUMN CD_ALLERGEN TO CD_ALRGN;
ALTER TABLE RHN_BD_ALLERGEN RENAME COLUMN NA_ALLERGEN TO NA_ALRGN;

-- bd.med_allergen_map
ALTER TABLE RHN_BD_MED_ALLERGEN_MAP RENAME COLUMN ID_MED_ALLERGEN_MAP TO ID_MED_ALRGN_MAP;
ALTER TABLE RHN_BD_MED_ALLERGEN_MAP RENAME COLUMN ID_ALLERGEN TO ID_ALRGN;
ALTER TABLE RHN_BD_MED_ALLERGEN_MAP RENAME COLUMN SD_RELATION_TYPE TO SD_REL_TYPE;

-- bd.med_class_map
ALTER TABLE RHN_BD_MED_CLASS_MAP RENAME COLUMN SOURCE_REFERENCE TO SOURCE_REF;

-- op.triage_rec
ALTER TABLE RHN_OP_TRIAGE_REC RENAME COLUMN ID_RESIDENT TO ID_RESDNT;
ALTER TABLE RHN_OP_TRIAGE_REC RENAME COLUMN SD_COMPANION_TYPE TO SD_CMPNON_TYPE;
ALTER TABLE RHN_OP_TRIAGE_REC RENAME COLUMN DES_CHIEF_COMPLAINT TO DES_CHIEF_CMPLNT;
ALTER TABLE RHN_OP_TRIAGE_REC RENAME COLUMN TXT_SYMPTOMS TO TXT_SYMPT;
ALTER TABLE RHN_OP_TRIAGE_REC RENAME COLUMN SD_CONSCIOUSNESS TO SD_CNSC;
ALTER TABLE RHN_OP_TRIAGE_REC RENAME COLUMN TXT_EPIDEMIC TO TXT_EPID;
ALTER TABLE RHN_OP_TRIAGE_REC RENAME COLUMN SD_DISPOSITION TO SD_DISPOS;

-- sup.rx_inv_freeze
ALTER TABLE RHN_SUP_RX_INV_FREEZE RENAME COLUMN DT_RELEASED TO DT_RLSD;
ALTER TABLE RHN_SUP_RX_INV_FREEZE RENAME COLUMN ID_USER_RELEASED TO ID_USER_RLSD;

-- aud.quality_rule_definition
ALTER TABLE RHN_AUD_MED_RULE RENAME COLUMN CD_CATEGORY TO CD_CAT;

-- aud.quality_rule_version
ALTER TABLE RHN_AUD_MED_RULE_VER RENAME COLUMN CD_IMPLEMENTATION TO CD_IMPL;
ALTER TABLE RHN_AUD_MED_RULE_VER RENAME COLUMN SD_SEVERITY TO SD_SEV;
ALTER TABLE RHN_AUD_MED_RULE_VER RENAME COLUMN SD_DECISION TO SD_DCSN;
ALTER TABLE RHN_AUD_MED_RULE_VER RENAME COLUMN SD_OVERRIDE_POLICY TO SD_OVRD_POLICY;
ALTER TABLE RHN_AUD_MED_RULE_VER RENAME COLUMN DT_EFFECTIVE_FROM TO DT_EFF_FROM;
ALTER TABLE RHN_AUD_MED_RULE_VER RENAME COLUMN DT_EFFECTIVE_TO TO DT_EFF_TO;
ALTER TABLE RHN_AUD_MED_RULE_VER RENAME COLUMN JSON_EVIDENCE TO JSON_EVID;

-- aud.quality_evaluation
ALTER TABLE RHN_AUD_MED_EVAL RENAME COLUMN ID_PRESCRIPTION TO ID_RX;
ALTER TABLE RHN_AUD_MED_EVAL RENAME COLUMN SD_DECISION TO SD_DCSN;
ALTER TABLE RHN_AUD_MED_EVAL RENAME COLUMN DT_COMPLETED TO DT_CMPLD;

-- aud.quality_finding
ALTER TABLE RHN_AUD_MED_FINDING RENAME COLUMN SD_SEVERITY TO SD_SEV;
ALTER TABLE RHN_AUD_MED_FINDING RENAME COLUMN SD_DECISION TO SD_DCSN;
ALTER TABLE RHN_AUD_MED_FINDING RENAME COLUMN JSON_EVIDENCE TO JSON_EVID;
ALTER TABLE RHN_AUD_MED_FINDING RENAME COLUMN SD_OVERRIDE_POLICY TO SD_OVRD_POLICY;

-- aud.quality_override
ALTER TABLE RHN_AUD_MED_OVERRIDE RENAME COLUMN ID_OVERRIDE TO ID_OVRD;

-- bd.clinical_semantic_version
ALTER TABLE RHN_BD_CLIN_SEM_VER RENAME COLUMN JSON_SNAPSHOT TO JSON_SNAP;
ALTER TABLE RHN_BD_CLIN_SEM_VER RENAME COLUMN DT_RECORDED TO DT_RECDD;
ALTER TABLE RHN_BD_CLIN_SEM_VER RENAME COLUMN ID_USER_RECORDED TO ID_USER_RECDD;
ALTER TABLE RHN_BD_CLIN_SEM_VER RENAME COLUMN CD_IDENTITY_KEY TO CD_IDTY_KEY;

-- aud.medication_rule_governance_run
ALTER TABLE RHN_AUD_MED_GOV_RUN RENAME COLUMN SD_DECISION TO SD_DCSN;
ALTER TABLE RHN_AUD_MED_GOV_RUN RENAME COLUMN ID_PRESCRIPTION TO ID_RX;
ALTER TABLE RHN_AUD_MED_GOV_RUN RENAME COLUMN ID_DEPLOYMENT TO ID_DEPLOY;

-- bd.search_entry
ALTER TABLE RHN_BD_SEARCH_ENTRY RENAME COLUMN CD_MNEMONIC TO CD_MNEM;

-- bd.standard_catalog_review
ALTER TABLE RHN_BD_STD_REVIEW RENAME COLUMN HASH_IDENTITY TO HASH_IDTY;

-- aud.medication_knowledge_draft
ALTER TABLE RHN_AUD_MED_KNOW_DRAFT RENAME COLUMN ID_KNOWLEDGE TO ID_KNOW;

-- aud.medication_knowledge_replay
ALTER TABLE RHN_AUD_KNOW_REPLAY RENAME COLUMN ID_KNOWLEDGE TO ID_KNOW;

-- aud.medication_knowledge_rule
ALTER TABLE RHN_AUD_KNOW_RULE RENAME COLUMN ID_KNOWLEDGE TO ID_KNOW;
ALTER TABLE RHN_AUD_KNOW_RULE RENAME COLUMN NO_KNOWLEDGE_VERSION TO NO_KNOW_VERSION;
ALTER TABLE RHN_AUD_KNOW_RULE RENAME COLUMN CD_COMPILER_VER TO CD_CMPLR_VER;

-- aud.medication_rule_intake
ALTER TABLE RHN_AUD_KNOW_INTAKE RENAME COLUMN ID_FEEDBACK TO ID_FDBK;

-- aud.medication_knowledge_feedback
ALTER TABLE RHN_AUD_KNOW_FEEDBACK RENAME COLUMN ID_FEEDBACK TO ID_FDBK;
ALTER TABLE RHN_AUD_KNOW_FEEDBACK RENAME COLUMN ID_DEPLOYMENT TO ID_DEPLOY;
ALTER TABLE RHN_AUD_KNOW_FEEDBACK RENAME COLUMN SD_OPERATION TO SD_OPER;

-- aud.medication_knowledge_release
ALTER TABLE RHN_AUD_KNOW_RELEASE RENAME COLUMN ID_DEPLOYMENT TO ID_DEPLOY;

-- bd.standard_catalog_edition
ALTER TABLE RHN_BD_STD_EDITION RENAME COLUMN JSON_METADATA TO JSON_META;
ALTER TABLE RHN_BD_STD_EDITION RENAME COLUMN HASH_METADATA TO HASH_META;

-- Complete the governed catalog comment for the V1.76 field.
COMMENT ON COLUMN RHN_BD_MED_STD_SOURCE.CD_BINDING_CLAIM IS '标准绑定声明；CANONICAL 约束新建标准药品，EXISTING:本地标识保留共享标准身份的历史本地记录';

ALTER TABLE RHN_AUD_KNOW_FEEDBACK RENAME COLUMN NO_REVISION TO NO_REV;
