-- Optimize clinical catalog: split multi-form medications into distinct master records and govern investigation aliases.

-- 1. Split compound (tablet / capsule) western medications into distinct master records

-- Govern MED-2026-W078-06: normalize capsule master and create tablet master (布洛芬缓释片)
update RHN_BD_MED set NA_MED = '布洛芬缓释胶囊', NA_ALIAS = 'Ibuprofen', DOSE_FORM = 'CAPSULE', PREP_UNIT = '粒' where ID_MED = 362387880000268;
update RHN_BD_MED_WESTERN set ACTIVE_INGR = '布洛芬缓释胶囊' where ID_MED = 362387880000268;

insert into RHN_BD_MED (ID_MED, REVISION, ID_TNT, CD_MED, NA_MED, NA_ALIAS, SD_MED_TYPE, DOSE_FORM, PREP_SPEC, PREP_UNIT, QTY_STRNTH_VAL, STRNTH_UNIT, SD_STORAGE_TYPE, FG_RX_DRUG, FG_ESSNTL_DRUG, FG_ANTIMIC, SD_ANTIMIC_LEVEL, FG_SKIN_TEST_RQD, QTY_DEFAULT_DOSE, DEFAULT_DOSE_UNIT, DEFAULT_ROUTE, DEFAULT_FREQ, FG_CHRONIC_DISEASE_DRUG, FG_SINGLE_ORDER, SD_STATUS, DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED, ID_ITEM_TYPE, ID_ITEM_MASTER, ID_ORDER_FREQ_DEFAULT, ID_CONCEPT_DEFAULT_ROUTE, FG_ANTIMIC_OP, FG_ANTIMIC_CONSULT, FG_ANTIMIC_EMERG, QTY_ANTIMIC_MAX_DAYS, SD_SKIN_TEST_METHOD, SD_SKIN_TEST_SOLN_MODE, QTY_SKIN_TEST_OBS_MINUTES, QTY_SKIN_TEST_VALID_HOURS, DES_SKIN_TEST_INSTR)
select 362387880002201, 0, ID_TNT, 'MED-2026-W078-09', '布洛芬缓释片', 'Ibuprofen', SD_MED_TYPE, 'TABLET', PREP_SPEC, '片', QTY_STRNTH_VAL, STRNTH_UNIT, SD_STORAGE_TYPE, FG_RX_DRUG, FG_ESSNTL_DRUG, FG_ANTIMIC, SD_ANTIMIC_LEVEL, FG_SKIN_TEST_RQD, QTY_DEFAULT_DOSE, DEFAULT_DOSE_UNIT, DEFAULT_ROUTE, DEFAULT_FREQ, FG_CHRONIC_DISEASE_DRUG, FG_SINGLE_ORDER, SD_STATUS, DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED, ID_ITEM_TYPE, ID_ITEM_MASTER, ID_ORDER_FREQ_DEFAULT, ID_CONCEPT_DEFAULT_ROUTE, FG_ANTIMIC_OP, FG_ANTIMIC_CONSULT, FG_ANTIMIC_EMERG, QTY_ANTIMIC_MAX_DAYS, SD_SKIN_TEST_METHOD, SD_SKIN_TEST_SOLN_MODE, QTY_SKIN_TEST_OBS_MINUTES, QTY_SKIN_TEST_VALID_HOURS, DES_SKIN_TEST_INSTR
from RHN_BD_MED where ID_MED = 362387880000268 and not exists (select 1 from RHN_BD_MED where ID_MED = 362387880002201);

insert into RHN_BD_MED_WESTERN (ID_MED, ID_TNT, ACTIVE_INGR, SD_THERAP_CLASS, FG_BIOL, FG_BIOSIM)
select 362387880002201, ID_TNT, '布洛芬缓释片', SD_THERAP_CLASS, FG_BIOL, FG_BIOSIM
from RHN_BD_MED_WESTERN where ID_MED = 362387880000268 and not exists (select 1 from RHN_BD_MED_WESTERN where ID_MED = 362387880002201);

insert into RHN_BD_ITEM_ATTR_SUBJECT (ID_ITEM_ATTR_SUBJECT, ID_TNT, SD_SUBJECT_TYPE, CD_SUBJECT_KEY, ID_ITEM_MASTER, ID_MED, ID_CATALOG_ITEM, ID_SVC_VAR, DT_CREATED, ID_USER_CREATED)
select 362387880502201, ID_TNT, SD_SUBJECT_TYPE, 'TENANT:' || ID_TNT || '/MEDICATION:362387880002201', ID_ITEM_MASTER, 362387880002201, ID_CATALOG_ITEM, ID_SVC_VAR, DT_CREATED, ID_USER_CREATED
from RHN_BD_ITEM_ATTR_SUBJECT where ID_MED = 362387880000268 and not exists (select 1 from RHN_BD_ITEM_ATTR_SUBJECT where ID_ITEM_ATTR_SUBJECT = 362387880502201);

-- Govern MED-2026-W020-01: normalize capsule master and create tablet master (红霉素肠溶片)
update RHN_BD_MED set NA_MED = '红霉素肠溶胶囊', NA_ALIAS = 'Erythromycin', DOSE_FORM = 'CAPSULE', PREP_UNIT = '粒' where ID_MED = 362387880000087;
update RHN_BD_MED_WESTERN set ACTIVE_INGR = '红霉素肠溶胶囊' where ID_MED = 362387880000087;

insert into RHN_BD_MED (ID_MED, REVISION, ID_TNT, CD_MED, NA_MED, NA_ALIAS, SD_MED_TYPE, DOSE_FORM, PREP_SPEC, PREP_UNIT, QTY_STRNTH_VAL, STRNTH_UNIT, SD_STORAGE_TYPE, FG_RX_DRUG, FG_ESSNTL_DRUG, FG_ANTIMIC, SD_ANTIMIC_LEVEL, FG_SKIN_TEST_RQD, QTY_DEFAULT_DOSE, DEFAULT_DOSE_UNIT, DEFAULT_ROUTE, DEFAULT_FREQ, FG_CHRONIC_DISEASE_DRUG, FG_SINGLE_ORDER, SD_STATUS, DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED, ID_ITEM_TYPE, ID_ITEM_MASTER, ID_ORDER_FREQ_DEFAULT, ID_CONCEPT_DEFAULT_ROUTE, FG_ANTIMIC_OP, FG_ANTIMIC_CONSULT, FG_ANTIMIC_EMERG, QTY_ANTIMIC_MAX_DAYS, SD_SKIN_TEST_METHOD, SD_SKIN_TEST_SOLN_MODE, QTY_SKIN_TEST_OBS_MINUTES, QTY_SKIN_TEST_VALID_HOURS, DES_SKIN_TEST_INSTR)
select 362387880002202, 0, ID_TNT, 'MED-2026-W020-10', '红霉素肠溶片', 'Erythromycin', SD_MED_TYPE, 'TABLET', PREP_SPEC, '片', QTY_STRNTH_VAL, STRNTH_UNIT, SD_STORAGE_TYPE, FG_RX_DRUG, FG_ESSNTL_DRUG, FG_ANTIMIC, SD_ANTIMIC_LEVEL, FG_SKIN_TEST_RQD, QTY_DEFAULT_DOSE, DEFAULT_DOSE_UNIT, DEFAULT_ROUTE, DEFAULT_FREQ, FG_CHRONIC_DISEASE_DRUG, FG_SINGLE_ORDER, SD_STATUS, DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED, ID_ITEM_TYPE, ID_ITEM_MASTER, ID_ORDER_FREQ_DEFAULT, ID_CONCEPT_DEFAULT_ROUTE, FG_ANTIMIC_OP, FG_ANTIMIC_CONSULT, FG_ANTIMIC_EMERG, QTY_ANTIMIC_MAX_DAYS, SD_SKIN_TEST_METHOD, SD_SKIN_TEST_SOLN_MODE, QTY_SKIN_TEST_OBS_MINUTES, QTY_SKIN_TEST_VALID_HOURS, DES_SKIN_TEST_INSTR
from RHN_BD_MED where ID_MED = 362387880000087 and not exists (select 1 from RHN_BD_MED where ID_MED = 362387880002202);

insert into RHN_BD_MED_WESTERN (ID_MED, ID_TNT, ACTIVE_INGR, SD_THERAP_CLASS, FG_BIOL, FG_BIOSIM)
select 362387880002202, ID_TNT, '红霉素肠溶片', SD_THERAP_CLASS, FG_BIOL, FG_BIOSIM
from RHN_BD_MED_WESTERN where ID_MED = 362387880000087 and not exists (select 1 from RHN_BD_MED_WESTERN where ID_MED = 362387880002202);

insert into RHN_BD_ITEM_ATTR_SUBJECT (ID_ITEM_ATTR_SUBJECT, ID_TNT, SD_SUBJECT_TYPE, CD_SUBJECT_KEY, ID_ITEM_MASTER, ID_MED, ID_CATALOG_ITEM, ID_SVC_VAR, DT_CREATED, ID_USER_CREATED)
select 362387880502202, ID_TNT, SD_SUBJECT_TYPE, 'TENANT:' || ID_TNT || '/MEDICATION:362387880002202', ID_ITEM_MASTER, 362387880002202, ID_CATALOG_ITEM, ID_SVC_VAR, DT_CREATED, ID_USER_CREATED
from RHN_BD_ITEM_ATTR_SUBJECT where ID_MED = 362387880000087 and not exists (select 1 from RHN_BD_ITEM_ATTR_SUBJECT where ID_ITEM_ATTR_SUBJECT = 362387880502202);

-- Govern MED-2026-W020-02: normalize capsule master and create tablet master (红霉素肠溶片)
update RHN_BD_MED set NA_MED = '红霉素肠溶胶囊', NA_ALIAS = 'Erythromycin', DOSE_FORM = 'CAPSULE', PREP_UNIT = '粒' where ID_MED = 362387880000088;
update RHN_BD_MED_WESTERN set ACTIVE_INGR = '红霉素肠溶胶囊' where ID_MED = 362387880000088;

insert into RHN_BD_MED (ID_MED, REVISION, ID_TNT, CD_MED, NA_MED, NA_ALIAS, SD_MED_TYPE, DOSE_FORM, PREP_SPEC, PREP_UNIT, QTY_STRNTH_VAL, STRNTH_UNIT, SD_STORAGE_TYPE, FG_RX_DRUG, FG_ESSNTL_DRUG, FG_ANTIMIC, SD_ANTIMIC_LEVEL, FG_SKIN_TEST_RQD, QTY_DEFAULT_DOSE, DEFAULT_DOSE_UNIT, DEFAULT_ROUTE, DEFAULT_FREQ, FG_CHRONIC_DISEASE_DRUG, FG_SINGLE_ORDER, SD_STATUS, DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED, ID_ITEM_TYPE, ID_ITEM_MASTER, ID_ORDER_FREQ_DEFAULT, ID_CONCEPT_DEFAULT_ROUTE, FG_ANTIMIC_OP, FG_ANTIMIC_CONSULT, FG_ANTIMIC_EMERG, QTY_ANTIMIC_MAX_DAYS, SD_SKIN_TEST_METHOD, SD_SKIN_TEST_SOLN_MODE, QTY_SKIN_TEST_OBS_MINUTES, QTY_SKIN_TEST_VALID_HOURS, DES_SKIN_TEST_INSTR)
select 362387880002203, 0, ID_TNT, 'MED-2026-W020-11', '红霉素肠溶片', 'Erythromycin', SD_MED_TYPE, 'TABLET', PREP_SPEC, '片', QTY_STRNTH_VAL, STRNTH_UNIT, SD_STORAGE_TYPE, FG_RX_DRUG, FG_ESSNTL_DRUG, FG_ANTIMIC, SD_ANTIMIC_LEVEL, FG_SKIN_TEST_RQD, QTY_DEFAULT_DOSE, DEFAULT_DOSE_UNIT, DEFAULT_ROUTE, DEFAULT_FREQ, FG_CHRONIC_DISEASE_DRUG, FG_SINGLE_ORDER, SD_STATUS, DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED, ID_ITEM_TYPE, ID_ITEM_MASTER, ID_ORDER_FREQ_DEFAULT, ID_CONCEPT_DEFAULT_ROUTE, FG_ANTIMIC_OP, FG_ANTIMIC_CONSULT, FG_ANTIMIC_EMERG, QTY_ANTIMIC_MAX_DAYS, SD_SKIN_TEST_METHOD, SD_SKIN_TEST_SOLN_MODE, QTY_SKIN_TEST_OBS_MINUTES, QTY_SKIN_TEST_VALID_HOURS, DES_SKIN_TEST_INSTR
from RHN_BD_MED where ID_MED = 362387880000088 and not exists (select 1 from RHN_BD_MED where ID_MED = 362387880002203);

insert into RHN_BD_MED_WESTERN (ID_MED, ID_TNT, ACTIVE_INGR, SD_THERAP_CLASS, FG_BIOL, FG_BIOSIM)
select 362387880002203, ID_TNT, '红霉素肠溶片', SD_THERAP_CLASS, FG_BIOL, FG_BIOSIM
from RHN_BD_MED_WESTERN where ID_MED = 362387880000088 and not exists (select 1 from RHN_BD_MED_WESTERN where ID_MED = 362387880002203);

insert into RHN_BD_ITEM_ATTR_SUBJECT (ID_ITEM_ATTR_SUBJECT, ID_TNT, SD_SUBJECT_TYPE, CD_SUBJECT_KEY, ID_ITEM_MASTER, ID_MED, ID_CATALOG_ITEM, ID_SVC_VAR, DT_CREATED, ID_USER_CREATED)
select 362387880502203, ID_TNT, SD_SUBJECT_TYPE, 'TENANT:' || ID_TNT || '/MEDICATION:362387880002203', ID_ITEM_MASTER, 362387880002203, ID_CATALOG_ITEM, ID_SVC_VAR, DT_CREATED, ID_USER_CREATED
from RHN_BD_ITEM_ATTR_SUBJECT where ID_MED = 362387880000088 and not exists (select 1 from RHN_BD_ITEM_ATTR_SUBJECT where ID_ITEM_ATTR_SUBJECT = 362387880502203);

-- Govern MED-2026-W189-01: normalize capsule master and create tablet master (乌拉地尔缓释片)
update RHN_BD_MED set NA_MED = '乌拉地尔缓释胶囊', NA_ALIAS = 'Urapidil', DOSE_FORM = 'CAPSULE', PREP_UNIT = '粒' where ID_MED = 362387880000588;
update RHN_BD_MED_WESTERN set ACTIVE_INGR = '乌拉地尔缓释胶囊' where ID_MED = 362387880000588;

insert into RHN_BD_MED (ID_MED, REVISION, ID_TNT, CD_MED, NA_MED, NA_ALIAS, SD_MED_TYPE, DOSE_FORM, PREP_SPEC, PREP_UNIT, QTY_STRNTH_VAL, STRNTH_UNIT, SD_STORAGE_TYPE, FG_RX_DRUG, FG_ESSNTL_DRUG, FG_ANTIMIC, SD_ANTIMIC_LEVEL, FG_SKIN_TEST_RQD, QTY_DEFAULT_DOSE, DEFAULT_DOSE_UNIT, DEFAULT_ROUTE, DEFAULT_FREQ, FG_CHRONIC_DISEASE_DRUG, FG_SINGLE_ORDER, SD_STATUS, DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED, ID_ITEM_TYPE, ID_ITEM_MASTER, ID_ORDER_FREQ_DEFAULT, ID_CONCEPT_DEFAULT_ROUTE, FG_ANTIMIC_OP, FG_ANTIMIC_CONSULT, FG_ANTIMIC_EMERG, QTY_ANTIMIC_MAX_DAYS, SD_SKIN_TEST_METHOD, SD_SKIN_TEST_SOLN_MODE, QTY_SKIN_TEST_OBS_MINUTES, QTY_SKIN_TEST_VALID_HOURS, DES_SKIN_TEST_INSTR)
select 362387880002204, 0, ID_TNT, 'MED-2026-W189-04', '乌拉地尔缓释片', 'Urapidil', SD_MED_TYPE, 'TABLET', PREP_SPEC, '片', QTY_STRNTH_VAL, STRNTH_UNIT, SD_STORAGE_TYPE, FG_RX_DRUG, FG_ESSNTL_DRUG, FG_ANTIMIC, SD_ANTIMIC_LEVEL, FG_SKIN_TEST_RQD, QTY_DEFAULT_DOSE, DEFAULT_DOSE_UNIT, DEFAULT_ROUTE, DEFAULT_FREQ, FG_CHRONIC_DISEASE_DRUG, FG_SINGLE_ORDER, SD_STATUS, DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED, ID_ITEM_TYPE, ID_ITEM_MASTER, ID_ORDER_FREQ_DEFAULT, ID_CONCEPT_DEFAULT_ROUTE, FG_ANTIMIC_OP, FG_ANTIMIC_CONSULT, FG_ANTIMIC_EMERG, QTY_ANTIMIC_MAX_DAYS, SD_SKIN_TEST_METHOD, SD_SKIN_TEST_SOLN_MODE, QTY_SKIN_TEST_OBS_MINUTES, QTY_SKIN_TEST_VALID_HOURS, DES_SKIN_TEST_INSTR
from RHN_BD_MED where ID_MED = 362387880000588 and not exists (select 1 from RHN_BD_MED where ID_MED = 362387880002204);

insert into RHN_BD_MED_WESTERN (ID_MED, ID_TNT, ACTIVE_INGR, SD_THERAP_CLASS, FG_BIOL, FG_BIOSIM)
select 362387880002204, ID_TNT, '乌拉地尔缓释片', SD_THERAP_CLASS, FG_BIOL, FG_BIOSIM
from RHN_BD_MED_WESTERN where ID_MED = 362387880000588 and not exists (select 1 from RHN_BD_MED_WESTERN where ID_MED = 362387880002204);

insert into RHN_BD_ITEM_ATTR_SUBJECT (ID_ITEM_ATTR_SUBJECT, ID_TNT, SD_SUBJECT_TYPE, CD_SUBJECT_KEY, ID_ITEM_MASTER, ID_MED, ID_CATALOG_ITEM, ID_SVC_VAR, DT_CREATED, ID_USER_CREATED)
select 362387880502204, ID_TNT, SD_SUBJECT_TYPE, 'TENANT:' || ID_TNT || '/MEDICATION:362387880002204', ID_ITEM_MASTER, 362387880002204, ID_CATALOG_ITEM, ID_SVC_VAR, DT_CREATED, ID_USER_CREATED
from RHN_BD_ITEM_ATTR_SUBJECT where ID_MED = 362387880000588 and not exists (select 1 from RHN_BD_ITEM_ATTR_SUBJECT where ID_ITEM_ATTR_SUBJECT = 362387880502204);

-- Govern MED-2026-W231-01: normalize capsule master and create tablet master (奥美拉唑肠溶片)
update RHN_BD_MED set NA_MED = '奥美拉唑肠溶胶囊', NA_ALIAS = 'Omeprazole', DOSE_FORM = 'CAPSULE', PREP_UNIT = '粒' where ID_MED = 362387880000709;
update RHN_BD_MED_WESTERN set ACTIVE_INGR = '奥美拉唑肠溶胶囊' where ID_MED = 362387880000709;

insert into RHN_BD_MED (ID_MED, REVISION, ID_TNT, CD_MED, NA_MED, NA_ALIAS, SD_MED_TYPE, DOSE_FORM, PREP_SPEC, PREP_UNIT, QTY_STRNTH_VAL, STRNTH_UNIT, SD_STORAGE_TYPE, FG_RX_DRUG, FG_ESSNTL_DRUG, FG_ANTIMIC, SD_ANTIMIC_LEVEL, FG_SKIN_TEST_RQD, QTY_DEFAULT_DOSE, DEFAULT_DOSE_UNIT, DEFAULT_ROUTE, DEFAULT_FREQ, FG_CHRONIC_DISEASE_DRUG, FG_SINGLE_ORDER, SD_STATUS, DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED, ID_ITEM_TYPE, ID_ITEM_MASTER, ID_ORDER_FREQ_DEFAULT, ID_CONCEPT_DEFAULT_ROUTE, FG_ANTIMIC_OP, FG_ANTIMIC_CONSULT, FG_ANTIMIC_EMERG, QTY_ANTIMIC_MAX_DAYS, SD_SKIN_TEST_METHOD, SD_SKIN_TEST_SOLN_MODE, QTY_SKIN_TEST_OBS_MINUTES, QTY_SKIN_TEST_VALID_HOURS, DES_SKIN_TEST_INSTR)
select 362387880002205, 0, ID_TNT, 'MED-2026-W231-04', '奥美拉唑肠溶片', 'Omeprazole', SD_MED_TYPE, 'TABLET', PREP_SPEC, '片', QTY_STRNTH_VAL, STRNTH_UNIT, SD_STORAGE_TYPE, FG_RX_DRUG, FG_ESSNTL_DRUG, FG_ANTIMIC, SD_ANTIMIC_LEVEL, FG_SKIN_TEST_RQD, QTY_DEFAULT_DOSE, DEFAULT_DOSE_UNIT, DEFAULT_ROUTE, DEFAULT_FREQ, FG_CHRONIC_DISEASE_DRUG, FG_SINGLE_ORDER, SD_STATUS, DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED, ID_ITEM_TYPE, ID_ITEM_MASTER, ID_ORDER_FREQ_DEFAULT, ID_CONCEPT_DEFAULT_ROUTE, FG_ANTIMIC_OP, FG_ANTIMIC_CONSULT, FG_ANTIMIC_EMERG, QTY_ANTIMIC_MAX_DAYS, SD_SKIN_TEST_METHOD, SD_SKIN_TEST_SOLN_MODE, QTY_SKIN_TEST_OBS_MINUTES, QTY_SKIN_TEST_VALID_HOURS, DES_SKIN_TEST_INSTR
from RHN_BD_MED where ID_MED = 362387880000709 and not exists (select 1 from RHN_BD_MED where ID_MED = 362387880002205);

insert into RHN_BD_MED_WESTERN (ID_MED, ID_TNT, ACTIVE_INGR, SD_THERAP_CLASS, FG_BIOL, FG_BIOSIM)
select 362387880002205, ID_TNT, '奥美拉唑肠溶片', SD_THERAP_CLASS, FG_BIOL, FG_BIOSIM
from RHN_BD_MED_WESTERN where ID_MED = 362387880000709 and not exists (select 1 from RHN_BD_MED_WESTERN where ID_MED = 362387880002205);

insert into RHN_BD_ITEM_ATTR_SUBJECT (ID_ITEM_ATTR_SUBJECT, ID_TNT, SD_SUBJECT_TYPE, CD_SUBJECT_KEY, ID_ITEM_MASTER, ID_MED, ID_CATALOG_ITEM, ID_SVC_VAR, DT_CREATED, ID_USER_CREATED)
select 362387880502205, ID_TNT, SD_SUBJECT_TYPE, 'TENANT:' || ID_TNT || '/MEDICATION:362387880002205', ID_ITEM_MASTER, 362387880002205, ID_CATALOG_ITEM, ID_SVC_VAR, DT_CREATED, ID_USER_CREATED
from RHN_BD_ITEM_ATTR_SUBJECT where ID_MED = 362387880000709 and not exists (select 1 from RHN_BD_ITEM_ATTR_SUBJECT where ID_ITEM_ATTR_SUBJECT = 362387880502205);

-- Govern MED-2026-W231-02: normalize capsule master and create tablet master (奥美拉唑肠溶片)
update RHN_BD_MED set NA_MED = '奥美拉唑肠溶胶囊', NA_ALIAS = 'Omeprazole', DOSE_FORM = 'CAPSULE', PREP_UNIT = '粒' where ID_MED = 362387880000710;
update RHN_BD_MED_WESTERN set ACTIVE_INGR = '奥美拉唑肠溶胶囊' where ID_MED = 362387880000710;

insert into RHN_BD_MED (ID_MED, REVISION, ID_TNT, CD_MED, NA_MED, NA_ALIAS, SD_MED_TYPE, DOSE_FORM, PREP_SPEC, PREP_UNIT, QTY_STRNTH_VAL, STRNTH_UNIT, SD_STORAGE_TYPE, FG_RX_DRUG, FG_ESSNTL_DRUG, FG_ANTIMIC, SD_ANTIMIC_LEVEL, FG_SKIN_TEST_RQD, QTY_DEFAULT_DOSE, DEFAULT_DOSE_UNIT, DEFAULT_ROUTE, DEFAULT_FREQ, FG_CHRONIC_DISEASE_DRUG, FG_SINGLE_ORDER, SD_STATUS, DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED, ID_ITEM_TYPE, ID_ITEM_MASTER, ID_ORDER_FREQ_DEFAULT, ID_CONCEPT_DEFAULT_ROUTE, FG_ANTIMIC_OP, FG_ANTIMIC_CONSULT, FG_ANTIMIC_EMERG, QTY_ANTIMIC_MAX_DAYS, SD_SKIN_TEST_METHOD, SD_SKIN_TEST_SOLN_MODE, QTY_SKIN_TEST_OBS_MINUTES, QTY_SKIN_TEST_VALID_HOURS, DES_SKIN_TEST_INSTR)
select 362387880002206, 0, ID_TNT, 'MED-2026-W231-05', '奥美拉唑肠溶片', 'Omeprazole', SD_MED_TYPE, 'TABLET', PREP_SPEC, '片', QTY_STRNTH_VAL, STRNTH_UNIT, SD_STORAGE_TYPE, FG_RX_DRUG, FG_ESSNTL_DRUG, FG_ANTIMIC, SD_ANTIMIC_LEVEL, FG_SKIN_TEST_RQD, QTY_DEFAULT_DOSE, DEFAULT_DOSE_UNIT, DEFAULT_ROUTE, DEFAULT_FREQ, FG_CHRONIC_DISEASE_DRUG, FG_SINGLE_ORDER, SD_STATUS, DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED, ID_ITEM_TYPE, ID_ITEM_MASTER, ID_ORDER_FREQ_DEFAULT, ID_CONCEPT_DEFAULT_ROUTE, FG_ANTIMIC_OP, FG_ANTIMIC_CONSULT, FG_ANTIMIC_EMERG, QTY_ANTIMIC_MAX_DAYS, SD_SKIN_TEST_METHOD, SD_SKIN_TEST_SOLN_MODE, QTY_SKIN_TEST_OBS_MINUTES, QTY_SKIN_TEST_VALID_HOURS, DES_SKIN_TEST_INSTR
from RHN_BD_MED where ID_MED = 362387880000710 and not exists (select 1 from RHN_BD_MED where ID_MED = 362387880002206);

insert into RHN_BD_MED_WESTERN (ID_MED, ID_TNT, ACTIVE_INGR, SD_THERAP_CLASS, FG_BIOL, FG_BIOSIM)
select 362387880002206, ID_TNT, '奥美拉唑肠溶片', SD_THERAP_CLASS, FG_BIOL, FG_BIOSIM
from RHN_BD_MED_WESTERN where ID_MED = 362387880000710 and not exists (select 1 from RHN_BD_MED_WESTERN where ID_MED = 362387880002206);

insert into RHN_BD_ITEM_ATTR_SUBJECT (ID_ITEM_ATTR_SUBJECT, ID_TNT, SD_SUBJECT_TYPE, CD_SUBJECT_KEY, ID_ITEM_MASTER, ID_MED, ID_CATALOG_ITEM, ID_SVC_VAR, DT_CREATED, ID_USER_CREATED)
select 362387880502206, ID_TNT, SD_SUBJECT_TYPE, 'TENANT:' || ID_TNT || '/MEDICATION:362387880002206', ID_ITEM_MASTER, 362387880002206, ID_CATALOG_ITEM, ID_SVC_VAR, DT_CREATED, ID_USER_CREATED
from RHN_BD_ITEM_ATTR_SUBJECT where ID_MED = 362387880000710 and not exists (select 1 from RHN_BD_ITEM_ATTR_SUBJECT where ID_ITEM_ATTR_SUBJECT = 362387880502206);

-- Govern MED-2026-W232-01: normalize capsule master and create tablet master (艾司奥美拉唑肠溶片)
update RHN_BD_MED set NA_MED = '艾司奥美拉唑肠溶胶囊', NA_ALIAS = 'Esomeprazole', DOSE_FORM = 'CAPSULE', PREP_UNIT = '粒' where ID_MED = 362387880000712;
update RHN_BD_MED_WESTERN set ACTIVE_INGR = '艾司奥美拉唑肠溶胶囊' where ID_MED = 362387880000712;

insert into RHN_BD_MED (ID_MED, REVISION, ID_TNT, CD_MED, NA_MED, NA_ALIAS, SD_MED_TYPE, DOSE_FORM, PREP_SPEC, PREP_UNIT, QTY_STRNTH_VAL, STRNTH_UNIT, SD_STORAGE_TYPE, FG_RX_DRUG, FG_ESSNTL_DRUG, FG_ANTIMIC, SD_ANTIMIC_LEVEL, FG_SKIN_TEST_RQD, QTY_DEFAULT_DOSE, DEFAULT_DOSE_UNIT, DEFAULT_ROUTE, DEFAULT_FREQ, FG_CHRONIC_DISEASE_DRUG, FG_SINGLE_ORDER, SD_STATUS, DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED, ID_ITEM_TYPE, ID_ITEM_MASTER, ID_ORDER_FREQ_DEFAULT, ID_CONCEPT_DEFAULT_ROUTE, FG_ANTIMIC_OP, FG_ANTIMIC_CONSULT, FG_ANTIMIC_EMERG, QTY_ANTIMIC_MAX_DAYS, SD_SKIN_TEST_METHOD, SD_SKIN_TEST_SOLN_MODE, QTY_SKIN_TEST_OBS_MINUTES, QTY_SKIN_TEST_VALID_HOURS, DES_SKIN_TEST_INSTR)
select 362387880002207, 0, ID_TNT, 'MED-2026-W232-06', '艾司奥美拉唑肠溶片', 'Esomeprazole', SD_MED_TYPE, 'TABLET', PREP_SPEC, '片', QTY_STRNTH_VAL, STRNTH_UNIT, SD_STORAGE_TYPE, FG_RX_DRUG, FG_ESSNTL_DRUG, FG_ANTIMIC, SD_ANTIMIC_LEVEL, FG_SKIN_TEST_RQD, QTY_DEFAULT_DOSE, DEFAULT_DOSE_UNIT, DEFAULT_ROUTE, DEFAULT_FREQ, FG_CHRONIC_DISEASE_DRUG, FG_SINGLE_ORDER, SD_STATUS, DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED, ID_ITEM_TYPE, ID_ITEM_MASTER, ID_ORDER_FREQ_DEFAULT, ID_CONCEPT_DEFAULT_ROUTE, FG_ANTIMIC_OP, FG_ANTIMIC_CONSULT, FG_ANTIMIC_EMERG, QTY_ANTIMIC_MAX_DAYS, SD_SKIN_TEST_METHOD, SD_SKIN_TEST_SOLN_MODE, QTY_SKIN_TEST_OBS_MINUTES, QTY_SKIN_TEST_VALID_HOURS, DES_SKIN_TEST_INSTR
from RHN_BD_MED where ID_MED = 362387880000712 and not exists (select 1 from RHN_BD_MED where ID_MED = 362387880002207);

insert into RHN_BD_MED_WESTERN (ID_MED, ID_TNT, ACTIVE_INGR, SD_THERAP_CLASS, FG_BIOL, FG_BIOSIM)
select 362387880002207, ID_TNT, '艾司奥美拉唑肠溶片', SD_THERAP_CLASS, FG_BIOL, FG_BIOSIM
from RHN_BD_MED_WESTERN where ID_MED = 362387880000712 and not exists (select 1 from RHN_BD_MED_WESTERN where ID_MED = 362387880002207);

insert into RHN_BD_ITEM_ATTR_SUBJECT (ID_ITEM_ATTR_SUBJECT, ID_TNT, SD_SUBJECT_TYPE, CD_SUBJECT_KEY, ID_ITEM_MASTER, ID_MED, ID_CATALOG_ITEM, ID_SVC_VAR, DT_CREATED, ID_USER_CREATED)
select 362387880502207, ID_TNT, SD_SUBJECT_TYPE, 'TENANT:' || ID_TNT || '/MEDICATION:362387880002207', ID_ITEM_MASTER, 362387880002207, ID_CATALOG_ITEM, ID_SVC_VAR, DT_CREATED, ID_USER_CREATED
from RHN_BD_ITEM_ATTR_SUBJECT where ID_MED = 362387880000712 and not exists (select 1 from RHN_BD_ITEM_ATTR_SUBJECT where ID_ITEM_ATTR_SUBJECT = 362387880502207);

-- Govern MED-2026-W315-03: normalize capsule master and create tablet master (二甲双胍肠溶片)
update RHN_BD_MED set NA_MED = '二甲双胍肠溶胶囊', NA_ALIAS = 'Metformin', DOSE_FORM = 'CAPSULE', PREP_UNIT = '粒' where ID_MED = 362387880000906;
update RHN_BD_MED_WESTERN set ACTIVE_INGR = '二甲双胍肠溶胶囊' where ID_MED = 362387880000906;

insert into RHN_BD_MED (ID_MED, REVISION, ID_TNT, CD_MED, NA_MED, NA_ALIAS, SD_MED_TYPE, DOSE_FORM, PREP_SPEC, PREP_UNIT, QTY_STRNTH_VAL, STRNTH_UNIT, SD_STORAGE_TYPE, FG_RX_DRUG, FG_ESSNTL_DRUG, FG_ANTIMIC, SD_ANTIMIC_LEVEL, FG_SKIN_TEST_RQD, QTY_DEFAULT_DOSE, DEFAULT_DOSE_UNIT, DEFAULT_ROUTE, DEFAULT_FREQ, FG_CHRONIC_DISEASE_DRUG, FG_SINGLE_ORDER, SD_STATUS, DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED, ID_ITEM_TYPE, ID_ITEM_MASTER, ID_ORDER_FREQ_DEFAULT, ID_CONCEPT_DEFAULT_ROUTE, FG_ANTIMIC_OP, FG_ANTIMIC_CONSULT, FG_ANTIMIC_EMERG, QTY_ANTIMIC_MAX_DAYS, SD_SKIN_TEST_METHOD, SD_SKIN_TEST_SOLN_MODE, QTY_SKIN_TEST_OBS_MINUTES, QTY_SKIN_TEST_VALID_HOURS, DES_SKIN_TEST_INSTR)
select 362387880002208, 0, ID_TNT, 'MED-2026-W315-09', '二甲双胍肠溶片', 'Metformin', SD_MED_TYPE, 'TABLET', PREP_SPEC, '片', QTY_STRNTH_VAL, STRNTH_UNIT, SD_STORAGE_TYPE, FG_RX_DRUG, FG_ESSNTL_DRUG, FG_ANTIMIC, SD_ANTIMIC_LEVEL, FG_SKIN_TEST_RQD, QTY_DEFAULT_DOSE, DEFAULT_DOSE_UNIT, DEFAULT_ROUTE, DEFAULT_FREQ, FG_CHRONIC_DISEASE_DRUG, FG_SINGLE_ORDER, SD_STATUS, DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED, ID_ITEM_TYPE, ID_ITEM_MASTER, ID_ORDER_FREQ_DEFAULT, ID_CONCEPT_DEFAULT_ROUTE, FG_ANTIMIC_OP, FG_ANTIMIC_CONSULT, FG_ANTIMIC_EMERG, QTY_ANTIMIC_MAX_DAYS, SD_SKIN_TEST_METHOD, SD_SKIN_TEST_SOLN_MODE, QTY_SKIN_TEST_OBS_MINUTES, QTY_SKIN_TEST_VALID_HOURS, DES_SKIN_TEST_INSTR
from RHN_BD_MED where ID_MED = 362387880000906 and not exists (select 1 from RHN_BD_MED where ID_MED = 362387880002208);

insert into RHN_BD_MED_WESTERN (ID_MED, ID_TNT, ACTIVE_INGR, SD_THERAP_CLASS, FG_BIOL, FG_BIOSIM)
select 362387880002208, ID_TNT, '二甲双胍肠溶片', SD_THERAP_CLASS, FG_BIOL, FG_BIOSIM
from RHN_BD_MED_WESTERN where ID_MED = 362387880000906 and not exists (select 1 from RHN_BD_MED_WESTERN where ID_MED = 362387880002208);

insert into RHN_BD_ITEM_ATTR_SUBJECT (ID_ITEM_ATTR_SUBJECT, ID_TNT, SD_SUBJECT_TYPE, CD_SUBJECT_KEY, ID_ITEM_MASTER, ID_MED, ID_CATALOG_ITEM, ID_SVC_VAR, DT_CREATED, ID_USER_CREATED)
select 362387880502208, ID_TNT, SD_SUBJECT_TYPE, 'TENANT:' || ID_TNT || '/MEDICATION:362387880002208', ID_ITEM_MASTER, 362387880002208, ID_CATALOG_ITEM, ID_SVC_VAR, DT_CREATED, ID_USER_CREATED
from RHN_BD_ITEM_ATTR_SUBJECT where ID_MED = 362387880000906 and not exists (select 1 from RHN_BD_ITEM_ATTR_SUBJECT where ID_ITEM_ATTR_SUBJECT = 362387880502208);

-- Govern MED-2026-W315-04: normalize capsule master and create tablet master (二甲双胍肠溶片)
update RHN_BD_MED set NA_MED = '二甲双胍肠溶胶囊', NA_ALIAS = 'Metformin', DOSE_FORM = 'CAPSULE', PREP_UNIT = '粒' where ID_MED = 362387880000907;
update RHN_BD_MED_WESTERN set ACTIVE_INGR = '二甲双胍肠溶胶囊' where ID_MED = 362387880000907;

insert into RHN_BD_MED (ID_MED, REVISION, ID_TNT, CD_MED, NA_MED, NA_ALIAS, SD_MED_TYPE, DOSE_FORM, PREP_SPEC, PREP_UNIT, QTY_STRNTH_VAL, STRNTH_UNIT, SD_STORAGE_TYPE, FG_RX_DRUG, FG_ESSNTL_DRUG, FG_ANTIMIC, SD_ANTIMIC_LEVEL, FG_SKIN_TEST_RQD, QTY_DEFAULT_DOSE, DEFAULT_DOSE_UNIT, DEFAULT_ROUTE, DEFAULT_FREQ, FG_CHRONIC_DISEASE_DRUG, FG_SINGLE_ORDER, SD_STATUS, DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED, ID_ITEM_TYPE, ID_ITEM_MASTER, ID_ORDER_FREQ_DEFAULT, ID_CONCEPT_DEFAULT_ROUTE, FG_ANTIMIC_OP, FG_ANTIMIC_CONSULT, FG_ANTIMIC_EMERG, QTY_ANTIMIC_MAX_DAYS, SD_SKIN_TEST_METHOD, SD_SKIN_TEST_SOLN_MODE, QTY_SKIN_TEST_OBS_MINUTES, QTY_SKIN_TEST_VALID_HOURS, DES_SKIN_TEST_INSTR)
select 362387880002209, 0, ID_TNT, 'MED-2026-W315-10', '二甲双胍肠溶片', 'Metformin', SD_MED_TYPE, 'TABLET', PREP_SPEC, '片', QTY_STRNTH_VAL, STRNTH_UNIT, SD_STORAGE_TYPE, FG_RX_DRUG, FG_ESSNTL_DRUG, FG_ANTIMIC, SD_ANTIMIC_LEVEL, FG_SKIN_TEST_RQD, QTY_DEFAULT_DOSE, DEFAULT_DOSE_UNIT, DEFAULT_ROUTE, DEFAULT_FREQ, FG_CHRONIC_DISEASE_DRUG, FG_SINGLE_ORDER, SD_STATUS, DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED, ID_ITEM_TYPE, ID_ITEM_MASTER, ID_ORDER_FREQ_DEFAULT, ID_CONCEPT_DEFAULT_ROUTE, FG_ANTIMIC_OP, FG_ANTIMIC_CONSULT, FG_ANTIMIC_EMERG, QTY_ANTIMIC_MAX_DAYS, SD_SKIN_TEST_METHOD, SD_SKIN_TEST_SOLN_MODE, QTY_SKIN_TEST_OBS_MINUTES, QTY_SKIN_TEST_VALID_HOURS, DES_SKIN_TEST_INSTR
from RHN_BD_MED where ID_MED = 362387880000907 and not exists (select 1 from RHN_BD_MED where ID_MED = 362387880002209);

insert into RHN_BD_MED_WESTERN (ID_MED, ID_TNT, ACTIVE_INGR, SD_THERAP_CLASS, FG_BIOL, FG_BIOSIM)
select 362387880002209, ID_TNT, '二甲双胍肠溶片', SD_THERAP_CLASS, FG_BIOL, FG_BIOSIM
from RHN_BD_MED_WESTERN where ID_MED = 362387880000907 and not exists (select 1 from RHN_BD_MED_WESTERN where ID_MED = 362387880002209);

insert into RHN_BD_ITEM_ATTR_SUBJECT (ID_ITEM_ATTR_SUBJECT, ID_TNT, SD_SUBJECT_TYPE, CD_SUBJECT_KEY, ID_ITEM_MASTER, ID_MED, ID_CATALOG_ITEM, ID_SVC_VAR, DT_CREATED, ID_USER_CREATED)
select 362387880502209, ID_TNT, SD_SUBJECT_TYPE, 'TENANT:' || ID_TNT || '/MEDICATION:362387880002209', ID_ITEM_MASTER, 362387880002209, ID_CATALOG_ITEM, ID_SVC_VAR, DT_CREATED, ID_USER_CREATED
from RHN_BD_ITEM_ATTR_SUBJECT where ID_MED = 362387880000907 and not exists (select 1 from RHN_BD_ITEM_ATTR_SUBJECT where ID_ITEM_ATTR_SUBJECT = 362387880502209);

-- 2. Item aliases for chest radiography (DEMO-EXAM-CHEST-DR) when present
insert into RHN_BD_ITEM_ALIAS
    (ID_ITEM_ALIAS, ID_TNT, ID_CATALOG_ITEM, SD_ALIAS_TYPE, NA_ALIAS,
     CD_PINYIN, CD_WUBI, CD_MNEM, FG_PRIMARY_ALIAS, SD_STATUS)
select 362387895000003, 362387869790209, 362387871000203, 'SYNONYM', '胸部X线摄片',
       'XBXXSP', null, null, false, 'ACTIVE'
where exists (select 1 from RHN_BD_CATALOG_ITEM where ID_CATALOG_ITEM = 362387871000203)
  and not exists (select 1 from RHN_BD_ITEM_ALIAS where ID_ITEM_ALIAS = 362387895000003);

insert into RHN_BD_SEARCH_ENTRY
    (ID_SEARCH_ENTRY, REVISION, SD_SCOPE_TYPE, ID_SCOPE, ID_TNT, SD_TARGET_TYPE, ID_TARGET,
     SD_NAME_TYPE, CD_SOURCE_KEY, NA_SEARCH, CD_PINYIN, CD_WUBI, CD_MNEM, FG_PRIMARY,
     CD_GEN_VER, SD_STATUS, DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED)
select 362387895000003, 0, 'TENANT', 362387869790209, 362387869790209, 'CATALOG_ITEM',
       362387871000203, 'ALIAS', 'ITEM_ALIAS:362387895000003', '胸部X线摄片', 'XBXXSP', null, null,
       false, 'search-code-v1', 'ACTIVE', current_timestamp, null, current_timestamp, null
where exists (select 1 from RHN_BD_CATALOG_ITEM where ID_CATALOG_ITEM = 362387871000203)
  and not exists (select 1 from RHN_BD_SEARCH_ENTRY where ID_SEARCH_ENTRY = 362387895000003);

insert into RHN_BD_ITEM_ALIAS
    (ID_ITEM_ALIAS, ID_TNT, ID_CATALOG_ITEM, SD_ALIAS_TYPE, NA_ALIAS,
     CD_PINYIN, CD_WUBI, CD_MNEM, FG_PRIMARY_ALIAS, SD_STATUS)
select 362387895000004, 362387869790209, 362387871000203, 'SYNONYM', '胸部DR',
       'XBDR', null, null, false, 'ACTIVE'
where exists (select 1 from RHN_BD_CATALOG_ITEM where ID_CATALOG_ITEM = 362387871000203)
  and not exists (select 1 from RHN_BD_ITEM_ALIAS where ID_ITEM_ALIAS = 362387895000004);

insert into RHN_BD_SEARCH_ENTRY
    (ID_SEARCH_ENTRY, REVISION, SD_SCOPE_TYPE, ID_SCOPE, ID_TNT, SD_TARGET_TYPE, ID_TARGET,
     SD_NAME_TYPE, CD_SOURCE_KEY, NA_SEARCH, CD_PINYIN, CD_WUBI, CD_MNEM, FG_PRIMARY,
     CD_GEN_VER, SD_STATUS, DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED)
select 362387895000004, 0, 'TENANT', 362387869790209, 362387869790209, 'CATALOG_ITEM',
       362387871000203, 'ALIAS', 'ITEM_ALIAS:362387895000004', '胸部DR', 'XBDR', null, null,
       false, 'search-code-v1', 'ACTIVE', current_timestamp, null, current_timestamp, null
where exists (select 1 from RHN_BD_CATALOG_ITEM where ID_CATALOG_ITEM = 362387871000203)
  and not exists (select 1 from RHN_BD_SEARCH_ENTRY where ID_SEARCH_ENTRY = 362387895000004);

insert into RHN_BD_ITEM_ALIAS
    (ID_ITEM_ALIAS, ID_TNT, ID_CATALOG_ITEM, SD_ALIAS_TYPE, NA_ALIAS,
     CD_PINYIN, CD_WUBI, CD_MNEM, FG_PRIMARY_ALIAS, SD_STATUS)
select 362387895000005, 362387869790209, 362387871000203, 'SYNONYM', '胸片',
       'XP', null, null, false, 'ACTIVE'
where exists (select 1 from RHN_BD_CATALOG_ITEM where ID_CATALOG_ITEM = 362387871000203)
  and not exists (select 1 from RHN_BD_ITEM_ALIAS where ID_ITEM_ALIAS = 362387895000005);

insert into RHN_BD_SEARCH_ENTRY
    (ID_SEARCH_ENTRY, REVISION, SD_SCOPE_TYPE, ID_SCOPE, ID_TNT, SD_TARGET_TYPE, ID_TARGET,
     SD_NAME_TYPE, CD_SOURCE_KEY, NA_SEARCH, CD_PINYIN, CD_WUBI, CD_MNEM, FG_PRIMARY,
     CD_GEN_VER, SD_STATUS, DT_CREATED, ID_USER_CREATED, DT_UPDATED, ID_USER_UPDATED)
select 362387895000005, 0, 'TENANT', 362387869790209, 362387869790209, 'CATALOG_ITEM',
       362387871000203, 'ALIAS', 'ITEM_ALIAS:362387895000005', '胸片', 'XP', null, null,
       false, 'search-code-v1', 'ACTIVE', current_timestamp, null, current_timestamp, null
where exists (select 1 from RHN_BD_CATALOG_ITEM where ID_CATALOG_ITEM = 362387871000203)
  and not exists (select 1 from RHN_BD_SEARCH_ENTRY where ID_SEARCH_ENTRY = 362387895000005);
