create table stock_bins (
    id bigint primary key,
    revision bigint default 0 not null,
    tenant_id bigint not null,
    stock_site_id bigint not null,
    parent_bin_id bigint,
    code varchar(64) not null,
    name varchar(200) not null,
    bin_type varchar(32) not null,
    stock_default varchar(32) not null,
    receive_allowed boolean not null,
    pick_allowed boolean not null,
    count_allowed boolean not null,
    sort_order int not null,
    active boolean not null,
    created_at timestamp with time zone not null,
    created_by bigint not null,
    constraint fk_stock_bin_tenant foreign key (tenant_id) references tenants(id),
    constraint fk_stock_bin_site foreign key (tenant_id, stock_site_id) references stock_sites(tenant_id, id),
    constraint uk_stock_bin_tenant_id unique (tenant_id, id),
    constraint uk_stock_bin_code unique (tenant_id, stock_site_id, code),
    constraint fk_stock_bin_parent foreign key (tenant_id, parent_bin_id) references stock_bins(tenant_id, id),
    constraint ck_stock_bin_type check (bin_type in ('ZONE', 'RACK', 'BIN', 'COUNTER', 'TRANSIT')),
    constraint ck_stock_bin_default check (stock_default in ('AVAILABLE', 'PENDING', 'QUARANTINE', 'DAMAGED', 'EXPIRED'))
);
create index idx_stock_bin_site on stock_bins (tenant_id, stock_site_id, active, sort_order);

create table stock_lots (
    id bigint primary key,
    revision bigint default 0 not null,
    tenant_id bigint not null,
    catalog_item_id bigint not null,
    package_id bigint not null,
    lot_no varchar(128) not null,
    production_date date,
    expiry_date date,
    approval_code_snapshot varchar(128),
    manufacturer_name_snapshot varchar(300),
    quality_status varchar(32) not null,
    quality_at timestamp with time zone not null,
    quality_user_id bigint not null,
    status varchar(32) not null,
    created_at timestamp with time zone not null,
    created_by bigint not null,
    constraint fk_stock_lot_tenant foreign key (tenant_id) references tenants(id),
    constraint fk_stock_lot_catalog foreign key (tenant_id, catalog_item_id) references catalog_items(tenant_id, id),
    constraint fk_stock_lot_package foreign key (tenant_id, package_id) references item_packages(tenant_id, id),
    constraint uk_stock_lot_tenant_id unique (tenant_id, id),
    constraint uk_stock_lot_business unique (tenant_id, catalog_item_id, package_id, lot_no),
    constraint ck_stock_lot_quality check (quality_status in ('PENDING', 'QUALIFIED', 'QUARANTINE', 'REJECTED', 'RECALLED')),
    constraint ck_stock_lot_status check (status in ('ACTIVE', 'CLOSED', 'RETIRED')),
    constraint ck_stock_lot_dates check (expiry_date is null or production_date is null or expiry_date >= production_date)
);
create index idx_stock_lot_issue on stock_lots (tenant_id, catalog_item_id, quality_status, status, expiry_date);

create table inventory_periods (
    id bigint primary key,
    revision bigint default 0 not null,
    tenant_id bigint not null,
    stock_site_id bigint not null,
    period_code varchar(32) not null,
    period_from date not null,
    period_to date not null,
    status varchar(32) not null,
    closed_at timestamp with time zone,
    closed_by bigint,
    description varchar(1000),
    created_at timestamp with time zone not null,
    created_by bigint not null,
    constraint fk_inv_period_tenant foreign key (tenant_id) references tenants(id),
    constraint fk_inv_period_site foreign key (tenant_id, stock_site_id) references stock_sites(tenant_id, id),
    constraint uk_inv_period_tenant_id unique (tenant_id, id),
    constraint uk_inv_period_code unique (tenant_id, stock_site_id, period_code),
    constraint ck_inv_period_status check (status in ('OPEN', 'CLOSING', 'CLOSED')),
    constraint ck_inv_period_dates check (period_to >= period_from)
);
create index idx_inv_period_open on inventory_periods (tenant_id, stock_site_id, status);

create table inventory_transactions (
    id bigint primary key,
    tenant_id bigint not null,
    inventory_period_id bigint not null,
    reverses_transaction_id bigint,
    transaction_no varchar(64) not null,
    request_code varchar(128) not null,
    transaction_type varchar(32) not null,
    source_type varchar(32) not null,
    source_code varchar(128) not null,
    occurred_at timestamp with time zone not null,
    posted_at timestamp with time zone not null,
    posted_by bigint not null,
    description varchar(1000),
    constraint fk_inv_txn_tenant foreign key (tenant_id) references tenants(id),
    constraint fk_inv_txn_period foreign key (tenant_id, inventory_period_id) references inventory_periods(tenant_id, id),
    constraint uk_inv_txn_tenant_id unique (tenant_id, id),
    constraint uk_inv_txn_no unique (tenant_id, transaction_no),
    constraint uk_inv_txn_request unique (tenant_id, request_code),
    constraint fk_inv_txn_reverses foreign key (tenant_id, reverses_transaction_id) references inventory_transactions(tenant_id, id),
    constraint ck_inv_txn_type check (transaction_type in ('RECEIPT', 'ISSUE', 'TRANSFER', 'COUNT', 'DISPENSE', 'RETURN', 'QUALITY', 'REVERSAL'))
);
create index idx_inv_txn_source on inventory_transactions (tenant_id, source_type, source_code);
create index idx_inv_txn_period on inventory_transactions (tenant_id, inventory_period_id, posted_at);

create table inventory_transaction_lines (
    id bigint primary key,
    tenant_id bigint not null,
    inventory_transaction_id bigint not null,
    sort_order int not null,
    stock_site_id bigint not null,
    stock_bin_id bigint not null,
    stock_item_id bigint not null,
    stock_lot_id bigint not null,
    package_id bigint not null,
    stock_status varchar(32) not null,
    operation_quantity decimal(28,8) not null,
    operation_unit_code varchar(64) not null,
    base_quantity_factor decimal(28,8) not null,
    quantity_delta decimal(28,8) not null,
    unit_cost decimal(24,6),
    amount_delta decimal(24,6),
    constraint fk_inv_line_tenant foreign key (tenant_id) references tenants(id),
    constraint fk_inv_line_txn foreign key (tenant_id, inventory_transaction_id) references inventory_transactions(tenant_id, id),
    constraint fk_inv_line_site foreign key (tenant_id, stock_site_id) references stock_sites(tenant_id, id),
    constraint fk_inv_line_bin foreign key (tenant_id, stock_bin_id) references stock_bins(tenant_id, id),
    constraint fk_inv_line_item foreign key (tenant_id, stock_item_id) references stock_items(tenant_id, id),
    constraint fk_inv_line_lot foreign key (tenant_id, stock_lot_id) references stock_lots(tenant_id, id),
    constraint fk_inv_line_package foreign key (tenant_id, package_id) references item_packages(tenant_id, id),
    constraint uk_inv_line_tenant_id unique (tenant_id, id),
    constraint uk_inv_line_order unique (tenant_id, inventory_transaction_id, sort_order),
    constraint ck_inv_line_status check (stock_status in ('AVAILABLE', 'PENDING', 'QUARANTINE', 'DAMAGED', 'EXPIRED')),
    constraint ck_inv_line_quantity check (operation_quantity > 0 and base_quantity_factor > 0 and quantity_delta <> 0)
);
create index idx_inv_line_balance on inventory_transaction_lines (tenant_id, stock_bin_id, stock_item_id, stock_lot_id, stock_status);

create table inventory_balances (
    id bigint primary key,
    revision bigint default 0 not null,
    tenant_id bigint not null,
    stock_site_id bigint not null,
    stock_bin_id bigint not null,
    stock_item_id bigint not null,
    stock_lot_id bigint not null,
    stock_status varchar(32) not null,
    base_unit_code varchar(64) not null,
    quantity_on_hand decimal(28,8) not null,
    quantity_reserved decimal(28,8) not null,
    quantity_frozen decimal(28,8) not null,
    quantity_available decimal(28,8) not null,
    average_unit_cost decimal(24,6),
    projected_at timestamp with time zone not null,
    constraint fk_inv_bal_tenant foreign key (tenant_id) references tenants(id),
    constraint fk_inv_bal_site foreign key (tenant_id, stock_site_id) references stock_sites(tenant_id, id),
    constraint fk_inv_bal_bin foreign key (tenant_id, stock_bin_id) references stock_bins(tenant_id, id),
    constraint fk_inv_bal_item foreign key (tenant_id, stock_item_id) references stock_items(tenant_id, id),
    constraint fk_inv_bal_lot foreign key (tenant_id, stock_lot_id) references stock_lots(tenant_id, id),
    constraint uk_inv_bal_tenant_id unique (tenant_id, id),
    constraint uk_inv_bal_dimension unique (tenant_id, stock_bin_id, stock_item_id, stock_lot_id, stock_status),
    constraint ck_inv_bal_status check (stock_status in ('AVAILABLE', 'PENDING', 'QUARANTINE', 'DAMAGED', 'EXPIRED')),
    constraint ck_inv_bal_quantities check (quantity_on_hand >= 0 and quantity_reserved >= 0 and quantity_frozen >= 0
        and quantity_available = quantity_on_hand - quantity_reserved - quantity_frozen and quantity_available >= 0)
);
create index idx_inv_bal_item on inventory_balances (tenant_id, stock_site_id, stock_item_id, stock_status, projected_at);

create table inventory_reservations (
    id bigint primary key,
    revision bigint default 0 not null,
    tenant_id bigint not null,
    stock_site_id bigint not null,
    stock_bin_id bigint not null,
    stock_item_id bigint not null,
    stock_lot_id bigint not null,
    request_id bigint not null,
    reservation_group_code varchar(128) not null,
    reservation_type varchar(32) not null,
    status varchar(32) not null,
    quantity_reserved decimal(28,8) not null,
    quantity_consumed decimal(28,8) not null,
    base_unit_code varchar(64) not null,
    created_at timestamp with time zone not null,
    created_by bigint not null,
    expires_at timestamp with time zone,
    consumed_at timestamp with time zone,
    consumed_by bigint,
    released_at timestamp with time zone,
    released_by bigint,
    release_reason varchar(1000),
    constraint fk_inv_rsv_tenant foreign key (tenant_id) references tenants(id),
    constraint fk_inv_rsv_site foreign key (tenant_id, stock_site_id) references stock_sites(tenant_id, id),
    constraint fk_inv_rsv_bin foreign key (tenant_id, stock_bin_id) references stock_bins(tenant_id, id),
    constraint fk_inv_rsv_item foreign key (tenant_id, stock_item_id) references stock_items(tenant_id, id),
    constraint fk_inv_rsv_lot foreign key (tenant_id, stock_lot_id) references stock_lots(tenant_id, id),
    constraint fk_inv_rsv_request foreign key (tenant_id, request_id) references care_requests(tenant_id, id),
    constraint uk_inv_rsv_tenant_id unique (tenant_id, id),
    constraint uk_inv_rsv_dimension unique (tenant_id, reservation_group_code, stock_bin_id, stock_item_id, stock_lot_id),
    constraint ck_inv_rsv_type check (reservation_type in ('ORDER', 'DISPENSE', 'TRANSFER', 'OTHER')),
    constraint ck_inv_rsv_status check (status in ('ACTIVE', 'PARTIAL', 'CONSUMED', 'RELEASED', 'EXPIRED')),
    constraint ck_inv_rsv_quantities check (quantity_reserved > 0 and quantity_consumed >= 0 and quantity_consumed <= quantity_reserved)
);
create index idx_inv_rsv_request on inventory_reservations (tenant_id, request_id, status);
create index idx_inv_rsv_expire on inventory_reservations (tenant_id, expires_at, status);
