create table suppliers (
    id bigint primary key,
    revision bigint default 0 not null,
    tenant_id bigint not null,
    organization_id bigint not null,
    code varchar(64) not null,
    name varchar(300) not null,
    unified_credit_code varchar(64),
    license_no varchar(128),
    license_valid_to date,
    contact_name varchar(100),
    contact_phone varchar(64),
    status varchar(32) not null,
    valid_from date not null,
    valid_to date,
    created_at timestamp with time zone not null,
    created_by bigint not null,
    updated_at timestamp with time zone not null,
    updated_by bigint not null,
    constraint fk_supplier_tenant foreign key (tenant_id) references tenants(id),
    constraint fk_supplier_org foreign key (tenant_id, organization_id) references organizations(tenant_id, id),
    constraint uk_supplier_tenant_id unique (tenant_id, id),
    constraint uk_supplier_code unique (tenant_id, organization_id, code),
    constraint ck_supplier_status check (status in ('ACTIVE', 'SUSPENDED', 'RETIRED')),
    constraint ck_supplier_validity check (valid_to is null or valid_to >= valid_from)
);
create index idx_supplier_active on suppliers (tenant_id, organization_id, status, license_valid_to);

create table supplier_supply_items (
    id bigint primary key,
    revision bigint default 0 not null,
    tenant_id bigint not null,
    supplier_id bigint not null,
    catalog_item_id bigint not null,
    package_id bigint not null,
    agreement_price decimal(24,6),
    tax_rate decimal(9,6),
    purchase_enabled boolean not null,
    valid_from date not null,
    valid_to date,
    created_at timestamp with time zone not null,
    created_by bigint not null,
    updated_at timestamp with time zone not null,
    updated_by bigint not null,
    constraint fk_supplier_item_tenant foreign key (tenant_id) references tenants(id),
    constraint fk_supplier_item_supplier foreign key (tenant_id, supplier_id) references suppliers(tenant_id, id),
    constraint fk_supplier_item_catalog foreign key (tenant_id, catalog_item_id) references catalog_items(tenant_id, id),
    constraint fk_supplier_item_package foreign key (tenant_id, package_id) references item_packages(tenant_id, id),
    constraint uk_supplier_item_tenant_id unique (tenant_id, id),
    constraint uk_supplier_item_business unique (tenant_id, supplier_id, catalog_item_id, package_id),
    constraint ck_supplier_item_price check (agreement_price is null or agreement_price >= 0),
    constraint ck_supplier_item_tax check (tax_rate is null or (tax_rate >= 0 and tax_rate <= 1)),
    constraint ck_supplier_item_validity check (valid_to is null or valid_to >= valid_from)
);
create index idx_supplier_item_catalog on supplier_supply_items (tenant_id, catalog_item_id, purchase_enabled, valid_to);

create table purchase_orders (
    id bigint primary key,
    revision bigint default 0 not null,
    tenant_id bigint not null,
    organization_id bigint not null,
    stock_site_id bigint not null,
    supplier_id bigint not null,
    order_no varchar(64) not null,
    request_code varchar(128) not null,
    status varchar(32) not null,
    order_date date not null,
    expected_date date,
    submitted_at timestamp with time zone,
    submitted_by bigint,
    approved_at timestamp with time zone,
    approved_by bigint,
    approval_reason varchar(1000),
    description varchar(1000),
    created_at timestamp with time zone not null,
    created_by bigint not null,
    updated_at timestamp with time zone not null,
    updated_by bigint not null,
    constraint fk_po_tenant foreign key (tenant_id) references tenants(id),
    constraint fk_po_org foreign key (tenant_id, organization_id) references organizations(tenant_id, id),
    constraint fk_po_site foreign key (tenant_id, stock_site_id) references stock_sites(tenant_id, id),
    constraint fk_po_supplier foreign key (tenant_id, supplier_id) references suppliers(tenant_id, id),
    constraint uk_po_tenant_id unique (tenant_id, id),
    constraint uk_po_no unique (tenant_id, order_no),
    constraint uk_po_request unique (tenant_id, request_code),
    constraint ck_po_status check (status in ('DRAFT', 'SUBMITTED', 'APPROVED', 'PARTIALLY_RECEIVED', 'COMPLETED', 'REJECTED', 'CANCELLED')),
    constraint ck_po_dates check (expected_date is null or expected_date >= order_date)
);
create index idx_po_worklist on purchase_orders (tenant_id, stock_site_id, status, order_date);

create table purchase_order_lines (
    id bigint primary key,
    revision bigint default 0 not null,
    tenant_id bigint not null,
    purchase_order_id bigint not null,
    sort_order int not null,
    stock_item_id bigint not null,
    package_id bigint not null,
    ordered_quantity decimal(28,8) not null,
    received_quantity decimal(28,8) default 0 not null,
    unit_price decimal(24,6) not null,
    tax_rate decimal(9,6),
    line_status varchar(32) not null,
    description varchar(1000),
    constraint fk_po_line_tenant foreign key (tenant_id) references tenants(id),
    constraint fk_po_line_header foreign key (tenant_id, purchase_order_id) references purchase_orders(tenant_id, id),
    constraint fk_po_line_item foreign key (tenant_id, stock_item_id) references stock_items(tenant_id, id),
    constraint fk_po_line_package foreign key (tenant_id, package_id) references item_packages(tenant_id, id),
    constraint uk_po_line_tenant_id unique (tenant_id, id),
    constraint uk_po_line_order unique (tenant_id, purchase_order_id, sort_order),
    constraint uk_po_line_item unique (tenant_id, purchase_order_id, stock_item_id),
    constraint ck_po_line_quantity check (ordered_quantity > 0 and received_quantity >= 0 and received_quantity <= ordered_quantity),
    constraint ck_po_line_price check (unit_price >= 0),
    constraint ck_po_line_tax check (tax_rate is null or (tax_rate >= 0 and tax_rate <= 1)),
    constraint ck_po_line_status check (line_status in ('OPEN', 'PARTIALLY_RECEIVED', 'COMPLETED', 'CANCELLED'))
);
create index idx_po_line_item on purchase_order_lines (tenant_id, stock_item_id, line_status);

create table goods_receipts (
    id bigint primary key,
    revision bigint default 0 not null,
    tenant_id bigint not null,
    organization_id bigint not null,
    stock_site_id bigint not null,
    purchase_order_id bigint not null,
    supplier_id bigint not null,
    receipt_no varchar(64) not null,
    request_code varchar(128) not null,
    delivery_note_no varchar(128),
    status varchar(32) not null,
    received_at timestamp with time zone not null,
    received_by bigint not null,
    inspected_at timestamp with time zone,
    inspected_by bigint,
    posted_at timestamp with time zone,
    posted_by bigint,
    description varchar(1000),
    created_at timestamp with time zone not null,
    created_by bigint not null,
    updated_at timestamp with time zone not null,
    updated_by bigint not null,
    constraint fk_gr_tenant foreign key (tenant_id) references tenants(id),
    constraint fk_gr_org foreign key (tenant_id, organization_id) references organizations(tenant_id, id),
    constraint fk_gr_site foreign key (tenant_id, stock_site_id) references stock_sites(tenant_id, id),
    constraint fk_gr_po foreign key (tenant_id, purchase_order_id) references purchase_orders(tenant_id, id),
    constraint fk_gr_supplier foreign key (tenant_id, supplier_id) references suppliers(tenant_id, id),
    constraint uk_gr_tenant_id unique (tenant_id, id),
    constraint uk_gr_no unique (tenant_id, receipt_no),
    constraint uk_gr_request unique (tenant_id, request_code),
    constraint ck_gr_status check (status in ('RECEIVED', 'INSPECTING', 'ACCEPTED', 'PARTIALLY_ACCEPTED', 'REJECTED', 'POSTED', 'CANCELLED'))
);
create index idx_gr_worklist on goods_receipts (tenant_id, stock_site_id, status, received_at);

create table goods_receipt_lines (
    id bigint primary key,
    revision bigint default 0 not null,
    tenant_id bigint not null,
    goods_receipt_id bigint not null,
    purchase_order_line_id bigint not null,
    sort_order int not null,
    stock_item_id bigint not null,
    package_id bigint not null,
    destination_bin_id bigint not null,
    lot_no varchar(128) not null,
    production_date date,
    expiry_date date,
    delivered_quantity decimal(28,8) not null,
    accepted_quantity decimal(28,8),
    rejected_quantity decimal(28,8),
    unit_cost decimal(24,6) not null,
    quality_status varchar(32) not null,
    rejection_reason varchar(1000),
    stock_lot_id bigint,
    inventory_transaction_id bigint,
    constraint fk_gr_line_tenant foreign key (tenant_id) references tenants(id),
    constraint fk_gr_line_header foreign key (tenant_id, goods_receipt_id) references goods_receipts(tenant_id, id),
    constraint fk_gr_line_po foreign key (tenant_id, purchase_order_line_id) references purchase_order_lines(tenant_id, id),
    constraint fk_gr_line_item foreign key (tenant_id, stock_item_id) references stock_items(tenant_id, id),
    constraint fk_gr_line_package foreign key (tenant_id, package_id) references item_packages(tenant_id, id),
    constraint fk_gr_line_bin foreign key (tenant_id, destination_bin_id) references stock_bins(tenant_id, id),
    constraint fk_gr_line_lot foreign key (tenant_id, stock_lot_id) references stock_lots(tenant_id, id),
    constraint fk_gr_line_txn foreign key (tenant_id, inventory_transaction_id) references inventory_transactions(tenant_id, id),
    constraint uk_gr_line_tenant_id unique (tenant_id, id),
    constraint uk_gr_line_order unique (tenant_id, goods_receipt_id, sort_order),
    constraint ck_gr_line_quantity check (delivered_quantity > 0 and (accepted_quantity is null or accepted_quantity >= 0) and (rejected_quantity is null or rejected_quantity >= 0)),
    constraint ck_gr_line_cost check (unit_cost >= 0),
    constraint ck_gr_line_dates check (expiry_date is null or production_date is null or expiry_date >= production_date),
    constraint ck_gr_line_quality check (quality_status in ('PENDING', 'QUALIFIED', 'REJECTED', 'QUARANTINE'))
);
create index idx_gr_line_item on goods_receipt_lines (tenant_id, stock_item_id, lot_no);

create table stock_requisitions (
    id bigint primary key,
    revision bigint default 0 not null,
    tenant_id bigint not null,
    organization_id bigint not null,
    source_site_id bigint not null,
    requesting_department_id bigint not null,
    destination_site_id bigint,
    requisition_no varchar(64) not null,
    request_code varchar(128) not null,
    status varchar(32) not null,
    requested_at timestamp with time zone not null,
    requested_by bigint not null,
    approved_at timestamp with time zone,
    approved_by bigint,
    picked_at timestamp with time zone,
    picked_by bigint,
    issued_at timestamp with time zone,
    issued_by bigint,
    reason varchar(1000),
    description varchar(1000),
    inventory_transaction_id bigint,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    updated_by bigint not null,
    constraint fk_req_tenant foreign key (tenant_id) references tenants(id),
    constraint fk_req_org foreign key (tenant_id, organization_id) references organizations(tenant_id, id),
    constraint fk_req_source foreign key (tenant_id, source_site_id) references stock_sites(tenant_id, id),
    constraint fk_req_department foreign key (tenant_id, organization_id, requesting_department_id) references departments(tenant_id, organization_id, id),
    constraint fk_req_destination foreign key (tenant_id, destination_site_id) references stock_sites(tenant_id, id),
    constraint fk_req_txn foreign key (tenant_id, inventory_transaction_id) references inventory_transactions(tenant_id, id),
    constraint uk_req_tenant_id unique (tenant_id, id),
    constraint uk_req_no unique (tenant_id, requisition_no),
    constraint uk_req_request unique (tenant_id, request_code),
    constraint ck_req_status check (status in ('DRAFT', 'SUBMITTED', 'APPROVED', 'PICKING', 'ISSUED', 'REJECTED', 'CANCELLED'))
);
create index idx_req_worklist on stock_requisitions (tenant_id, source_site_id, status, requested_at);

create table stock_requisition_lines (
    id bigint primary key,
    revision bigint default 0 not null,
    tenant_id bigint not null,
    stock_requisition_id bigint not null,
    sort_order int not null,
    stock_item_id bigint not null,
    requested_quantity decimal(28,8) not null,
    approved_quantity decimal(28,8),
    issued_quantity decimal(28,8) default 0 not null,
    base_unit_code varchar(64) not null,
    line_status varchar(32) not null,
    description varchar(1000),
    constraint fk_req_line_tenant foreign key (tenant_id) references tenants(id),
    constraint fk_req_line_header foreign key (tenant_id, stock_requisition_id) references stock_requisitions(tenant_id, id),
    constraint fk_req_line_item foreign key (tenant_id, stock_item_id) references stock_items(tenant_id, id),
    constraint uk_req_line_tenant_id unique (tenant_id, id),
    constraint uk_req_line_order unique (tenant_id, stock_requisition_id, sort_order),
    constraint uk_req_line_item unique (tenant_id, stock_requisition_id, stock_item_id),
    constraint ck_req_line_quantity check (requested_quantity > 0 and (approved_quantity is null or (approved_quantity >= 0 and approved_quantity <= requested_quantity)) and issued_quantity >= 0),
    constraint ck_req_line_status check (line_status in ('REQUESTED', 'APPROVED', 'PICKING', 'ISSUED', 'REJECTED', 'CANCELLED'))
);

create table stock_requisition_allocations (
    id bigint primary key,
    tenant_id bigint not null,
    stock_requisition_line_id bigint not null,
    stock_bin_id bigint not null,
    stock_lot_id bigint not null,
    stock_status varchar(32) not null,
    allocated_quantity decimal(28,8) not null,
    issued_quantity decimal(28,8) default 0 not null,
    status varchar(32) not null,
    created_at timestamp with time zone not null,
    created_by bigint not null,
    constraint fk_req_alloc_tenant foreign key (tenant_id) references tenants(id),
    constraint fk_req_alloc_line foreign key (tenant_id, stock_requisition_line_id) references stock_requisition_lines(tenant_id, id),
    constraint fk_req_alloc_bin foreign key (tenant_id, stock_bin_id) references stock_bins(tenant_id, id),
    constraint fk_req_alloc_lot foreign key (tenant_id, stock_lot_id) references stock_lots(tenant_id, id),
    constraint uk_req_alloc_tenant_id unique (tenant_id, id),
    constraint uk_req_alloc_dimension unique (tenant_id, stock_requisition_line_id, stock_bin_id, stock_lot_id, stock_status),
    constraint ck_req_alloc_quantity check (allocated_quantity > 0 and issued_quantity >= 0 and issued_quantity <= allocated_quantity),
    constraint ck_req_alloc_status check (status in ('ALLOCATED', 'ISSUED', 'RELEASED'))
);

create table stock_transfers (
    id bigint primary key,
    revision bigint default 0 not null,
    tenant_id bigint not null,
    organization_id bigint not null,
    source_site_id bigint not null,
    destination_site_id bigint not null,
    transfer_no varchar(64) not null,
    request_code varchar(128) not null,
    status varchar(32) not null,
    requested_at timestamp with time zone not null,
    requested_by bigint not null,
    approved_at timestamp with time zone,
    approved_by bigint,
    dispatched_at timestamp with time zone,
    dispatched_by bigint,
    received_at timestamp with time zone,
    received_by bigint,
    reason varchar(1000),
    description varchar(1000),
    outbound_transaction_id bigint,
    inbound_transaction_id bigint,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    updated_by bigint not null,
    constraint fk_transfer_tenant foreign key (tenant_id) references tenants(id),
    constraint fk_transfer_org foreign key (tenant_id, organization_id) references organizations(tenant_id, id),
    constraint fk_transfer_source foreign key (tenant_id, source_site_id) references stock_sites(tenant_id, id),
    constraint fk_transfer_destination foreign key (tenant_id, destination_site_id) references stock_sites(tenant_id, id),
    constraint fk_transfer_out_txn foreign key (tenant_id, outbound_transaction_id) references inventory_transactions(tenant_id, id),
    constraint fk_transfer_in_txn foreign key (tenant_id, inbound_transaction_id) references inventory_transactions(tenant_id, id),
    constraint uk_transfer_tenant_id unique (tenant_id, id),
    constraint uk_transfer_no unique (tenant_id, transfer_no),
    constraint uk_transfer_request unique (tenant_id, request_code),
    constraint ck_transfer_sites check (source_site_id <> destination_site_id),
    constraint ck_transfer_status check (status in ('DRAFT', 'SUBMITTED', 'APPROVED', 'PICKING', 'IN_TRANSIT', 'COMPLETED', 'REJECTED', 'CANCELLED'))
);
create index idx_transfer_source on stock_transfers (tenant_id, source_site_id, status, requested_at);
create index idx_transfer_destination on stock_transfers (tenant_id, destination_site_id, status, requested_at);

create table stock_transfer_lines (
    id bigint primary key,
    revision bigint default 0 not null,
    tenant_id bigint not null,
    stock_transfer_id bigint not null,
    sort_order int not null,
    source_stock_item_id bigint not null,
    destination_stock_item_id bigint not null,
    requested_quantity decimal(28,8) not null,
    approved_quantity decimal(28,8),
    dispatched_quantity decimal(28,8) default 0 not null,
    received_quantity decimal(28,8) default 0 not null,
    damaged_quantity decimal(28,8) default 0 not null,
    base_unit_code varchar(64) not null,
    line_status varchar(32) not null,
    discrepancy_reason varchar(1000),
    constraint fk_transfer_line_tenant foreign key (tenant_id) references tenants(id),
    constraint fk_transfer_line_header foreign key (tenant_id, stock_transfer_id) references stock_transfers(tenant_id, id),
    constraint fk_transfer_line_source foreign key (tenant_id, source_stock_item_id) references stock_items(tenant_id, id),
    constraint fk_transfer_line_destination foreign key (tenant_id, destination_stock_item_id) references stock_items(tenant_id, id),
    constraint uk_transfer_line_tenant_id unique (tenant_id, id),
    constraint uk_transfer_line_order unique (tenant_id, stock_transfer_id, sort_order),
    constraint uk_transfer_line_item unique (tenant_id, stock_transfer_id, source_stock_item_id),
    constraint ck_transfer_line_quantity check (requested_quantity > 0 and (approved_quantity is null or (approved_quantity >= 0 and approved_quantity <= requested_quantity)) and dispatched_quantity >= 0 and received_quantity >= 0 and damaged_quantity >= 0),
    constraint ck_transfer_line_status check (line_status in ('REQUESTED', 'APPROVED', 'PICKING', 'IN_TRANSIT', 'COMPLETED', 'REJECTED', 'CANCELLED'))
);

create table stock_transfer_allocations (
    id bigint primary key,
    tenant_id bigint not null,
    stock_transfer_line_id bigint not null,
    source_bin_id bigint not null,
    destination_bin_id bigint,
    stock_lot_id bigint not null,
    stock_status varchar(32) not null,
    dispatched_quantity decimal(28,8) not null,
    received_quantity decimal(28,8) default 0 not null,
    damaged_quantity decimal(28,8) default 0 not null,
    status varchar(32) not null,
    created_at timestamp with time zone not null,
    created_by bigint not null,
    constraint fk_transfer_alloc_tenant foreign key (tenant_id) references tenants(id),
    constraint fk_transfer_alloc_line foreign key (tenant_id, stock_transfer_line_id) references stock_transfer_lines(tenant_id, id),
    constraint fk_transfer_alloc_source foreign key (tenant_id, source_bin_id) references stock_bins(tenant_id, id),
    constraint fk_transfer_alloc_destination foreign key (tenant_id, destination_bin_id) references stock_bins(tenant_id, id),
    constraint fk_transfer_alloc_lot foreign key (tenant_id, stock_lot_id) references stock_lots(tenant_id, id),
    constraint uk_transfer_alloc_tenant_id unique (tenant_id, id),
    constraint uk_transfer_alloc_dimension unique (tenant_id, stock_transfer_line_id, source_bin_id, stock_lot_id, stock_status),
    constraint ck_transfer_alloc_quantity check (dispatched_quantity > 0 and received_quantity >= 0 and damaged_quantity >= 0 and received_quantity + damaged_quantity <= dispatched_quantity),
    constraint ck_transfer_alloc_status check (status in ('ALLOCATED', 'IN_TRANSIT', 'RECEIVED', 'DISCREPANCY'))
);

create table stock_counts (
    id bigint primary key,
    revision bigint default 0 not null,
    tenant_id bigint not null,
    organization_id bigint not null,
    stock_site_id bigint not null,
    stock_bin_id bigint,
    count_no varchar(64) not null,
    request_code varchar(128) not null,
    count_type varchar(32) not null,
    status varchar(32) not null,
    snapshot_at timestamp with time zone not null,
    started_at timestamp with time zone,
    started_by bigint,
    submitted_at timestamp with time zone,
    submitted_by bigint,
    approved_at timestamp with time zone,
    approved_by bigint,
    posted_at timestamp with time zone,
    posted_by bigint,
    reason varchar(1000),
    description varchar(1000),
    inventory_transaction_id bigint,
    created_at timestamp with time zone not null,
    created_by bigint not null,
    updated_at timestamp with time zone not null,
    updated_by bigint not null,
    constraint fk_count_tenant foreign key (tenant_id) references tenants(id),
    constraint fk_count_org foreign key (tenant_id, organization_id) references organizations(tenant_id, id),
    constraint fk_count_site foreign key (tenant_id, stock_site_id) references stock_sites(tenant_id, id),
    constraint fk_count_bin foreign key (tenant_id, stock_bin_id) references stock_bins(tenant_id, id),
    constraint fk_count_txn foreign key (tenant_id, inventory_transaction_id) references inventory_transactions(tenant_id, id),
    constraint uk_count_tenant_id unique (tenant_id, id),
    constraint uk_count_no unique (tenant_id, count_no),
    constraint uk_count_request unique (tenant_id, request_code),
    constraint ck_count_type check (count_type in ('FULL', 'BIN', 'ITEM', 'CYCLE')),
    constraint ck_count_status check (status in ('DRAFT', 'COUNTING', 'SUBMITTED', 'APPROVED', 'POSTED', 'REJECTED', 'CANCELLED'))
);
create index idx_count_worklist on stock_counts (tenant_id, stock_site_id, status, snapshot_at);

create table stock_count_lines (
    id bigint primary key,
    revision bigint default 0 not null,
    tenant_id bigint not null,
    stock_count_id bigint not null,
    sort_order int not null,
    inventory_balance_id bigint not null,
    inventory_balance_revision bigint not null,
    stock_bin_id bigint not null,
    stock_item_id bigint not null,
    stock_lot_id bigint not null,
    stock_status varchar(32) not null,
    book_quantity decimal(28,8) not null,
    counted_quantity decimal(28,8),
    variance_quantity decimal(28,8),
    count_result varchar(32),
    counted_at timestamp with time zone,
    counted_by bigint,
    variance_reason varchar(1000),
    constraint fk_count_line_tenant foreign key (tenant_id) references tenants(id),
    constraint fk_count_line_header foreign key (tenant_id, stock_count_id) references stock_counts(tenant_id, id),
    constraint fk_count_line_balance foreign key (tenant_id, inventory_balance_id) references inventory_balances(tenant_id, id),
    constraint fk_count_line_bin foreign key (tenant_id, stock_bin_id) references stock_bins(tenant_id, id),
    constraint fk_count_line_item foreign key (tenant_id, stock_item_id) references stock_items(tenant_id, id),
    constraint fk_count_line_lot foreign key (tenant_id, stock_lot_id) references stock_lots(tenant_id, id),
    constraint uk_count_line_tenant_id unique (tenant_id, id),
    constraint uk_count_line_order unique (tenant_id, stock_count_id, sort_order),
    constraint uk_count_line_balance unique (tenant_id, stock_count_id, inventory_balance_id),
    constraint ck_count_line_quantity check (book_quantity >= 0 and (counted_quantity is null or counted_quantity >= 0)),
    constraint ck_count_line_result check (count_result is null or count_result in ('MATCHED', 'SURPLUS', 'SHORTAGE'))
);

create table inventory_document_events (
    id bigint primary key,
    tenant_id bigint not null,
    organization_id bigint not null,
    document_type varchar(32) not null,
    document_id bigint not null,
    document_no varchar(64) not null,
    event_type varchar(64) not null,
    from_status varchar(32),
    to_status varchar(32) not null,
    reason varchar(1000),
    correlation_id varchar(128),
    occurred_at timestamp with time zone not null,
    occurred_by bigint not null,
    constraint fk_inv_doc_event_tenant foreign key (tenant_id) references tenants(id),
    constraint fk_inv_doc_event_org foreign key (tenant_id, organization_id) references organizations(tenant_id, id),
    constraint uk_inv_doc_event_tenant_id unique (tenant_id, id),
    constraint ck_inv_doc_event_type check (document_type in ('PURCHASE_ORDER', 'GOODS_RECEIPT', 'REQUISITION', 'TRANSFER', 'COUNT'))
);
create index idx_inv_doc_event_document on inventory_document_events (tenant_id, document_type, document_id, occurred_at);
