package com.rhn.pharmacy.domain;
import com.rhn.shared.id.GlobalIds;
import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.Instant;
@Entity @Table(name="RHN_SUP_STOCK_COUNT_LINE")
public class StockCountLine {
 @Id @Column(name = "ID_STOCK_COUNT_LINE") private Long id;@Version @Column(name = "REVISION") private long revision;@Column(name = "ID_TNT", nullable=false)private Long tenantId;@Column(name = "ID_STOCK_COUNT", nullable=false)private Long stockCountId;@Column(name = "SN_SORT", nullable=false)private int sortOrder;
 @Column(name = "ID_INV_BAL", nullable=false)private Long inventoryBalanceId;@Column(name = "SN_INV_BAL_VER", nullable=false)private long inventoryBalanceRevision;@Column(name = "ID_STOCK_BIN", nullable=false)private Long stockBinId;@Column(name = "ID_STOCK_ITEM", nullable=false)private Long stockItemId;@Column(name = "ID_STOCK_LOT", nullable=false)private Long stockLotId;@Column(name = "SD_STOCK_STATUS", nullable=false)private String stockStatus;
 @Column(name = "QTY_BOOK", nullable=false, precision=28, scale=8)private BigDecimal bookQuantity;@Column(name = "QTY_COUNTED", precision=28, scale=8)private BigDecimal countedQuantity;@Column(name = "QTY_VARIANCE", precision=28, scale=8)private BigDecimal varianceQuantity;@Column(name = "SD_COUNT_RESULT")private String countResult;@Column(name = "DT_COUNTED")private Instant countedAt;@Column(name = "ID_USER_COUNTED")private Long countedBy;@Column(name = "DES_VARIANCE_REASON")private String varianceReason;
 protected StockCountLine(){}public StockCountLine(Long tenantId,Long countId,int sort,InventoryBalance b){id=GlobalIds.next();this.tenantId=tenantId;stockCountId=countId;sortOrder=sort;inventoryBalanceId=b.id();inventoryBalanceRevision=b.revision();stockBinId=b.stockBinId();stockItemId=b.stockItemId();stockLotId=b.stockLotId();stockStatus=b.stockStatus();bookQuantity=b.quantityOnHand();}
 public void record(BigDecimal counted,String reason,Long actor){if(counted==null||counted.signum()<0)throw new IllegalStateException("实盘数量不能小于零");countedQuantity=counted;varianceQuantity=counted.subtract(bookQuantity);countResult=varianceQuantity.signum()==0?"MATCHED":varianceQuantity.signum()>0?"SURPLUS":"SHORTAGE";if(varianceQuantity.signum()!=0&&(reason==null||reason.isBlank()))throw new IllegalStateException("存在盘点差异时必须填写原因");varianceReason=reason;countedAt=Instant.now();countedBy=actor;}
 public Long id(){return id;}public long revision(){return revision;}public Long stockCountId(){return stockCountId;}public int sortOrder(){return sortOrder;}public Long inventoryBalanceId(){return inventoryBalanceId;}public long inventoryBalanceRevision(){return inventoryBalanceRevision;}public Long stockBinId(){return stockBinId;}public Long stockItemId(){return stockItemId;}public Long stockLotId(){return stockLotId;}public String stockStatus(){return stockStatus;}public BigDecimal bookQuantity(){return bookQuantity;}public BigDecimal countedQuantity(){return countedQuantity;}public BigDecimal varianceQuantity(){return varianceQuantity;}public String countResult(){return countResult;}public Instant countedAt(){return countedAt;}public Long countedBy(){return countedBy;}public String varianceReason(){return varianceReason;}
}
