package com.rhn.pharmacy.domain;
import com.rhn.shared.id.GlobalIds;
import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.Instant;
@Entity @Table(name="stock_count_lines")
public class StockCountLine {
 @Id private Long id;@Version private long revision;@Column(name="tenant_id",nullable=false)private Long tenantId;@Column(name="stock_count_id",nullable=false)private Long stockCountId;@Column(name="sort_order",nullable=false)private int sortOrder;
 @Column(name="inventory_balance_id",nullable=false)private Long inventoryBalanceId;@Column(name="inventory_balance_revision",nullable=false)private long inventoryBalanceRevision;@Column(name="stock_bin_id",nullable=false)private Long stockBinId;@Column(name="stock_item_id",nullable=false)private Long stockItemId;@Column(name="stock_lot_id",nullable=false)private Long stockLotId;@Column(name="stock_status",nullable=false)private String stockStatus;
 @Column(name="book_quantity",nullable=false,precision=28,scale=8)private BigDecimal bookQuantity;@Column(name="counted_quantity",precision=28,scale=8)private BigDecimal countedQuantity;@Column(name="variance_quantity",precision=28,scale=8)private BigDecimal varianceQuantity;@Column(name="count_result")private String countResult;@Column(name="counted_at")private Instant countedAt;@Column(name="counted_by")private Long countedBy;@Column(name="variance_reason")private String varianceReason;
 protected StockCountLine(){}public StockCountLine(Long tenantId,Long countId,int sort,InventoryBalance b){id=GlobalIds.next();this.tenantId=tenantId;stockCountId=countId;sortOrder=sort;inventoryBalanceId=b.id();inventoryBalanceRevision=b.revision();stockBinId=b.stockBinId();stockItemId=b.stockItemId();stockLotId=b.stockLotId();stockStatus=b.stockStatus();bookQuantity=b.quantityOnHand();}
 public void record(BigDecimal counted,String reason,Long actor){if(counted==null||counted.signum()<0)throw new IllegalStateException("实盘数量不能小于零");countedQuantity=counted;varianceQuantity=counted.subtract(bookQuantity);countResult=varianceQuantity.signum()==0?"MATCHED":varianceQuantity.signum()>0?"SURPLUS":"SHORTAGE";if(varianceQuantity.signum()!=0&&(reason==null||reason.isBlank()))throw new IllegalStateException("存在盘点差异时必须填写原因");varianceReason=reason;countedAt=Instant.now();countedBy=actor;}
 public Long id(){return id;}public long revision(){return revision;}public Long stockCountId(){return stockCountId;}public int sortOrder(){return sortOrder;}public Long inventoryBalanceId(){return inventoryBalanceId;}public long inventoryBalanceRevision(){return inventoryBalanceRevision;}public Long stockBinId(){return stockBinId;}public Long stockItemId(){return stockItemId;}public Long stockLotId(){return stockLotId;}public String stockStatus(){return stockStatus;}public BigDecimal bookQuantity(){return bookQuantity;}public BigDecimal countedQuantity(){return countedQuantity;}public BigDecimal varianceQuantity(){return varianceQuantity;}public String countResult(){return countResult;}public Instant countedAt(){return countedAt;}public Long countedBy(){return countedBy;}public String varianceReason(){return varianceReason;}
}
