package com.rhn.pharmacy.domain;
import com.rhn.shared.id.GlobalIds;
import jakarta.persistence.*;
import java.time.Instant;
@Entity @Table(name="stock_counts")
public class StockCount {
 @Id private Long id; @Version private long revision; @Column(name="tenant_id",nullable=false)private Long tenantId;
 @Column(name="organization_id",nullable=false)private Long organizationId;@Column(name="stock_site_id",nullable=false)private Long stockSiteId;@Column(name="stock_bin_id")private Long stockBinId;
 @Column(name="count_no",nullable=false)private String countNo;@Column(name="request_code",nullable=false)private String requestCode;@Column(name="count_type",nullable=false)private String countType;@Column(nullable=false)private String status;
 @Column(name="snapshot_at",nullable=false)private Instant snapshotAt;@Column(name="started_at")private Instant startedAt;@Column(name="started_by")private Long startedBy;@Column(name="submitted_at")private Instant submittedAt;@Column(name="submitted_by")private Long submittedBy;
 @Column(name="approved_at")private Instant approvedAt;@Column(name="approved_by")private Long approvedBy;@Column(name="posted_at")private Instant postedAt;@Column(name="posted_by")private Long postedBy;@Column private String reason;@Column private String description;
 @Column(name="inventory_transaction_id")private Long inventoryTransactionId;@Column(name="created_at",nullable=false)private Instant createdAt;@Column(name="created_by",nullable=false)private Long createdBy;@Column(name="updated_at",nullable=false)private Instant updatedAt;@Column(name="updated_by",nullable=false)private Long updatedBy;
 protected StockCount(){}
 public StockCount(Long tenantId,Long organizationId,Long siteId,Long binId,String no,String requestCode,String type,Instant snapshotAt,String reason,String description,Long actor){this.id=GlobalIds.next();this.tenantId=tenantId;this.organizationId=organizationId;this.stockSiteId=siteId;this.stockBinId=binId;this.countNo=no;this.requestCode=requestCode;this.countType=type;this.status="DRAFT";this.snapshotAt=snapshotAt;this.reason=reason;this.description=description;this.createdAt=Instant.now();this.createdBy=actor;this.updatedAt=createdAt;this.updatedBy=actor;}
 public void start(Long actor){require("DRAFT");status="COUNTING";startedAt=Instant.now();startedBy=actor;touch(actor);}public void submit(Long actor){require("COUNTING");status="SUBMITTED";submittedAt=Instant.now();submittedBy=actor;touch(actor);}public void approve(Long actor,String reason){require("SUBMITTED");status="APPROVED";approvedAt=Instant.now();approvedBy=actor;if(reason!=null&&!reason.isBlank())this.reason=reason;touch(actor);}public void reject(Long actor,String reason){require("SUBMITTED");status="REJECTED";approvedAt=Instant.now();approvedBy=actor;this.reason=reason;touch(actor);}public void post(Long actor,Long txn){require("APPROVED");status="POSTED";postedAt=Instant.now();postedBy=actor;inventoryTransactionId=txn;touch(actor);}private void require(String s){if(!s.equals(status))throw new IllegalStateException("盘点单状态不允许当前操作");}private void touch(Long a){updatedAt=Instant.now();updatedBy=a;}
 public Long id(){return id;}public long revision(){return revision;}public Long tenantId(){return tenantId;}public Long organizationId(){return organizationId;}public Long stockSiteId(){return stockSiteId;}public Long stockBinId(){return stockBinId;}public String countNo(){return countNo;}public String requestCode(){return requestCode;}public String countType(){return countType;}public String status(){return status;}public Instant snapshotAt(){return snapshotAt;}public Instant startedAt(){return startedAt;}public Long startedBy(){return startedBy;}public Instant submittedAt(){return submittedAt;}public Long submittedBy(){return submittedBy;}public Instant approvedAt(){return approvedAt;}public Long approvedBy(){return approvedBy;}public Instant postedAt(){return postedAt;}public Long postedBy(){return postedBy;}public String reason(){return reason;}public String description(){return description;}public Long inventoryTransactionId(){return inventoryTransactionId;}
}
