package com.rhn;

import com.rhn.platform.identityaccess.api.IdentityAccessDirectory;
import com.rhn.platform.terminology.domain.TerminologyCodePolicy;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;

import java.time.Instant;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

class FoundationDeveloperPlatformTest extends RhnIntegrationTestSupport {
    @Autowired
    JdbcTemplate jdbcTemplate;
    @Autowired
    IdentityAccessDirectory identityAccessDirectory;

    @Test
    void openapi_contract_includes_required_tenant_context() throws Exception {
        mockMvc.perform(get("/v3/api-docs"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.info.version").value("1.27.0"))
                .andExpect(jsonPath("$.paths['/api/session'].get.parameters[?(@.name == 'X-Tenant-Id')].required")
                        .value(true))
                .andExpect(jsonPath("$.paths['/api/session'].get.parameters[?(@.name == 'X-Tenant-Id')].schema.type")
                        .value("string"))
                .andExpect(jsonPath("$.components.schemas.ResidentResponse.properties.id.type").value("string"))
                .andExpect(jsonPath("$.components.schemas.ResidentResponse.properties.id.pattern")
                        .value("^[1-9][0-9]{0,18}$"))
                .andExpect(jsonPath("$.components.schemas.CreateCodeSystemRequest.properties.code.pattern")
                        .value(TerminologyCodePolicy.CODE_SYSTEM_REGEX))
                .andExpect(jsonPath("$.components.schemas.CreateValueSetRequest.properties.code.pattern")
                        .value(TerminologyCodePolicy.VALUE_SET_REGEX))
                .andExpect(jsonPath("$.components.schemas.CreateDictionaryRequest.properties.code.pattern")
                        .value(com.rhn.platform.dictionary.domain.DictionaryCodePolicy.DICTIONARY_CODE_REGEX))
                .andExpect(jsonPath("$.components.schemas.DictionarySummaryResponse.properties.sdDictStatus").exists())
                .andExpect(jsonPath("$.components.schemas.DictionarySummaryResponse.properties.sdDictStatusText.type")
                        .value("string"))
                .andExpect(jsonPath("$.components.schemas.DictionarySummaryResponse.properties.sdDictStatusText.readOnly")
                        .value(true))
                .andExpect(jsonPath("$.components.schemas.DictionaryItemResponse.properties.sdDictItemStatusText")
                        .exists())
                .andExpect(jsonPath("$.components.schemas.DictionaryChangeResponse.properties.sdDictChangeTypeText")
                        .exists())
                .andExpect(jsonPath("$.components.schemas.StaffAssignmentView.properties.sdPositionType")
                        .exists())
                .andExpect(jsonPath("$.paths['/api/platform/dictionaries/{id}/items'].post").exists())
                .andExpect(jsonPath("$.paths['/api/platform/dictionaries/{id}/changes'].get").exists())
                .andExpect(jsonPath("$.paths['/api/platform/dictionaries/system-enums'].get").exists())
                .andExpect(jsonPath("$.paths['/api/platform/dictionaries/system-enums/{code}'].get").exists())
                .andExpect(jsonPath("$.paths['/api/platform/configuration/categories'].get").exists())
                .andExpect(jsonPath("$.paths['/api/platform/configuration/definitions/{id}/values'].put").exists())
                .andExpect(jsonPath("$.components.schemas.ParameterDefinitionDetailResponse.properties.sdParamStatusText.readOnly")
                        .value(true))
                .andExpect(jsonPath("$.components.schemas.ParameterValueResponse.properties.sdParamValueModeText")
                        .exists())
                .andExpect(jsonPath("$.components.schemas.ParameterChangeResponse.properties.sdParamChangeTypeText")
                        .exists())
                .andExpect(jsonPath("$.paths['/api/platform/master-data/item-attributes/schema'].get").exists())
                .andExpect(jsonPath("$.paths['/api/platform/master-data/item-attributes/resolve'].post").exists())
                .andExpect(jsonPath("$.paths['/api/platform/master-data/item-attributes/snapshot'].post").exists())
                .andExpect(jsonPath("$.paths['/api/platform/master-data/item-attributes/maintenance'].get").exists())
                .andExpect(jsonPath("$.paths['/api/platform/master-data/item-attributes/changes'].get").exists())
                .andExpect(jsonPath("$.paths['/api/platform/master-data/item-attributes/base-value'].put").exists())
                .andExpect(jsonPath("$.paths['/api/platform/master-data/item-attributes/override'].put").exists())
                .andExpect(jsonPath("$.paths['/api/platform/master-data/item-attributes/base-value/disable'].post")
                        .exists())
                .andExpect(jsonPath("$.paths['/api/platform/master-data/item-attributes/override/disable'].post")
                        .exists())
                .andExpect(jsonPath("$.paths['/api/platform/master-data/item-attribute-configurations'].get")
                        .exists())
                .andExpect(jsonPath("$.paths['/api/platform/master-data/item-attribute-configurations/changes'].get")
                        .exists())
                .andExpect(jsonPath("$.paths['/api/platform/master-data/item-attribute-configurations/definitions'].post")
                        .exists())
                .andExpect(jsonPath("$.paths['/api/platform/master-data/item-attribute-configurations/definitions/{id}'].put")
                        .exists())
                .andExpect(jsonPath("$.paths['/api/platform/master-data/item-attribute-configurations/assignments'].post")
                        .exists())
                .andExpect(jsonPath("$.paths['/api/platform/master-data/item-attribute-configurations/assignments/{id}/status'].post")
                        .exists())
                .andExpect(jsonPath("$.components.schemas.AttributeConfigurationResponse.properties.tenantNamespace")
                        .exists())
                .andExpect(jsonPath("$.components.schemas.AttributeDefinitionView.properties.editable")
                        .exists())
                .andExpect(jsonPath("$.components.schemas.ItemAttributeSnapshot.properties.jsonItemAttrSnapshot")
                        .exists())
                .andExpect(jsonPath("$.components.schemas.ItemAttributeSnapshot.properties.hashItemAttrSnapshot")
                        .exists())
                .andExpect(jsonPath("$.paths['/api/platform/master-data/imports/preflight'].post").exists())
                .andExpect(jsonPath("$.paths['/api/platform/master-data/imports/{batchId}'].get").exists())
                .andExpect(jsonPath("$.paths['/api/platform/master-data/imports/{batchId}/rows/{rowId}'].put")
                        .exists())
                .andExpect(jsonPath("$.paths['/api/platform/master-data/imports/{batchId}/commit'].post").exists())
                .andExpect(jsonPath("$.paths['/api/platform/master-data/imports/{batchId}/errors.csv'].get")
                        .exists())
                .andExpect(jsonPath("$.components.schemas.ImportBatchView.properties.invalidRows").exists())
                .andExpect(jsonPath("$.components.schemas.ImportRowView.properties.errors").exists())
                .andExpect(jsonPath("$.paths['/api/platform/master-data/standard-mappings/code-systems'].get")
                        .exists())
                .andExpect(jsonPath("$.paths['/api/platform/master-data/standard-mappings/terms'].get").exists())
                .andExpect(jsonPath("$.paths['/api/platform/master-data/standard-mappings/{subjectType}/{targetId}'].get")
                        .exists())
                .andExpect(jsonPath("$.paths['/api/platform/master-data/standard-mappings/{subjectType}/{targetId}'].post")
                        .exists())
                .andExpect(jsonPath("$.paths['/api/platform/master-data/standard-mappings/mappings/{mappingId}/status'].post")
                        .exists())
                .andExpect(jsonPath("$.components.schemas.ItemTermMappingMaintenanceView.properties.effectiveMappings")
                        .exists())
                .andExpect(jsonPath("$.components.schemas.ItemTermMappingView.properties.systemVersion").exists())
                .andExpect(jsonPath("$.paths['/api/platform/master-data/catalog-lifecycle/catalog-items/{catalogItemId}'].get")
                        .exists())
                .andExpect(jsonPath("$.paths['/api/platform/master-data/catalog-lifecycle/adoptions/{adoptionId}/replace'].post")
                        .exists())
                .andExpect(jsonPath("$.paths['/api/platform/master-data/catalog-lifecycle/prices/{priceId}/replace'].post")
                        .exists())
                .andExpect(jsonPath("$.paths['/api/platform/master-data/catalog-lifecycle/adoption-batches'].post")
                        .exists())
                .andExpect(jsonPath("$.paths['/api/platform/master-data/catalog-lifecycle/price-batches'].post")
                        .exists())
                .andExpect(jsonPath("$.components.schemas.CatalogLifecycleView.properties.adoptionHistory").exists())
                .andExpect(jsonPath("$.components.schemas.CatalogChangeBatchView.properties.rows").exists())
                .andExpect(jsonPath("$.paths['/api/encounters/{encounterId}/service-requests'].post").exists())
                .andExpect(jsonPath("$.paths['/api/encounters/{encounterId}/service-requests'].get").exists())
                .andExpect(jsonPath("$.paths['/api/encounters/{encounterId}/service-requests/{requestId}/cancel'].post")
                        .exists())
                .andExpect(jsonPath("$.components.schemas.ServiceRequestResponse.properties.itemAttributeHash")
                        .exists())
                .andExpect(jsonPath("$.components.schemas.ServiceRequestResponse.properties.standardMappings")
                        .exists())
                .andExpect(jsonPath("$.components.schemas.ServiceRequestResponse.properties.adoptionRevision")
                        .exists())
                .andExpect(jsonPath("$.components.schemas.ServiceRequestResponse.properties.priceRevision")
                        .exists())
                .andExpect(jsonPath("$.components.schemas.ServiceRequestResponse.properties.serviceType")
                        .exists())
                .andExpect(jsonPath("$.paths['/api/encounters/{encounterId}/medication-requests'].post").exists())
                .andExpect(jsonPath("$.paths['/api/encounters/{encounterId}/medication-requests'].get").exists())
                .andExpect(jsonPath("$.paths['/api/encounters/{encounterId}/medication-requests/{requestId}/cancel'].post")
                        .exists())
                .andExpect(jsonPath("$.components.schemas.MedicationRequestResponse.properties.medicationSnapshot")
                        .exists())
                .andExpect(jsonPath("$.components.schemas.MedicationRequestResponse.properties.packageFactor")
                        .exists())
                .andExpect(jsonPath("$.components.schemas.MedicationRequestResponse.properties.baseQuantity")
                        .exists())
                .andExpect(jsonPath("$.components.schemas.MedicationRequestResponse.properties.priceQuantity")
                        .exists())
                .andExpect(jsonPath("$.components.schemas.MedicationRequestResponse.properties.prescriptionId")
                        .exists())
                .andExpect(jsonPath("$.components.schemas.CreateMedicationRequest.properties.medicationId")
                        .exists())
                .andExpect(jsonPath("$.paths['/api/encounters/{encounterId}/prescriptions'].post").exists())
                .andExpect(jsonPath("$.paths['/api/encounters/{encounterId}/prescriptions'].get").exists())
                .andExpect(jsonPath("$.paths['/api/encounters/{encounterId}/prescriptions/{prescriptionId}/submit'].post")
                        .exists())
                .andExpect(jsonPath("$.paths['/api/encounters/{encounterId}/prescriptions/{prescriptionId}/cancel'].post")
                        .exists())
                .andExpect(jsonPath("$.components.schemas.PrescriptionResponse.properties.medicationRequests")
                        .exists())
                .andExpect(jsonPath("$.paths['/api/clinical-documents'].get.parameters[?(@.name == 'encounterId')]")
                        .exists())
                .andExpect(jsonPath("$.paths['/api/clinical-documents/{documentId}/sign'].post").exists())
                .andExpect(jsonPath("$.components.schemas.ClinicalDocumentResponse.properties.history").exists())
                .andExpect(jsonPath("$.components.schemas.VersionView.properties.signatureEvidenceId").exists())
                .andExpect(jsonPath("$.paths['/api/clinical-documents/{documentId}/print-jobs'].post").exists())
                .andExpect(jsonPath("$.paths['/api/encounters/{encounterId}/prescriptions/{prescriptionId}/print-jobs'].post")
                        .exists())
                .andExpect(jsonPath("$.paths['/api/platform/printing/templates'].get").exists())
                .andExpect(jsonPath("$.paths['/api/platform/printing/jobs/{jobId}/reprints'].post").exists())
                .andExpect(jsonPath("$.paths['/api/platform/printing/outputs/{outputId}/content'].get").exists())
                .andExpect(jsonPath("$.components.schemas.PrintReceipt.properties.contentDigest").exists())
                .andExpect(jsonPath("$.paths['/api/integration/diagnostics/requests/{requestId}/outbound-messages'].post")
                        .exists())
                .andExpect(jsonPath("$.paths['/api/integration/diagnostics/outbound-messages'].get").exists())
                .andExpect(jsonPath("$.paths['/api/integration/diagnostics/outbound-messages/{messageId}/delivery'].post")
                        .exists())
                .andExpect(jsonPath("$.paths['/api/integration/diagnostics/inbound/acknowledgements'].post")
                        .exists())
                .andExpect(jsonPath("$.paths['/api/integration/diagnostics/inbound/reports'].post").exists())
                .andExpect(jsonPath("$.paths['/api/encounters/{encounterId}/diagnostic-reports'].get").exists())
                .andExpect(jsonPath("$.paths['/api/service-requests/{requestId}/diagnostic-reports'].get").exists())
                .andExpect(jsonPath("$.components.schemas.DiagnosticReportResponse.properties.observations")
                        .exists())
                .andExpect(jsonPath("$.components.schemas.ExternalMessageReceipt.properties.payloadDigest")
                        .exists())
                .andExpect(jsonPath("$.paths['/api/pharmacy/stock-sites'].post").exists())
                .andExpect(jsonPath("$.paths['/api/pharmacy/stock-sites'].get").exists())
                .andExpect(jsonPath("$.paths['/api/pharmacy/stock-sites/{siteId}/stock-items'].post").exists())
                .andExpect(jsonPath("$.paths['/api/pharmacy/stock-sites/{siteId}/stock-items'].get").exists())
                .andExpect(jsonPath("$.paths['/api/pharmacy/stock-sites/{siteId}/stock-items/batch'].post").exists())
                .andExpect(jsonPath("$.paths['/api/pharmacy/inbox'].get").exists())
                .andExpect(jsonPath("$.paths['/api/pharmacy/requests/{requestId}/intake'].post").exists())
                .andExpect(jsonPath("$.paths['/api/pharmacy/dispense-tasks'].get").exists())
                .andExpect(jsonPath("$.paths['/api/pharmacy/dispense-tasks/{taskId}'].get").exists())
                .andExpect(jsonPath("$.paths['/api/pharmacy/dispense-tasks/{taskId}/reviews'].post").exists())
                .andExpect(jsonPath("$.paths['/api/pharmacy/stock-sites/{siteId}/stock-bins'].post").exists())
                .andExpect(jsonPath("$.paths['/api/pharmacy/stock-sites/{siteId}/stock-bins'].get").exists())
                .andExpect(jsonPath("$.paths['/api/pharmacy/stock-items/{stockItemId}/lots'].post").exists())
                .andExpect(jsonPath("$.paths['/api/pharmacy/stock-items/{stockItemId}/lots'].get").exists())
                .andExpect(jsonPath("$.paths['/api/pharmacy/inventory/receipts'].post").exists())
                .andExpect(jsonPath("$.paths['/api/pharmacy/inventory/balances'].get").exists())
                .andExpect(jsonPath("$.paths['/api/pharmacy/inventory/transactions'].get").exists())
                .andExpect(jsonPath("$.paths['/api/pharmacy/dispense-tasks/{taskId}/reservations'].post").exists())
                .andExpect(jsonPath("$.paths['/api/pharmacy/dispense-tasks/{taskId}/reservations'].get").exists())
                .andExpect(jsonPath("$.paths['/api/pharmacy/dispense-tasks/{taskId}/reservations/release'].post")
                        .exists())
                .andExpect(jsonPath("$.paths['/api/pharmacy/dispense-tasks/{taskId}/picking/complete'].post")
                        .exists())
                .andExpect(jsonPath("$.paths['/api/pharmacy/dispense-tasks/{taskId}/dispenses'].post").exists())
                .andExpect(jsonPath("$.paths['/api/pharmacy/dispenses/{dispenseId}/returns'].post").exists())
                .andExpect(jsonPath("$.paths['/api/pharmacy/dispense-tasks/{taskId}/trace'].get").exists())
                .andExpect(jsonPath("$.components.schemas.DispenseTaskView.properties.lines").exists())
                .andExpect(jsonPath("$.components.schemas.DispenseTaskLineView.properties.itemAttributeSnapshot")
                        .exists())
                .andExpect(jsonPath("$.components.schemas.PharmacyReviewView.properties.result").exists())
                .andExpect(jsonPath("$.components.schemas.InventoryBalanceView.properties.quantityAvailable").exists())
                .andExpect(jsonPath("$.components.schemas.InventoryTransactionView.properties.lines").exists())
                .andExpect(jsonPath("$.components.schemas.ReservationResultView.properties.allocations").exists())
                .andExpect(jsonPath("$.components.schemas.MedicationDispenseView.properties.lines").exists())
                .andExpect(jsonPath("$.components.schemas.MedicationDispenseLineView.properties.inventoryTransactionLineId")
                        .exists())
                .andExpect(jsonPath("$.components.schemas.StockReturnView.properties.originalDispenseId").exists())
                .andExpect(jsonPath("$.components.schemas.DispenseTraceView.properties.events").exists())
                .andExpect(jsonPath("$.paths['/api/billing/worklist'].get").exists())
                .andExpect(jsonPath("$.paths['/api/billing/encounters/{encounterId}/charges/synchronize'].post").exists())
                .andExpect(jsonPath("$.paths['/api/billing/encounters/{encounterId}/statement'].get").exists())
                .andExpect(jsonPath("$.paths['/api/billing/accounts/{accountId}/invoices'].post").exists())
                .andExpect(jsonPath("$.paths['/api/billing/invoices/{invoiceId}/payments'].post").exists())
                .andExpect(jsonPath("$.paths['/api/billing/payments/{paymentId}/refunds'].post").exists())
                .andExpect(jsonPath("$.paths['/api/billing/reconciliation/daily'].get").exists())
                .andExpect(jsonPath("$.components.schemas.BillingWorkItemView.properties.sourceEventCount").exists())
                .andExpect(jsonPath("$.components.schemas.ChargeItemView.properties.priceRevision").exists())
                .andExpect(jsonPath("$.components.schemas.ChargeItemView.properties.reversesChargeItemId").exists())
                .andExpect(jsonPath("$.components.schemas.AccountStatementView.properties.ledgerEntries").exists())
                .andExpect(jsonPath("$.components.schemas.LedgerEntryView.properties.reversesLedgerEntryId").exists())
                .andExpect(jsonPath("$.components.schemas.PaymentView.properties.reversesPaymentId").exists())
                .andExpect(jsonPath("$.components.schemas.DailyReconciliationView.properties.discrepancyCount").exists())
                .andExpect(jsonPath("$.paths['/api/health-planning/hypertension-candidates'].get").exists())
                .andExpect(jsonPath("$.paths['/api/health-planning/hypertension-candidates'].get.parameters[?(@.name == 'residentId')]")
                        .exists())
                .andExpect(jsonPath("$.components.schemas.HypertensionCandidateView.properties.conditionId")
                        .exists())
                .andExpect(jsonPath("$.components.schemas.HypertensionCandidateView.properties.verificationStatus")
                        .exists())
                .andExpect(jsonPath("$.components.schemas.HypertensionCandidateView.properties.evidenceEvents")
                        .exists())
                .andExpect(jsonPath("$.components.schemas.EvidenceEventView.properties.ruleCode").exists())
                .andExpect(jsonPath("$.components.schemas.EvidenceEventView.properties.evidenceHash").exists());
    }

    @Test
    void database_identity_model_resolves_active_roles_and_permissions() {
        Long userId = com.rhn.shared.id.GlobalIds.next();
        Long roleId = com.rhn.shared.id.GlobalIds.next();
        Long permissionId = com.rhn.shared.id.GlobalIds.next();
        Instant now = Instant.now();
        jdbcTemplate.update("""
                insert into user_accounts
                    (id, tenant_id, username, password_hash, status, created_at, updated_at, version)
                values (?, cast(? as bigint), 'iam-doctor', '{noop}secret', 'ACTIVE', ?, ?, 0)
                """, userId, TENANT, now, now);
        jdbcTemplate.update("""
                insert into access_roles
                    (id, tenant_id, code, name, role_type, status, created_at, updated_at, version)
                values (?, cast(? as bigint), 'CLINICIAN', '临床医生', 'SYSTEM', 'ACTIVE', ?, ?, 0)
                """, roleId, TENANT, now, now);
        jdbcTemplate.update("""
                insert into access_permissions
                    (id, tenant_id, code, name, action_code, resource_code, status)
                values (?, cast(? as bigint), 'resident:read', '读取居民', 'READ', 'RESIDENT', 'ACTIVE')
                """, permissionId, TENANT);
        jdbcTemplate.update("""
                insert into user_role_assignments
                    (id, tenant_id, user_id, role_id, data_scope_type, valid_from, created_at)
                values (?, cast(? as bigint), ?, ?, 'TENANT', ?, ?)
                """, com.rhn.shared.id.GlobalIds.next(), TENANT, userId, roleId, now.minusSeconds(60), now);
        jdbcTemplate.update("""
                insert into role_permission_assignments
                    (id, tenant_id, role_id, permission_id, valid_from, created_at)
                values (?, cast(? as bigint), ?, ?, ?, ?)
                """, com.rhn.shared.id.GlobalIds.next(), TENANT, roleId, permissionId, now.minusSeconds(60), now);

        var account = identityAccessDirectory.findActiveAccount(Long.valueOf(TENANT), " iam-doctor ")
                .orElseThrow();
        assertEquals(userId, account.id());
        assertTrue(account.authorities().contains("ROLE_CLINICIAN"));
        assertTrue(account.authorities().contains("resident:read"));
    }
}
