import { render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { expect, it, vi } from 'vitest'
import type { RhnApi } from '../../shared/rhnApi'
import type { PageSpec, PageResult } from '../../shared/api/analysisPagesApi'
import { DynamicAnalysisLibrary, DynamicResult } from './DynamicAnalysisLibrary'

const spec:PageSpec={title:'诊断记录排行',template:'RANKING',metrics:['DIAGNOSIS_RECORDS'],dimension:'DIAGNOSIS',scope:'CURRENT',period:{kind:'MONTH_TO_DATE'},limit:10}
const result:PageResult={spec,startDate:'2026-09-01',endDate:'2026-09-14',scopeName:'全科门诊',timezone:'Asia/Shanghai',fetchedAt:'2026-09-14T00:00:00Z',series:[{code:'DIAGNOSIS_RECORDS',name:'有效确诊记录数',unit:'条',definition:'只统计有效确诊记录，不按患者去重',total:3,groupCount:2,points:[{key:'A',label:'测试诊断A',value:2},{key:'B',label:'测试诊断B',value:1}]}]}
function setup(){
 const generate=vi.fn().mockResolvedValue({status:'READY',message:'按有效确诊记录统计',spec})
 const query=vi.fn().mockResolvedValue(result),save=vi.fn().mockImplementation(async spec=>({id:'saved-1',spec,savedAt:'2026-09-14'}))
 const api={analytics:{savedPages:vi.fn().mockResolvedValue([]),pageSources:vi.fn().mockResolvedValue([]),pageCatalog:vi.fn().mockResolvedValue([]),aiStatus:vi.fn().mockResolvedValue({available:true,model:'test',message:'AI可用'}),generatePage:generate,queryPage:query,savePage:save}} as unknown as RhnApi
 return {api,generate,query,save}
}
it('starts with generic templates and no fixed metrics or query form',async()=>{
 const {api,query}=setup();render(<DynamicAnalysisLibrary api={api}/>)
 await screen.findByRole('button',{name:/排行分析/})
 expect(screen.queryByText('挂号人次')).not.toBeInTheDocument()
 expect(screen.queryByText('退号率')).not.toBeInTheDocument()
 expect(screen.queryByLabelText('统计日期')).not.toBeInTheDocument()
 expect(screen.queryByLabelText('生成的业务分析页面')).not.toBeInTheDocument()
 expect(query).not.toHaveBeenCalled()
})
it('uses selected presentation and business-only requirement to generate only relevant fields, then persists',async()=>{
 const user=userEvent.setup(),{api,generate,query,save}=setup();render(<DynamicAnalysisLibrary api={api}/>)
 await user.click(await screen.findByRole('button',{name:/排行分析/}))
 await user.type(screen.getByLabelText('业务分析需求'),'本月诊断记录条数排行')
 await user.click(screen.getByRole('button',{name:'生成页面预览'}))
 await user.click(await screen.findByRole('tab',{name:'数据明细'}))
 await screen.findByRole('table')
 expect(generate).toHaveBeenCalledWith('本月诊断记录条数排行','RANKING')
 expect(query).toHaveBeenCalledWith(spec)
 expect(screen.queryByText('挂号人次')).not.toBeInTheDocument()
 expect(within(screen.getByRole('table')).getByRole('columnheader',{name:'有效确诊记录数（条）'})).toBeInTheDocument()
 expect(save).not.toHaveBeenCalled()
 await user.click(screen.getByRole('button',{name:'确认并固化'}))
 await screen.findByRole('button',{name:/诊断记录排行/})
 expect(save).toHaveBeenCalledWith(spec)
 expect(screen.queryByLabelText('业务分析需求')).not.toBeInTheDocument()
})
it('keeps clarification outside generated page and never queries',async()=>{
 const user=userEvent.setup(),{api,generate,query}=setup();generate.mockResolvedValue({status:'CLARIFY',message:'是否按记录条数统计？',spec:null})
 render(<DynamicAnalysisLibrary api={api}/>)
 await user.type(await screen.findByLabelText('业务分析需求'),'诊断数量排行')
 await user.click(screen.getByRole('button',{name:'生成页面预览'}))
 await screen.findAllByText('是否按记录条数统计？')
 expect(query).not.toHaveBeenCalled()
 expect(screen.queryByRole('button',{name:'确认并固化'})).not.toBeInTheDocument()
})
it('keeps setup out of the editing workspace and blocks saving an unsent change',async()=>{
 const user=userEvent.setup(),{api}=setup();render(<DynamicAnalysisLibrary api={api}/>)
 await user.type(await screen.findByLabelText('业务分析需求'),'诊断记录排行')
 await user.click(screen.getByRole('button',{name:'生成页面预览'}))
 await waitFor(()=>expect(screen.getByRole('button',{name:'确认并固化'})).toBeEnabled())
 expect(screen.queryByLabelText('业务分析需求')).not.toBeInTheDocument()
 expect(screen.queryByRole('button',{name:/统计列表/})).not.toBeInTheDocument()
 expect(screen.queryByRole('table')).not.toBeInTheDocument()
 await user.type(screen.getByLabelText('补充或修改要求'),'再按人数')
 expect(screen.getByRole('button',{name:'确认并固化'})).toBeDisabled()
})
it('renders multi-metric columns from the result definition',()=>{
 render(<DynamicResult result={{...result,spec:{...spec,template:'LIST',metrics:['DIAGNOSIS_RECORDS','COMPLETED']},series:[...result.series,{...result.series[0],code:'COMPLETED',name:'诊毕人次',unit:'人次'}]}}/>)
 expect(screen.getByRole('columnheader',{name:'有效确诊记录数（条）'})).toBeInTheDocument()
 expect(screen.getByRole('columnheader',{name:'诊毕人次（人次）'})).toBeInTheDocument()
 expect(screen.queryByText('挂号队列退号率')).not.toBeInTheDocument()
})
it('shows field-based calculations and filters, then saves and reopens the same plan',async()=>{
 const user=userEvent.setup(),{api,generate,query,save}=setup()
 const plan:PageSpec={...spec,title:'有效药品医嘱人数',template:'LIST',dimension:'DEPARTMENT',metrics:['M1'],measures:[{code:'M1',name:'有效药品医嘱患者人数',source:'ORDER',sourceVersion:1,aggregate:'COUNT_DISTINCT',field:'patientId',filters:[{field:'status',operator:'EQ',values:['ACTIVE']},{field:'kind',operator:'EQ',values:['MEDICATION']}]}]}
 vi.mocked(api.analytics.pageSources).mockResolvedValue([{code:'ORDER',version:1,name:'门诊医嘱',grain:'每条医嘱一行',definition:'按开立日期',relation:'医嘱到就诊',dimensions:['DEPARTMENT'],fields:[{code:'patientId',name:'有医嘱的患者',databaseType:'NUMBER',unit:'人',aggregates:['COUNT_DISTINCT'],operators:[],values:{}},{code:'status',name:'医嘱状态',databaseType:'VARCHAR',unit:'',aggregates:[],operators:['EQ'],values:{ACTIVE:'有效'}},{code:'kind',name:'医嘱类别',databaseType:'VARCHAR',unit:'',aggregates:[],operators:['EQ'],values:{MEDICATION:'药品医嘱'}}]}])
 generate.mockResolvedValue({status:'READY',message:'字段组合生成',spec:plan});query.mockResolvedValue({...result,spec:plan,series:[{...result.series[0],code:'M1',name:'有效药品医嘱患者人数',unit:'人'}]})
 render(<DynamicAnalysisLibrary api={api}/>);await user.type(await screen.findByLabelText('业务分析需求'),'有效药品医嘱患者人数')
 await user.click(screen.getByRole('button',{name:'生成页面预览'}))
 await user.click(await screen.findByRole('tab',{name:'计算配置'}))
 expect(screen.getByLabelText('指标1计算方式')).toHaveValue('COUNT_DISTINCT')
 expect(screen.getByLabelText('指标1筛选2值')).toHaveValue('MEDICATION')
 await waitFor(()=>expect(screen.getByRole('button',{name:'确认并固化'})).toBeEnabled())
 await user.click(screen.getByRole('button',{name:'确认并固化'}));expect(save).toHaveBeenCalledWith(plan)
 await user.click(await screen.findByRole('button',{name:/有效药品医嘱人数/}));expect(query).toHaveBeenLastCalledWith(plan)
})
it('renders reversal amounts below zero with valid bar dimensions',()=>{
 const {container}=render(<DynamicResult result={{...result,spec:{...spec,template:'COMPARISON'},series:[{...result.series[0],name:'费用净发生额',unit:'元',total:-50,points:[{key:'A',label:'正向费用',value:50},{key:'B',label:'冲销',value:-100}]}]}}/>)
 const bars=[...container.querySelectorAll('svg rect')]
 expect(bars).toHaveLength(2)
 expect(bars.every(bar=>Number(bar.getAttribute('height'))>0)).toBe(true)
 expect(bars[1].classList.contains('is-negative')).toBe(true)
 expect([...container.querySelectorAll('svg title')].map(node=>node.textContent)).toContain('冲销：-100 元')
})

it('replaces the progress explanation with the failure reason when generation fails',async()=>{
 const user=userEvent.setup(),{api,generate}=setup();generate.mockRejectedValue(new Error('模型格式错误'))
 render(<DynamicAnalysisLibrary api={api}/>);await user.type(await screen.findByLabelText('业务分析需求'),'门诊医嘱分析')
 await user.click(screen.getByRole('button',{name:'生成页面预览'}))
 await screen.findByText('未能完成页面预览：模型格式错误')
 expect(screen.queryByText('AI 正在分析数据关系、计算方式和筛选条件…')).not.toBeInTheDocument()
 expect(screen.getByRole('button',{name:'生成页面预览'})).toBeEnabled()
})

it('answers clarification with history and preserves the current plan on unresolved changes',async()=>{
 const user=userEvent.setup(),{api,generate,query}=setup()
 generate.mockResolvedValueOnce({status:'CLARIFY',message:'按记录还是人数？',spec:null})
 render(<DynamicAnalysisLibrary api={api}/>);await user.type(await screen.findByLabelText('业务分析需求'),'诊断数量排行')
 await user.click(screen.getByRole('button',{name:'生成页面预览'}))
 await user.type(await screen.findByLabelText('补充或修改要求'),'按记录')
 await user.click(screen.getByRole('button',{name:'发送补充并更新预览'}))
 await waitFor(()=>expect(screen.getByRole('button',{name:'确认并固化'})).toBeEnabled())
 expect(generate).toHaveBeenLastCalledWith('按记录','AUTO',{currentSpec:null,history:[{role:'USER',content:'诊断数量排行'},{role:'ASSISTANT',content:'按记录还是人数？'}]})
 generate.mockResolvedValueOnce({status:'CLARIFY',message:'需要实际收款吗？',spec:null})
 await user.type(screen.getByLabelText('补充或修改要求'),'增加收费情况')
 expect(screen.getByRole('button',{name:'确认并固化'})).toBeDisabled()
 await user.click(screen.getByRole('button',{name:'发送补充并更新预览'}))
 await screen.findAllByText('需要实际收款吗？')
 expect(generate.mock.calls.at(-1)?.[2].currentSpec).toEqual(spec)
 expect(query).toHaveBeenCalledTimes(1)
 await user.click(screen.getByRole('tab',{name:'数据明细'}))
 expect(screen.getByRole('columnheader',{name:'有效确诊记录数（条）'})).toBeInTheDocument()
 expect(screen.getByRole('button',{name:'确认并固化'})).toBeDisabled()
 await user.click(screen.getByRole('button',{name:'撤销所有调整'}))
 await user.click(screen.getByRole('button',{name:'更新预览'}))
 await waitFor(()=>expect(screen.getByRole('button',{name:'确认并固化'})).toBeEnabled())
})
it('requires a new preview after direct changes and saves an adjusted function separately',async()=>{
 const user=userEvent.setup(),{api,query,save}=setup()
 vi.mocked(api.analytics.savedPages).mockResolvedValue([{id:'original',spec,savedAt:'2026-09-14'}])
 query.mockImplementation(async (s:PageSpec)=>({...result,spec:s}))
 render(<DynamicAnalysisLibrary api={api}/>);await user.click(await screen.findByRole('button',{name:'基于此功能调整'}))
 await user.selectOptions(screen.getByLabelText('统计日期'),'LAST_MONTH')
 expect(screen.getByRole('button',{name:'确认并另存为新功能'})).toBeDisabled()
 await user.click(screen.getByRole('tab',{name:'变更对照'}))
 expect(screen.getByText('与初始方案比较')).toBeInTheDocument()
 await user.click(screen.getByRole('button',{name:'更新预览'}))
 await waitFor(()=>expect(screen.getByRole('button',{name:'确认并另存为新功能'})).toBeEnabled())
 await user.click(screen.getByRole('button',{name:'确认并另存为新功能'}))
 await waitFor(()=>expect(save).toHaveBeenCalledTimes(1))
 expect(save.mock.calls[0][0].period.kind).toBe('LAST_MONTH')
 expect(spec.period.kind).toBe('MONTH_TO_DATE')
 expect(within(screen.getByRole('navigation',{name:'已固化统计功能列表'})).getAllByRole('button')).toHaveLength(2)
})
it('confirms abandoning edits and ignores a late AI response after returning to the library',async()=>{
 const user=userEvent.setup(),{api,generate,query}=setup()
 vi.mocked(api.analytics.savedPages).mockResolvedValue([{id:'original',spec,savedAt:'2026-09-14'}])
 let resolve!:(value:unknown)=>void;generate.mockReturnValue(new Promise(r=>{resolve=r}))
 render(<DynamicAnalysisLibrary api={api}/>);await user.click(await screen.findByRole('button',{name:'基于此功能调整'}))
 await user.type(screen.getByLabelText('补充或修改要求'),'改成上个月')
 await user.click(screen.getByRole('button',{name:'发送补充并更新预览'}))
 await user.click(screen.getByRole('button',{name:'返回功能库'}))
 expect(screen.getByRole('dialog')).toBeInTheDocument()
 await user.click(screen.getByRole('button',{name:'放弃调整并返回'}))
 await screen.findByRole('button',{name:'基于此功能调整'})
 resolve({status:'READY',message:'旧结果',spec:{...spec,title:'过期的方案'}})
 await waitFor(()=>expect(screen.queryByText('过期的方案')).not.toBeInTheDocument())
 expect(query).toHaveBeenCalledTimes(2)
 expect(screen.queryByLabelText('补充或修改要求')).not.toBeInTheDocument()
})

it('includes manually edited grouping and measure filters in the next AI request',async()=>{
 const user=userEvent.setup(),{api,generate,query}=setup()
 const plan:PageSpec={...spec,template:'LIST',dimension:'DAY',metrics:['M1'],measures:[{code:'M1',name:'医嘱条数',source:'ORDER',sourceVersion:1,aggregate:'COUNT',field:'orderId',filters:[{field:'kind',operator:'EQ',values:['MEDICATION']}]}]}
 vi.mocked(api.analytics.pageSources).mockResolvedValue([{code:'ORDER',version:1,name:'门诊医嘱',grain:'每条医嘱',definition:'开立日期',relation:'就诊',dimensions:['DAY','DEPARTMENT'],fields:[{code:'orderId',name:'医嘱',databaseType:'NUMBER',unit:'条',aggregates:['COUNT'],operators:[],values:{}},{code:'kind',name:'类别',databaseType:'VARCHAR',unit:'',aggregates:[],operators:['EQ'],values:{MEDICATION:'药品',SERVICE:'服务'}}]}])
 generate.mockResolvedValue({status:'READY',message:'医嘱统计',spec:plan});query.mockImplementation(async(s:PageSpec)=>({...result,spec:s}))
 render(<DynamicAnalysisLibrary api={api}/>);await user.type(await screen.findByLabelText('业务分析需求'),'医嘱条数')
 await user.click(screen.getByRole('button',{name:'生成页面预览'}))
 await waitFor(()=>expect(screen.getByRole('button',{name:'确认并固化'})).toBeEnabled())
 await user.click(screen.getByRole('tab',{name:'计算配置'}))
 await user.selectOptions(screen.getByLabelText('分组方式'),'DEPARTMENT')
 await user.selectOptions(screen.getByLabelText('指标1筛选1值'),'SERVICE')
 expect(screen.getByRole('button',{name:'确认并固化'})).toBeDisabled()
 await user.type(screen.getByLabelText('补充或修改要求'),'改成上个月')
 await user.click(screen.getByRole('button',{name:'发送补充并更新预览'}))
 await waitFor(()=>expect(generate).toHaveBeenCalledTimes(2))
 expect(generate.mock.calls[1][2].currentSpec.dimension).toBe('DEPARTMENT')
 expect(generate.mock.calls[1][2].currentSpec.measures[0].filters[0].values).toEqual(['SERVICE'])
})

it('separates workspace responsibilities, supports keyboard tabs and preserves a hidden AI draft',async()=>{
 const user=userEvent.setup(),{api}=setup()
 render(<DynamicAnalysisLibrary api={api}/>);await user.type(await screen.findByLabelText('业务分析需求'),'诊断记录排行')
 await user.click(screen.getByRole('button',{name:'生成页面预览'}))
 const preview=await screen.findByRole('tab',{name:'结果预览'})
 expect(screen.queryByRole('table')).not.toBeInTheDocument()
 preview.focus();await user.keyboard('{ArrowRight}')
 expect(screen.getByRole('tab',{name:'数据明细'})).toHaveFocus()
 expect(screen.getByRole('table')).toBeInTheDocument()
 await user.type(screen.getByLabelText('补充或修改要求'),'改成上个月')
 await user.click(screen.getByRole('button',{name:'收起 AI'}))
 expect(screen.queryByLabelText('补充或修改要求')).not.toBeInTheDocument()
 expect(screen.getByRole('button',{name:'确认并固化'})).toBeDisabled()
 await user.click(screen.getByRole('button',{name:'AI 助手'}))
 expect(screen.getByLabelText('补充或修改要求')).toHaveValue('改成上个月')
})
it('edits one metric at a time and returns to the result after updating',async()=>{
 const user=userEvent.setup(),{api,generate,query}=setup()
 const m={code:'M1',name:'医嘱条数',source:'ORDER',sourceVersion:1,aggregate:'COUNT' as const,field:'orderId',filters:[]}
 const plan:PageSpec={...spec,template:'LIST',dimension:'DAY',metrics:['M1','M2'],measures:[m,{...m,code:'M2',name:'另一个指标'}]}
 generate.mockResolvedValue({status:'READY',message:'生成两个指标',spec:plan});query.mockImplementation(async(s:PageSpec)=>({...result,spec:s}))
 render(<DynamicAnalysisLibrary api={api}/>);await user.type(await screen.findByLabelText('业务分析需求'),'医嘱统计')
 await user.click(screen.getByRole('button',{name:'生成页面预览'}));await user.click(await screen.findByRole('tab',{name:'计算配置'}))
 expect(screen.getByLabelText('指标1名称')).toBeInTheDocument()
 expect(screen.queryByLabelText('指标2名称')).not.toBeInTheDocument()
 await user.click(screen.getByRole('button',{name:'2. 另一个指标'}))
 await user.clear(screen.getByLabelText('指标2名称'));await user.type(screen.getByLabelText('指标2名称'),'调整后指标')
 expect(screen.queryByLabelText('指标1名称')).not.toBeInTheDocument()
 await user.click(screen.getByRole('tab',{name:'变更对照'}))
 expect(screen.getByText(/调整后指标：/)).toBeInTheDocument()
 await user.click(screen.getByRole('button',{name:'更新预览'}))
 await waitFor(()=>expect(screen.getByRole('tab',{name:'结果预览'})).toHaveAttribute('aria-selected','true'))
})

it('keeps data capabilities available in the request header after clarification and in the editor',async()=>{
 const user=userEvent.setup(),{api,generate}=setup()
 generate.mockResolvedValueOnce({status:'CLARIFY',message:'记录还是人数？',spec:null})
 render(<DynamicAnalysisLibrary api={api}/>);
 expect(await screen.findByRole('button',{name:/AI 自动识别/})).toHaveAttribute('aria-pressed','true')
 await user.type(screen.getByLabelText('业务分析需求'),'诊断数量');await user.click(screen.getByRole('button',{name:'生成页面预览'}))
 await screen.findByLabelText('补充或修改要求')
 await user.click(screen.getByRole('button',{name:'可分析数据'}));expect(screen.getByRole('dialog')).toHaveTextContent('可分析数据')
 await user.click(within(screen.getByRole('dialog')).getByRole('button',{name:'关闭'}))
 await user.type(screen.getByLabelText('补充或修改要求'),'记录');await user.click(screen.getByRole('button',{name:'发送补充并更新预览'}))
 await screen.findByRole('tab',{name:'结果预览'});await user.click(screen.getByRole('button',{name:'可分析数据'}));expect(screen.getByRole('dialog')).toBeInTheDocument()
 expect(generate.mock.calls[0][1]).toBe('AUTO');expect(generate.mock.calls[1][1]).toBe('AUTO')
})
it('renders AI-composed cards and a table in one preview without adding a chart',()=>{
 const custom:PageSpec={...spec,template:'CUSTOM',widgets:[{title:'核心数量',type:'KPI',metrics:spec.metrics},{title:'诊断明细',type:'TABLE',metrics:spec.metrics}]}
 const {container}=render(<DynamicResult result={{...result,spec:custom}} view="preview"/>)
 expect(screen.getByRole('heading',{name:'核心数量'})).toBeInTheDocument()
 expect(screen.getByRole('heading',{name:'诊断明细'})).toBeInTheDocument()
 expect(screen.getByRole('table')).toBeInTheDocument()
 expect(container.querySelectorAll('svg')).toHaveLength(0)
 expect(container.querySelectorAll('.da-result-meta')).toHaveLength(1)
})
it('updates composed widget references when a metric is removed',async()=>{
 const user=userEvent.setup(),{api,generate,query}=setup()
 const m={code:'M1',name:'医嘱条数',source:'ORDER',sourceVersion:1,aggregate:'COUNT' as const,field:'orderId',filters:[]}
 const plan:PageSpec={...spec,template:'CUSTOM',dimension:'DAY',metrics:['M1','M2'],measures:[m,{...m,code:'M2',name:'第二指标'}],widgets:[{title:'第一项',type:'KPI',metrics:['M1']},{title:'第二项',type:'BAR',metrics:['M2']}]}
 generate.mockResolvedValue({status:'READY',message:'组合展示',spec:plan});query.mockImplementation(async(s:PageSpec)=>({...result,spec:s}))
 render(<DynamicAnalysisLibrary api={api}/>);await user.type(await screen.findByLabelText('业务分析需求'),'医嘱组合展示');await user.click(screen.getByRole('button',{name:'生成页面预览'}))
 await user.click(await screen.findByRole('tab',{name:'计算配置'}));await user.click(screen.getByRole('button',{name:'移除指标 1'}));await user.click(screen.getByRole('button',{name:'更新预览'}))
 await waitFor(()=>expect(query).toHaveBeenCalledTimes(2));const next=query.mock.calls[1][0]
 expect(next.measures[0].name).toBe('第二指标');expect(next.widgets).toEqual([{title:'第二项',type:'BAR',metrics:['M1']}])
})
