package com.rhn.pharmacy.application;
import com.rhn.pharmacy.api.InventoryOperationViews.*;import com.rhn.pharmacy.application.InventoryApplicationService.*;import com.rhn.pharmacy.domain.*;import com.rhn.pharmacy.infrastructure.*;import com.rhn.shared.context.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;
import static com.rhn.shared.api.BusinessErrors.*;
@Service
public class StockCountApplicationService{
 private static final Set<String>TYPES=Set.of("FULL","BIN","ITEM","CYCLE"),ACTIVE=Set.of("DRAFT","COUNTING","SUBMITTED","APPROVED");private static final DateTimeFormatter FORMAT=DateTimeFormatter.ofPattern("yyyyMMddHHmmss").withZone(ZoneOffset.UTC);
 private final StockCountRepository repository;private final StockCountLineRepository lineRepository;private final StockSiteRepository siteRepository;private final StockBinRepository binRepository;private final InventoryBalanceRepository balanceRepository;private final InventoryDocumentEventRepository eventRepository;private final InventoryApplicationService inventoryService;private final ExecutionContextProvider contextProvider;
 public StockCountApplicationService(StockCountRepository r,StockCountLineRepository l,StockSiteRepository s,StockBinRepository b,InventoryBalanceRepository balances,InventoryDocumentEventRepository events,InventoryApplicationService inventory,ExecutionContextProvider contexts){repository=r;lineRepository=l;siteRepository=s;binRepository=b;balanceRepository=balances;eventRepository=events;inventoryService=inventory;contextProvider=contexts;}
 @Transactional public CountView create(CreateCountCommand input){ExecutionContext c=context();String request=required(input.requestCode(),"COUNT_REQUEST_REQUIRED","盘点请求编码不能为空");StockCount existing=repository.findByTenantIdAndRequestCode(c.tenantId(),request).orElse(null);if(existing!=null)return view(c,existing);StockSite site=requireSite(c,input.stockSiteId());String type=upper(input.countType());if(!TYPES.contains(type))throw badRequest("COUNT_TYPE_INVALID","盘点类型不受支持");for(StockCount open:repository.findByTenantIdAndStockSiteIdOrderBySnapshotAtDesc(c.tenantId(),site.id()))if(ACTIVE.contains(open.status()))throw conflict("COUNT_ACTIVE_CONFLICT","当前库存站点已有未完成盘点单");Long binId=input.stockBinId();if("BIN".equals(type)&&binId==null)throw badRequest("COUNT_BIN_REQUIRED","货位盘点必须选择货位");if(binId!=null){StockBin bin=binRepository.findByIdAndTenantId(binId,c.tenantId()).orElseThrow(()->notFound("STOCK_BIN_NOT_FOUND","未找到盘点货位"));if(!site.id().equals(bin.stockSiteId())||!bin.active()||!bin.countAllowed())throw badRequest("COUNT_BIN_INVALID","所选货位不属于当前站点或未开放盘点");}Set<Long>items=input.stockItemIds()==null?Set.of():new HashSet<>(input.stockItemIds());if(Set.of("ITEM","CYCLE").contains(type)&&items.isEmpty())throw badRequest("COUNT_ITEMS_REQUIRED","按项目盘点必须选择经营项目");List<InventoryBalance> balances=binId==null?balanceRepository.findByTenantIdAndStockSiteIdOrderByStockBinIdAscStockItemIdAscStockLotIdAsc(c.tenantId(),site.id()):balanceRepository.findByTenantIdAndStockBinIdOrderByStockItemIdAscStockLotIdAsc(c.tenantId(),binId);if(!items.isEmpty())balances=balances.stream().filter(v->items.contains(v.stockItemId())).toList();if(balances.isEmpty())throw conflict("COUNT_SCOPE_EMPTY","当前盘点范围没有库存记录");String no=clean(input.countNo());if(no==null)no="CT"+FORMAT.format(Instant.now())+com.rhn.shared.id.GlobalIds.randomSuffix(6);StockCount value=new StockCount(c.tenantId(),site.organizationId(),site.id(),binId,no,request,type,Instant.now(),clean(input.reason()),clean(input.description()),c.subjectId());repository.save(value);int sort=0;for(InventoryBalance balance:balances)lineRepository.save(new StockCountLine(c.tenantId(),value.id(),++sort,balance));append(c,value,"CREATED",null,value.status(),null);lineRepository.flush();repository.flush();return view(c,value);}
 @Transactional public CountView start(Long id){ExecutionContext c=context();StockCount v=lock(c,id);String from=v.status();transition(()->v.start(c.subjectId()));append(c,v,"STARTED",from,v.status(),null);return view(c,v);}
 @Transactional public CountView record(Long id,RecordCountCommand input){ExecutionContext c=context();StockCount v=lock(c,id);if(!"COUNTING".equals(v.status()))throw conflict("COUNT_STATE_INVALID","只有盘点中的单据可以录入实盘数量");List<StockCountLine>lines=lineRepository.lockByCount(c.tenantId(),id);Map<Long,RecordCountLineCommand>values=new HashMap<>();if(input.lines()==null||input.lines().isEmpty())throw badRequest("COUNT_RECORD_LINES_REQUIRED","至少需要录入一条实盘记录");for(RecordCountLineCommand d:input.lines())if(values.put(d.countLineId(),d)!=null)throw badRequest("COUNT_RECORD_DUPLICATE","实盘明细不能重复");for(StockCountLine line:lines){RecordCountLineCommand d=values.get(line.id());if(d==null)continue;try{line.record(d.countedQuantity(),clean(d.varianceReason()),c.subjectId());}catch(IllegalStateException e){throw badRequest("COUNT_RECORD_INVALID",e.getMessage());}}lineRepository.flush();append(c,v,"COUNT_RECORDED",v.status(),v.status(),clean(input.description()));return view(c,v);}
 @Transactional public CountView submit(Long id){ExecutionContext c=context();StockCount v=lock(c,id);List<StockCountLine>lines=lineRepository.lockByCount(c.tenantId(),id);if(lines.stream().anyMatch(l->l.countedQuantity()==null))throw conflict("COUNT_RECORD_INCOMPLETE","必须完成全部盘点明细后才能提交");String from=v.status();transition(()->v.submit(c.subjectId()));append(c,v,"SUBMITTED",from,v.status(),null);return view(c,v);}
 @Transactional public CountView approve(Long id,DecisionCommand input){ExecutionContext c=context();StockCount v=lock(c,id);String from=v.status();transition(()->v.approve(c.subjectId(),clean(input.reason())));append(c,v,"APPROVED",from,v.status(),clean(input.reason()));return view(c,v);}
 @Transactional public CountView reject(Long id,DecisionCommand input){ExecutionContext c=context();StockCount v=lock(c,id);String reason=required(input.reason(),"COUNT_REJECTION_REASON_REQUIRED","驳回盘点单必须填写原因");String from=v.status();transition(()->v.reject(c.subjectId(),reason));append(c,v,"REJECTED",from,v.status(),reason);return view(c,v);}
 @Transactional public CountView post(Long id){ExecutionContext c=context();StockCount v=lock(c,id);if("POSTED".equals(v.status()))return view(c,v);if(!"APPROVED".equals(v.status()))throw conflict("COUNT_STATE_INVALID","只有审核通过的盘点单可以调整库存");List<StockCountLine>lines=lineRepository.lockByCount(c.tenantId(),id);List<DocumentPostingLineCommand>posting=new ArrayList<>();for(StockCountLine line:lines){InventoryBalance balance=balanceRepository.lockByIdAndTenantId(line.inventoryBalanceId(),c.tenantId()).orElseThrow(()->conflict("COUNT_BALANCE_MISSING","盘点快照对应库存已不存在"));if(balance.revision()!=line.inventoryBalanceRevision())throw conflict("COUNT_BALANCE_CHANGED","盘点期间库存已变化，请重新盘点后再审核调整");if(line.varianceQuantity()==null)throw conflict("COUNT_RECORD_INCOMPLETE","盘点单存在未录入明细");if(line.varianceQuantity().signum()!=0)posting.add(new DocumentPostingLineCommand(line.stockBinId(),line.stockItemId(),line.stockLotId(),line.stockStatus(),line.varianceQuantity(),balance.averageUnitCost(),false));}Long transactionId=null;if(!posting.isEmpty())transactionId=inventoryService.postDocument(new DocumentPostingCommand(v.requestCode()+":ADJUST","COUNT","STOCK_COUNT",v.countNo(),v.stockSiteId(),Instant.now(),"盘点盈亏调整",posting)).id();Long txn=transactionId;String from=v.status();transition(()->v.post(c.subjectId(),txn));append(c,v,"POSTED",from,v.status(),null);repository.flush();return view(c,v);}
 @Transactional(readOnly=true)public List<CountView>list(Long siteId){ExecutionContext c=context();requireSite(c,siteId);return repository.findByTenantIdAndStockSiteIdOrderBySnapshotAtDesc(c.tenantId(),siteId).stream().map(v->view(c,v)).toList();}
 private StockCount lock(ExecutionContext c,Long id){StockCount v=repository.lockByIdAndTenantId(id,c.tenantId()).orElseThrow(()->notFound("COUNT_NOT_FOUND","未找到盘点单"));requireSite(c,v.stockSiteId());return v;}private StockSite requireSite(ExecutionContext c,Long id){StockSite s=siteRepository.findByIdAndTenantId(id,c.tenantId()).orElseThrow(()->notFound("STOCK_SITE_NOT_FOUND","未找到库存站点"));if(!c.canAccessOrganization(s.organizationId()))throw badRequest("PHARMACY_ORGANIZATION_SCOPE_INVALID","当前上下文不能访问该机构库存");if(s.departmentId()!=null&&!s.departmentId().equals(c.departmentId()))throw badRequest("PHARMACY_SITE_CONTEXT_MISMATCH","当前工作科室与盘点站点不一致");return s;}
 private void append(ExecutionContext c,StockCount v,String event,String from,String to,String reason){eventRepository.save(new InventoryDocumentEvent(c.tenantId(),v.organizationId(),"COUNT",v.id(),v.countNo(),event,from,to,c.subjectId(),reason,v.requestCode()));}private CountView view(ExecutionContext c,StockCount v){List<CountLineView>lines=lineRepository.findByTenantIdAndStockCountIdOrderBySortOrder(c.tenantId(),v.id()).stream().map(l->new CountLineView(l.id(),l.revision(),l.sortOrder(),l.inventoryBalanceId(),l.inventoryBalanceRevision(),l.stockBinId(),l.stockItemId(),l.stockLotId(),l.stockStatus(),l.bookQuantity(),l.countedQuantity(),l.varianceQuantity(),l.countResult(),l.countedAt(),l.countedBy(),l.varianceReason())).toList();return new CountView(v.id(),v.revision(),v.organizationId(),v.stockSiteId(),v.stockBinId(),v.countNo(),v.requestCode(),v.countType(),v.status(),v.snapshotAt(),v.startedAt(),v.startedBy(),v.submittedAt(),v.submittedBy(),v.approvedAt(),v.approvedBy(),v.postedAt(),v.postedBy(),v.reason(),v.description(),v.inventoryTransactionId(),lines);}
 private ExecutionContext context(){ExecutionContext c=contextProvider.requireCurrent();if(!c.hasWorkContext())throw badRequest("PHARMACY_WORK_CONTEXT_REQUIRED","库存操作必须选择工作机构和科室");return c;}private void transition(Runnable r){try{r.run();}catch(IllegalStateException e){throw conflict("COUNT_STATE_INVALID",e.getMessage());}}private String upper(String v){String r=clean(v);return r==null?null:r.toUpperCase();}private String required(String v,String code,String msg){String r=clean(v);if(r==null)throw badRequest(code,msg);return r;}private String clean(String v){return v==null||v.isBlank()?null:v.trim();}
 public record CreateCountCommand(Long stockSiteId,Long stockBinId,String countNo,String requestCode,String countType,List<Long>stockItemIds,String reason,String description){}public record RecordCountLineCommand(Long countLineId,BigDecimal countedQuantity,String varianceReason){}public record RecordCountCommand(String description,List<RecordCountLineCommand>lines){}public record DecisionCommand(String reason){}
}
