package com.rhn.outpatient.triage;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.List;

public class TriageContracts {

    public record TriageRecordResponse(
            Long id,
            Long tenantId,
            Long organizationId,
            Long residentId,
            Long encounterId,
            Long registrationId,
            String triageNo,
            Instant triageTime,
            String triageNurseId,
            String triageNurseName,
            String patientName,
            String gender,
            Integer age,
            LocalDate birthDate,
            String phone,
            String idCardNo,
            String healthRecordNo,
            String arrivalMethod,
            String companionType,
            String chiefComplaint,
            String symptoms,
            BigDecimal temperature,
            BigDecimal pulseRate,
            BigDecimal respiratoryRate,
            BigDecimal systolic,
            BigDecimal diastolic,
            BigDecimal oxygenSaturation,
            BigDecimal bloodGlucose,
            Integer painScore,
            String consciousness,
            boolean fever,
            String epidemicHistory,
            String riskTags,
            String triageLevel,
            String triageReason,
            Long targetDepartmentId,
            String targetDepartmentName,
            String targetDoctorId,
            String targetDoctorName,
            String greenChannel,
            String disposition,
            String status,
            String notes,
            Instant createdAt,
            Instant updatedAt
    ) {
        public static TriageRecordResponse from(OutpatientTriageRecord entity) {
            return new TriageRecordResponse(
                    entity.getId(),
                    entity.getTenantId(),
                    entity.getOrganizationId(),
                    entity.getResidentId(),
                    entity.getEncounterId(),
                    entity.getRegistrationId(),
                    entity.getTriageNo(),
                    entity.getTriageTime(),
                    entity.getTriageNurseId(),
                    entity.getTriageNurseName(),
                    entity.getPatientName(),
                    entity.getGender(),
                    entity.getAge(),
                    entity.getBirthDate(),
                    entity.getPhone(),
                    entity.getIdCardNo(),
                    entity.getHealthRecordNo(),
                    entity.getArrivalMethod(),
                    entity.getCompanionType(),
                    entity.getChiefComplaint(),
                    entity.getSymptoms(),
                    entity.getTemperature(),
                    entity.getPulseRate(),
                    entity.getRespiratoryRate(),
                    entity.getSystolic(),
                    entity.getDiastolic(),
                    entity.getOxygenSaturation(),
                    entity.getBloodGlucose(),
                    entity.getPainScore(),
                    entity.getConsciousness(),
                    entity.isFever(),
                    entity.getEpidemicHistory(),
                    entity.getRiskTags(),
                    entity.getTriageLevel(),
                    entity.getTriageReason(),
                    entity.getTargetDepartmentId(),
                    entity.getTargetDepartmentName(),
                    entity.getTargetDoctorId(),
                    entity.getTargetDoctorName(),
                    entity.getGreenChannel(),
                    entity.getDisposition(),
                    entity.getStatus(),
                    entity.getNotes(),
                    entity.getCreatedAt(),
                    entity.getUpdatedAt()
            );
        }
    }

    public record CreateTriageRequest(
            Long organizationId,
            Long residentId,
            Long encounterId,
            Long registrationId,
            @NotBlank(message = "患者姓名不能为空") @Size(max = 100) String patientName,
            @NotBlank(message = "患者性别不能为空") @Size(max = 20) String gender,
            Integer age,
            LocalDate birthDate,
            @Size(max = 30) String phone,
            @Size(max = 30) String idCardNo,
            @Size(max = 64) String healthRecordNo,
            String arrivalMethod,
            String companionType,
            @Size(max = 1000) String chiefComplaint,
            @Size(max = 1000) String symptoms,
            BigDecimal temperature,
            BigDecimal pulseRate,
            BigDecimal respiratoryRate,
            BigDecimal systolic,
            BigDecimal diastolic,
            BigDecimal oxygenSaturation,
            BigDecimal bloodGlucose,
            Integer painScore,
            String consciousness,
            boolean fever,
            @Size(max = 1000) String epidemicHistory,
            @Size(max = 1000) String riskTags,
            @NotBlank(message = "分诊级别不能为空") String triageLevel,
            @Size(max = 1000) String triageReason,
            Long targetDepartmentId,
            String targetDepartmentName,
            String targetDoctorId,
            String targetDoctorName,
            String greenChannel,
            String disposition,
            String notes,
            String nurseId,
            String nurseName
    ) {}

    public record UpdateTriageRequest(
            Long residentId,
            Long encounterId,
            Long registrationId,
            @NotBlank(message = "患者姓名不能为空") @Size(max = 100) String patientName,
            @NotBlank(message = "患者性别不能为空") @Size(max = 20) String gender,
            Integer age,
            LocalDate birthDate,
            @Size(max = 30) String phone,
            @Size(max = 30) String idCardNo,
            @Size(max = 64) String healthRecordNo,
            String arrivalMethod,
            String companionType,
            @Size(max = 1000) String chiefComplaint,
            @Size(max = 1000) String symptoms,
            BigDecimal temperature,
            BigDecimal pulseRate,
            BigDecimal respiratoryRate,
            BigDecimal systolic,
            BigDecimal diastolic,
            BigDecimal oxygenSaturation,
            BigDecimal bloodGlucose,
            Integer painScore,
            String consciousness,
            boolean fever,
            @Size(max = 1000) String epidemicHistory,
            @Size(max = 1000) String riskTags,
            @NotBlank(message = "分诊级别不能为空") String triageLevel,
            @Size(max = 1000) String triageReason,
            Long targetDepartmentId,
            String targetDepartmentName,
            String targetDoctorId,
            String targetDoctorName,
            String greenChannel,
            String disposition,
            String status,
            String notes
    ) {}

    public record TriageStatisticsResponse(
            long totalCount,
            long level1CriticalCount,
            long level2UrgentCount,
            long level3RoutineUrgentCount,
            long level4NonUrgentCount,
            long feverCount,
            long greenChannelCount
    ) {}

    public record DepartmentRecommendationResponse(
            Long departmentId,
            String departmentName,
            int score,
            String rationale,
            int availableScheduleCount,
            String alertNotice,
            String source,
            boolean scheduledToday
    ) {
        public DepartmentRecommendationResponse(Long departmentId, String departmentName, int score,
                                                String rationale, int availableScheduleCount, String alertNotice) {
            this(departmentId, departmentName, score, rationale, availableScheduleCount, alertNotice,
                    "LOCAL_ASSIST", availableScheduleCount > 0);
        }
    }

    public record PendingEncounterResponse(
            Long encounterId,
            Long registrationId,
            Long residentId,
            String healthRecordNo,
            String residentName,
            String gender,
            LocalDate birthDate,
            Integer age,
            String phone,
            String registrationNo,
            String ticketNo,
            int sequenceNo,
            Long departmentId,
            String departmentName,
            String practitionerName,
            Instant registeredAt,
            boolean triaged,
            String triageLevel,
            Long triageId,
            String triageNo
    ) {}
}
